### DISCUSSION TITLE
Apparent vs Real power measurement

### DISCUSSION THREAD

**Discussion by jcam** [emporia-vue-local/esphome#102] [General]
So I've been trying to figure out why my older monitoring system reports different values than the Vue, and I thought it had something to do with apparent vs real power (turns out that I had configured the clamps wrong months ago, so it really was just reporting high).

I read through this thread on the emporia forum: https://community.emporiaenergy.com/topic/real-vs-apparent-vs-reactive-power-why-things-dont-add-up-in-the-app/

Apparently for 3 phase installations, they measure apparent / VA power and for split phase 120/240, they measure real power, calculating phase shift / power factor automatically. I'm hoping this works for our local installations as well!

Has anyone done many measurements? Do you have split phase 120/240 with big inductive loads (air conditioners, etc), and do your measurements match up with the electric company?

I'm going to hook up one of my emporia's in the garage at the service entrance monitoring both sets of inputs (I have 400A / dual 200A service... I'll put one set of clamps on the A and B inputs and the other set of clamps on inputs 15 and 16 set to a x4 multiplier) and see if my numbers match up with the meter, then work down to the individual loads from there. I have a feeling my brultech gem was not doing as good a job... officially they say they report real power, not apparent... but there's only one voltage sensor, so I'm not convinced.

**Comment by flaviut** [comment]
I'd like to share this spreadsheet, which shows raw data from the Emporia Vue sensors: https://docs.google.com/spreadsheets/d/1Yu98tDRhFJqqMntNak6X297SKyzQtf0_Cvv_g7qKewk/edit#gid=0

![spreadsheet screenshot](https://user-images.githubusercontent.com/5213469/209589365-0c4a006c-80ab-4608-8d74-a6ca39505382.png)

This data is directly mapped into the sensor readings you see using the configuration. No smartness, no anything else. That said, it is technically possible for the actual sensor to process the data differently depending on if it is a 3-phase or split-phase system. However, I'm skeptical.

[There's been recent changes improve the current reporting](https://github.com/emporia-vue-local/esphome/pull/90), which is suspected to return power-factor dependent results. Make sure your config is up to date, and give it a try:

```
      - phase_id: barn_phase_b_v
        input: "B"
        power:
          name: "Barn PhaseB Power"
          id: barn_phase_b_power
          device_class: power
          filters: [ *moving_avg, *pos ]
        current:
          name: "Barn PhaseB Current"
          device_class: current
          filters: [ *moving_avg, *pos ]
```

If you do figure out something conclusive, please go ahead and make a pull request to the documentation in this repo!
