### DISCUSSION TITLE
Anyone else getting i2c error 3 after updating esphome version?

### DISCUSSION THREAD

**Discussion by derekyle** [emporia-vue-local/esphome#108] [General]
All the sudden, I'm getting NaN responses from all sensors on the vue2 and the following error:

" Failed to read from sensor due to I2C error 3"

appears over and over in the logs. I saw one other person with this error in a now closed issue, but no update on if/how they fixed it. This seems to have appeared suddenly, but I believe it started occurring after the most recent version update of ESPhome. It was running for a few weeks without issue before that.

Is anyone else getting an error after any recent updates?

I have tried power cycling the vue2 as well as clearing the build cache and rebuilding/reinstalling the firmware, but still getting the error. I also tried adjusting the i2c frequency down to 150khz, 100, 50, and back to 200, but also no change. Any help would be appreciated.

I'm currently running esphome v 2022.12.3 and home assistant core version 2023.1.4. Not sure if the version of anything except esphome should make a difference.

**Comment by flaviut** [comment]
[Error 3 is "Timeout"](https://github.com/esphome/esphome/blob/dev/esphome/components/i2c/i2c_bus.h#L10-L19).

I'm not sure what's wrong. You can always downgrade and see if that works. Maybe check and/or reflow some solder joints if you have the equipment for that.

**Reply by derekyle** [reply]
I'm surprised no one else is having this issue. I am now on my 3rd Vue2 and just like before, it worked perfectly at first. And then this time, just a few days after installing it just all the sudden started returning the i2c error 3 again for every sensor.  Power cycling doesn't fix it, left it off for a few minutes then reconnected the power. I'm going to post my config below just in case I have something weird. It just seems so bizarre that I would have this problem with 3 units. I'm beginning to wonder if something is up with my power and it is getting a surge or something. But power is pretty stable and wiring is good here. So I'm really at a loss. 

```
esphome:
  name: emporiavue2

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components: [ emporia_vue ]

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret commmon_ota_password

logger:
  baud_rate: 0

preferences:
  flash_write_interval: "48h"

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a
time:
  - platform: sntp
    id: my_time

.defaultfilters:
  - &moving_avg
    sliding_window_moving_average:
      window_size: 6
      send_every: 6
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    lambda: 'return max(x, 0.0f);'
  - &abs
    lambda: 'return abs(x);'
  - &neg
    lambda: 'return min(x, 0.0f);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a 
        input: RED  
        calibration: 0.021355  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
      
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
      - id: phase_b  
        input: BLACK  
        calibration: 0.023102  
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A" 
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_b
        input: "B" 
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg, *pos]
      - { phase_id: phase_a, input:  "1", power: { name: "HVAC Power A", id:  cir1, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "2", power: { name: "HVAC Power B", id:  cir2, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "3", power: { name: "Kitchen Power", id:  cir3, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "4", power: { name: "Microwave Power", id:  cir4, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "5", power: { name: "Bathroom Plugs Power", id:  cir5, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "6", power: { name: "Bedroom Plugs Power", id:  cir6, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "7", power: { name: "HVAC Blower A", id:  cir7, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "8", power: { name: "Main Lights/HVAC Blower B", id:  cir8, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "9", power: { name: "Fridge Power", id:  cir9, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "10", power: { name: "Server/Laundry Power", id: cir10, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "11", power: { name: "Garage Power", id: cir11, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "12", power: { name: "Office/South Kitchen Plugs Power", id: cir12, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "13", power: { name: "Dishwasher Power", id: cir13, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "14", power: { name: "Disposal Power", id: cir14, filters: [ *moving_avg, *pos ] } }
 

  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: 2.88s
    id: total_power
    unit_of_measurement: "W"
    
  - platform: template
    name: "HVAC Blower"
    lambda: return id(cir7).state * 2;
    update_interval: 2.88s
    id: hvac_blower_power
    unit_of_measurement: "W"

  - platform: template
    name: "HVAC Compressor"
    lambda: return id(cir1).state + id(cir2).state;
    update_interval: 2.88s
    id: hvac_compressor_power
    unit_of_measurement: "W"
  
  - platform: template
    name: "Main Lights"
    lambda: return id(cir8).state - id(cir7).state;
    update_interval: 2.88s
    id: main_lights_power
    unit_of_measurement: "W"
  
  - platform: template
    name: "Balance Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state - id(cir14).state - id(cir13).state - id(cir12).state - id(cir11).state - id(cir10).state - id(cir9).state - id(cir8).state - id(cir7).state - id(cir6).state - id(cir5).state - id(cir4).state - id(cir3).state - id(cir2).state - id(cir1).state;
    update_interval: 2.88s
    id: balance_power
    unit_of_measurement: "W"
  
  - platform: template
    name: "HVAC Power"
    lambda: return id(hvac_blower_power).state + id(cir1).state + id(cir2).state;
    update_interval: 2.88s
    id: total_hvac_power
    unit_of_measurement: "W"

  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, name:  "Kitchen Daily Energy" }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, name:  "Microwave Daily Energy" }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, name:  "Bathroom Plugs Daily Energy" }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, name:  "Bedroom Daily Energy" }
  - { power_id:  main_lights_power, platform: total_daily_energy, accuracy_decimals: 0, name:  "Main Lights Daily Energy" }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, name:  "Fridge Daily Energy" }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, name: "Server/Laundry Daily Energy" }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, name: "Garage Daily Energy" }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, name: "Office/Kitchen Plugs Daily Energy" }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, name: "Dishwasher Daily Energy" }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, name: "Disposal Daily Energy" }
  - { power_id:  hvac_blower_power, platform: total_daily_energy, accuracy_decimals: 0, name:  "HVAC Blower Daily Energy" }
  - { power_id: hvac_compressor_power, platform: total_daily_energy, accuracy_decimals: 0, name: "HVAC Compressor Daily Energy" }
  - { power_id: total_hvac_power, platform: total_daily_energy, accuracy_decimals: 0, name: "HVAC Daily Energy" }
 
```
