### DISCUSSION TITLE
How to switch branches in device?

### DISCUSSION THREAD

**Discussion by copekyle** [emporia-vue-local/esphome#116] [Q&A]
I just realized as I was looking through bug fixes today that my yaml code was using emporia-vue-2022.4.0 as the external component. This must be that I used an old install guide when setting my devices up. I'm attempted to switch it to the DEV branch but when I do that in my yaml file, I can't see that it changes anything in the compile. I also noticed that my resources in my ESPHome folders haven't updated since 9/10/2022 (emporia_vue.cpp file).

How do I make sure the new external location is being used and all the code fixes are being applied to my device?

**Comment by zanix** [comment]
In the config, find this section

```yaml
external_components:
```

And change to:

```yaml
external_components:
  - source: github://emporia-vue-local/esphome@dev
    components: [ emporia_vue ]
```
