### DISCUSSION TITLE
Voltage of main legs is skewed in software for some reason... thoughts?

### DISCUSSION THREAD

**Discussion by Aston77** [emporia-vue-local/esphome#12] [Q&A] [answered]
Tested with a multimeter I get the following...

**Phase A** = 123.9 V
**Phase B** = 124.2 V
**Total A+B** = 248.1 V

But when I look at the balance in software on ESPHome  this is what I get 
<img width="308" alt="image" src="https://user-images.githubusercontent.com/78501124/185682420-d51b3db1-0240-4788-8aa7-1953a859e78c.png">

FWIW - My CT clamps are installed properly and I have plugged and unplugged the 3.5mm wires into the Vue.

```
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg, *pos]
```
