### DISCUSSION TITLE
Total Daily Energy sensors don't reset anymore

### DISCUSSION THREAD

**Discussion by inuites** [emporia-vue-local/esphome#120] [Q&A]
Dear all,

I have esphome running on my Emporia vue since few months.
Everything was running flawlessly but since 1 week total daily energy sensors don't reset anymore everyday.
I already flashed the board two times but It doesn't work. The board keep the previous value in memory and still do the increment.

It is strange because I haven't touch anything since long time ago.
My configuration was working and it is similar to the one from the githup except I'm using 3 phases.

Is someone else encountered the same issue ?

**Comment by rb2k** [comment]
I currently noticed that mine don't reset either.
It's a bit odd since I have the time class enabled and it seems to be happy with that.

Did you figure anything out over the past month?


EDIT:

Ah yeah, seems like even though I had the time class, it never actually synced. Not sure why, don't have firewall rules set up against that.

Switched it from sntp to this, that worked:

```
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"
```

(had to clean build files once)
