### DISCUSSION TITLE
Getting 0 wattage on Phase/Total Power

### DISCUSSION THREAD

**Discussion by djvj1** [emporia-vue-local/esphome#127] [Q&A] [answered]
HA is showing 0 power on both my main phases, but voltage and frequency are fine. I have the CT's oriented properly with the 'To Breaker' arrow pointing down toward the breakers. I have the black wire going to a Phase A breaker and Red wire going to a Phase B breaker. Blue/white wires going to neutral/ground. I didn't change anything in that section of the default yaml config for the sensors except the 'name:' labels. The circuits all seem to be showing correct usage, just not phases or total.

Am I missing something?

I just reconnected the black and red wires and my Phase B is 52.4V / 8 angle / 2934W. Phase A showing 122V / 59.8Hz / 0W.

**Comment by Roemer** [comment]
I have the same issue. I finally added the Phases A-C (the individual ones work perfectly) and it shows blank 0 Watts on all of them.

**Comment by flaviut** [comment]
Sounds like the top 2-3 `ct_clamps` entries have the wrong phase entered. Make sure those match reality.

Other than that, you can try removing the `*pos` on the top 2-3  `ct_clamps` entries to see more details, and you can try double-checking that the physical plugs are fully inserted, since I had a bit of trouble with that.

**Reply by Roemer** [reply]
Dang, they all show negative values. Guess I put the clamp on backwards.

**Reply by flaviut** [reply]
another potential issue is that the wrong phase was entered and you are on a split-phase system.

**Reply by Roemer** [reply]
I double and tripple checked the phases. They are correct. I now rotated all the clamps and now it works. Strange, I had the clamps directly after the "counter" but before all breakers. I had to put them that the arrow points to the breaker instead of to the counter. In my head, this should be the other way around but oh well, as long as it works.

**Comment by djvj1** [comment, marked as answer]
I had to flip both the CT clamps around so breaker arrow was pointing toward outside and not down into the panel.

**Reply by agoode** [reply]
I didn't want to change the clamp direction away from how it was marked. Instead, I changed the YAML to use `invert` instead of `pos`:

```
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *invert]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg, *invert]
```
