### DISCUSSION TITLE
Emporia Vue and MQTT?

### DISCUSSION THREAD

**Discussion by hazymat** [emporia-vue-local/esphome#132] [General]
I use Node-RED with MQTT for the majority of my automation, rather than HomeAssistant.

Thinking about purchasing an Emporium Vue gen 2, and to be honest I mostly run Tasmota, however Tasmota doesn't support this energy monitoring device.

How simple it is to get the Vue up and running with MQTT, to receive power measurements every 30 seconds or so from each sensor?

Is it possible to customise the message format, e.g. have all sensor info within one message or a message on each topic corresponding to each sensor?

Is it possible to set the sensor reading timer (I'd call it the "tele" period) in ESPHome?

**Comment by flaviut** [comment]
> How simple it is to get the Vue up and running with MQTT

I don't personally do it, but I've heard some folks have had good luck with this. [Here's the ESPHome mqtt documentation](https://esphome.io/components/mqtt.html), it seems quite extensive and customizable. You don't need to make use of the customization though, just adding the `mqtt:` block is enough to get messages flowing.

> to receive power measurements every 30 seconds or so from each sensor?

Should be pretty easy, edit this filter from the example config like this:

```
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 30 seconds
      window_size: 125
      # we push a new value every 30 seconds
      send_every: 125
```

There's a few more filters that allow changing the "tele period" if SWMA doesn't work for you: https://esphome.io/components/sensor/index.html#throttle
