### DISCUSSION TITLE
Voltage calibration

### DISCUSSION THREAD

**Discussion by lahayeg** [emporia-vue-local/esphome#143] [Q&A] [answered]
Hello,

I flash with the current version of dev branche. I wanted to start calibration on voltage phase. I already have a Shelly 3 EM which I trust because it has <1% error compare to electricity supplier.
It tried to changed the calibration but still have gap between both Emporia and Shelly

```
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a 
        input: BLACK  
        calibration: 0.02190740741
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*moving_avg, *pos]
      - id: phase_b  
        input: RED  
        calibration: 0.01085678286  
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
      - id: phase_c  
        input: BLUE  
        calibration: 0.02132423208  
        voltage:
          name: "Phase C Voltage"
          filters: [*moving_avg, *pos]
```

![Screenshot 2023-03-13 at 09 42 07](https://user-images.githubusercontent.com/7801817/224651535-c243e13b-7286-4213-905f-7fbee62caa6f.png)
