### DISCUSSION TITLE
Emporia Vue 2 - Prometheus Integration

### DISCUSSION THREAD

**Discussion by Greg-MM** [emporia-vue-local/esphome#144] [General]
Anyone looking to use Prometheus to scrape metrics standalone (I don't use Home Assistant)
this is the configuration I am using, for some reason my modified Prometheus component is not compiling the .cpp file so I had to move the function bodies to the .h file, not sure why, if anyone knows let me know

also let me know if you test this as all my readings are 0 except for phase voltages showing near 0, but I haven't actually installed my unit yet so there are no CT's plugged in and I am just powering the device from the USB->TTL, but I think it should work

```
external_components:
  - source: github://emporia-vue-local/esphome@dev
    components:
      - emporia_vue
  - source: github://spali/esphome@pr3500
    components:
      - web_server
      - web_server_idf
      - web_server_base
  - source: github://Greg-MM/esphome-prometheus-idf@master
    components:
      - prometheus

web_server:

prometheus:
```
