### DISCUSSION TITLE
Reset all (energy) values

### DISCUSSION THREAD

**Discussion by eigenphase** [emporia-vue-local/esphome#146] [Q&A] [answered]
I'd like to have a clean start to confirm that all energy calculations make sense. So I'd like to reset them and start from scratch. From the FAQ:

> I've recorded negative energy values and I want to reset them
> Sensor values are saved to the esp32 flash. You can reset all sensors by implementing a [factory reset button](https://esphome.io/components/button/factory_reset.html).

But this page cautions that everything gets erased such as Wifi passwords etc.
If I do this, will my wifi password, mqtt etc be erased as well? And more importantly, will I use connection to the device (and have to reflash via serial)?

Assuming this is NOT dangerous, can I just replace 

```
button:
  - platform: template
    name: "Two Beeps"
    on_press:
      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"
```

with

```
button:
  - platform: template
    name: "Two Beeps"
    on_press:
      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

  - platform: factory_reset
    name: Restart with Factory Default Settings
```
