### DISCUSSION TITLE
Single phase and using all 3 200A CTs on supply, load, & PV

### DISCUSSION THREAD

**Discussion by LordGarth6** [emporia-vue-local/esphome#163] [Q&A]
Hi All,  - edit appologies seems i cant get the github code function to work right
just a query, im trying to get this to work. tested my unit with base script works fine, but this isnt quite working.
Have i made a config thats not applicable to the hardware/software?

My config is UK single phase. so i removed phase b voltage.

CT A around the supply cable from grid labelled somthing like "grid" or "grid power"
CT B around the incoming cable to my distribution board labelled somthing like "load" or "load power"
CT C around the out/incoming cable from PV Battery system somthing like "PV" or "pv power"
11 other single circuits all on phase A

```
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.01285 # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
         To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*moving_avg, *pos]

    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Grid"
          id: grid_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_a
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Load"
          id: load_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_a
        input: "C"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "PV Battery System"
          id: pv_power
          device_class: power
          filters: [*moving_avg, *pos]
       Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { name: "Central Heating", id:  cir1, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input:  "2", power: { name: "Shower", id:  cir2, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input:  "3", power: { name: "Cooker", id:  cir3, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input:  "4", power: { name: "Garage", id:  cir4, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input:  "5", power: { name: "Office", id:  cir5, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input:  "6", power: { name: "Upstairs Sockets", id:  cir6, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input:  "7", power: { name: "Kitchen Sockets", id:  cir7, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input:  "8", power: { name: "Downstairs Sockets", id:  cir8, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input:  "9", power: { name: "Downstairs Lights", id:  cir9, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input: "10", power: { name: "Upstairs Lights", id: cir10, filters: [ *moving_avg, *pos, multiply: 1 ] } }
      - { phase_id: phase_a, input: "11", power: { name: "Unused", id: cir11, filters: [ *moving_avg, *pos, multiply: 1 ] } }
  - platform: template
    name: "Total Power"
    lambda: return id(load_power).state;
    update_interval: 2s
    id: total_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
  - platform: template
    name: "Total Grid Power"
    lambda: return id(grid_power).state;
    update_interval: 2s
    id: total_grid_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Grid Energy"
    power_id: total_grid_power
    accuracy_decimals: 0
  - platform: template
    name: "Solar Power"
    lambda: return id(pv_power).state;
    id: total_solar_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Solar Energy"
    power_id: total_solar_power
    accuracy_decimals: 0
  - platform: template
    name: "Balance Power"
    lambda: !lambda |-
      return max(0.0f, id(total_power).state -
        id( cir1).state -
        id( cir2).state -
        id( cir3).state -
        id( cir4).state -
        id( cir5).state -
        id( cir6).state -
        id( cir7).state -
        id( cir8).state -
        id( cir9).state -
        id(cir10).state -
        id(cir11).state -;
    update_interval: 2.88s
    id: balance_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Balance Daily Energy"
    power_id: balance_power
    accuracy_decimals: 1
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 1 Daily Energy" }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 2 Daily Energy" }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 3 Daily Energy" }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 4 Daily Energy" }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 5 Daily Energy" }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 6 Daily Energy" }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 7 Daily Energy" }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 8 Daily Energy" }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 9 Daily Energy" }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 10 Daily Energy" }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 11 Daily Energy" }
```
