### DISCUSSION TITLE
Inputs A, B and C - what can be measured ?

### DISCUSSION THREAD

**Discussion by ozzy** [emporia-vue-local/esphome#168] [General]
Hi All,

Still amazed by this project.

Could anyone please tell me what can be measured on these inputs ?

So far I have:-
A-volts, A-frequency, A-Power;
B-volts, B-phase angle (hovers around 100 for me with a single phase site + single phase PV), B-power
C-power

Best regards
Oz

**Comment by flaviut** [comment]
Are you asking which parameters the hardware supports? In that case, you can also measure voltage, phase angle, and power on C.

**Reply by ozzy** [reply]
Hi @flaviut ,

Thank you for your response.
Yes I am asking both what the hardware can support and how to set up the config to extract the data.

Best regards,
Oz

**Reply by flaviut** [reply]
You would need to copy-paste the relevant phases and ct_clamps entries, replacing the names, colors, and letters as appropriate:

```
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*moving_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*moving_avg, *pos]
      - id: phase_c  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLUE  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase C Voltage"
          filters: [*moving_avg, *pos]
        phase_angle:
          name: "Phase C Phase Angle"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_c
        input: "C"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase C Power"
          id: phase_c_power
          device_class: power
          filters: [*moving_avg, *pos]
```
