### DISCUSSION TITLE
No main readings when A clamp is switched with B.

### DISCUSSION THREAD

**Discussion by karpeychik** [emporia-vue-local/esphome#174] [Q&A] [answered]
First of all, thanks for this work and thanks for great docs, this all was hugely inspiring.

I stumbled upon something that I don't understand and my question looks like lack of education which I am trying to fix. I was failing to get any readings from main A and B clamps after I connected everything in my panel. I have disconnected all the breaker-specific clamps and left main clamps only - still zeros on both A and B. I swapped A and B connectors on the device and I can read reasonable values now. Before doing the test I check that connectors all the way in. If I swap those connectors back I get zeros again on both main clamps.

My knowledge of electricity is not great, am I observing something obvious that I should educate myself on? Or is this some other kind of user error?

Really appreciate pointers.

**Comment by flaviut** [comment, marked as answer]
> I swapped A and B connectors on the device and I can read reasonable values now

Sounds to me like you have your phases backwards in your configuration. the `input` value in `ct_clamps` needs to match the correct phase in `phases`, and the wire color in `phases` needs to match the panel:

```
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*moving_avg, *pos]
...
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *pos]
```
