### DISCUSSION TITLE
3Phase Panels with 19 Circuits to monitor

### DISCUSSION THREAD

**Discussion by scar4731** [emporia-vue-local/esphome#184] [Q&A] [answered]
I have three 3 phase panels that contain 19 circuits that I would like to monitor.  The balanced two and three phase devices have one CT Sensor on only one leg whereas the unbalanced have a CT sensor on each leg.  I am interested in knowing how much Wattage is being used by each of the 19 circuits and am not concerned about knowing the full usage of all three panels, so I figured I could use the 200A CT sensors just like I would the 50A Sensors.  With the exemption of A, B, and C terminals (I still am not sure how to configure those in my YAML file, I have included the correct phase for each circuit.  On a 220VAC single phase AC, one leg seems to be reading correctly, but the other is measuring 0.  Why would that be?  Additionally devices that are on seem to be pulling very low wattage (i.e. 3.5W for a 5 ton package unit with a multiplier of 3).  What should I change in the YAML file to make terminals A,B,and C simply CT sensors and not use their data as a multiplier (if I can)?

**Comment by flaviut** [comment]
> exemption of A, B, and C terminals

Do you mean the `phases:` section? Configuring that incorrectly would cause problems that sound like what you're experiencing, where every clamp on a certain phase is reading 0.

Are the voltage readings accurate?

**Reply by scar4731** [reply]
Phase A: 112V, 59.8Hz
Phase B: 126.6V, 240deg (PH Angle)
Phase C: 113V, 125 deg (PH Angle)

But terminals A, B, and C are attached to circuits connected to Black, Red, and Blue (L1, L2, and L3) respectively.  

My Phases section looks like this: 

```
   phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*moving_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*moving_avg, *pos]
      - id: phase_c  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLUE  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase C Voltage"
          filters: [*moving_avg, *pos]
        phase_angle:
          name: "Phase C Phase Angle"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_c
        input: "C"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase C Power"
          id: phase_c_power
          device_class: power
          filters: [*moving_avg, *pos]
# Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_b, input:  "1", power: { name:  "Circuit 1", id:  cir1, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "2", power: { name:  "Circuit 2", id:  cir2, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "3", power: { name:  "Circuit 3", id:  cir3, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_c, input:  "4", power: { name:  "Circuit 4", id:  cir4, filters: [ *moving_avg, *pos, multiply: 2  ] } }
      - { phase_id: phase_b, input:  "5", power: { name:  "Circuit 5", id:  cir5, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "6", power: { name:  "Circuit 6", id:  cir6, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_c, input:  "7", power: { name:  "Circuit 7", id:  cir7, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "8", power: { name:  "Circuit 8", id:  cir8, filters: [ *moving_avg, *pos, multiply: 2  ] } }
      - { phase_id: phase_b, input:  "9", power: { name:  "Circuit 9", id:  cir9, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_c, input: "10", power: { name: Circuit 10", id: cir10, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "11", power: { name: "Circuit 11", id: cir11, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_c, input: "12", power: { name: "Circuit 12", id: cir12, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "13", power: { name: "Circuit 13", id: cir13, filters: [ *moving_avg, *pos, multiply: 3 ] } }
      - { phase_id: phase_c, input: "14", power: { name: "Circuit 14", id: cir14, filters: [ *moving_avg, *pos, multiply: 3  ] } }
      - { phase_id: phase_b, input: "15", power: { name: "Circuit 15", id: cir15, filters: [ *moving_avg, *pos, multiply: 3 ] } }
      - { phase_id: phase_b, input: "16", power: { name: "Circuit 16", id: cir16, filters: [ *moving_avg, *pos, multiply: 3  ] } }
```

All three legs have circuits attached that only show 0.  Additionally the Power for A, B, and C is at 0 as well.  Do the A, B, and C CT sensors have to be attached to the incoming L1, L2, and L3?
