### DISCUSSION TITLE
Help With Configuring Dual 200A Panels with Solar

### DISCUSSION THREAD

**Discussion by boukante** [emporia-vue-local/esphome#187] [General]
I have a 400A service with dual 200A panels and solar feeding into one of the panels. I was given an Emporia Vue2 for Fathers Day and have been researching the best way to integrate it into my Home Assistant setup. This has led me down the path of discovering the ESPHome options of the Vue.

I'm at the point where I'm trying to determine the best way to install the Vue and have come up with two options and would appreciate any advice:

1) Buy a second set of 200A CT clamps, install the Vue in the panel with solar, and extend the second set of CT wires from panel to the Vue in panel one. Extending the CT cables is approved by Emporia and I found this discussion (https://community.emporiaenergy.com/topic/gen2-and-2-200-amp-panels/#post-6583) about the need to wire the CTs in series so the phases match.

2) Buy a second Vue and install it in panel two. Then I will have to figure out how to combine the information from two separate Vues to show as one in HA for my consumption and solar excess production back to grid.

I'm a hardware guy and wiring is easy but it's not as neat and tidy of an install as #2. I'm not a software guy and wrapping my head around my needs for that configuration have me stymied at the moment. I would appreciate any pointers to instructions or help that can get me moving forward.

Thank you.

**Comment by flaviut** [comment]
for 1, I'd suggest at the very least putting the extended wire inside mains-rated conduit.

2 is straightforward: HomeAssistant doesn't actually care about which device a sensor reading comes from. If it makes it easier for you, you can tell the Vue to not report specific readings by removing them from the config. For example,

```
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*moving_avg, *pos]
```

becomes

```
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
```

You can also just entirely remove almost any entry (block of config, starting with a `-`) that you don't want. Only thing that's required is the `phases` configuration.
