### DISCUSSION TITLE
Power factor?

### DISCUSSION THREAD

**Discussion by clowrey** [emporia-vue-local/esphome#2] [General]
Does the emporia measure power factor in a way that we could display it on home assistant?

**Comment by flaviut** [comment]
> Does the emporia measure power factor

I suspect so. There's "current" readings in the data it sends over, and these current readings seem to be different from the power readings it also sends over.

> in a way that we could display it on home assistant

Definitely not. If you have reverse engineering skills, feel free to look into it. But unfortunately there is no such functionality out-of-the-box.

**Reply by clowrey** [reply]
Ahh I see.. so the microcontroller onboard would have to be re programmed then I take it.. yeah not something I have the skills or time for.. Wonder if I could approximate it by doing some math on the power vs current side of things..

**Reply by flaviut** [reply]
I'm not sure the MCU needs to be reprogrammed... but I think that maybe dumping the memory and trying to reverse-engineer it would be a good first step here to see how power are calculated vs how current readings are calculated.

Alternatively, and this would take lots of experimentation, ideally with well-characterized loads, but you could try something like the following to see if the "current" readings have anything to do with power factor:

```
      - phase_id: barn_phase_b_v
        input: "B"
        power:
          name: "Barn PhaseB Power"
          id: barn_phase_b_power
          device_class: power
          filters: [ *moving_avg, *pos ]
        current:
          name: "Barn PhaseB Current"
          device_class: current
          filters: [ *moving_avg, *pos ]
```

You can use a similar config for the smaller current clamps as well.

You'd be on your own, since I don't have time to look into this myself. But please let me know if you discover anything useful!

**Reply by Magfire** [reply]
I tried adding the current and the values I'm getting are way off what they should be. Can the CTs be calibrated the same as the voltage?
![total_pwr](https://user-images.githubusercontent.com/107365989/188244371-f5f09c13-6c96-40ce-a1aa-cd0945cce906.PNG)

**Reply by flaviut** [reply]
You can use sensor filters: https://esphome.io/components/sensor/index.html#sensor-filters

**Comment by PepereLoulou** [comment]
Hello,

I do some test, i have Emporia Vue 2 and Shelly EM... on Shelly EM there is Power Factor sensor:

**Test with oven:**

_Emporia Vue2:_
1800 W

_Shelly EM:_
980 W
Power Factor 57%

Without Power Factor, i think the Emporia datas are wrong.

I can do other tests if need.

**Reply by flaviut** [reply]
I'm surprised that an oven, which is usually a purely restive load, has a power factor that isn't 1.

But regardless, there is no claim that this system can measure true power. It can only measure apparent power, which is also what electric companies generally use to bill their residential customers.

**Reply by PepereLoulou** [reply]
Yes, it's an oven.

In France, and in Europe i think, the electric companies measure only the true power (for residential customers).

**Reply by PepereLoulou** [reply]
I test the oven with the Emporia Vue 2 official firmware, and it done the same datas:

Emporia Vue2 local firmware:
1800 W

Emporia Vue2 official firmware:
1750 W

Shelly EM:
980 W
Power Factor 57%

So the Emporia Vue 2 don't mesure active power but apparent power.

**Reply by henfri** [reply]
In case of an Oven, the power should be purely resistive.
What Current do you measure for both? Can you compare with a Wattmeter?

Honestly, for an Oven, I do not believe a power factor of 57%

**Comment by miwa4711** [comment]
Bought it and installed it, not flashed yet, running integration on HA. Already have a smart meter on the grid input side because of the solar system (Kostal) + another smart meter for the wall box because of excess charging. So I get a general overview of the consumption (active power) in the house + e-car, but not in the individual strands in the house, hence Emporia Vue. Now Emporia Vue shows e. g for my new electric stove in 2 phases a standby of about 70W (should be << 10W). 
I measured the current to the stove with a multimeter (approx. 0.3A), which corresponds to the current display in the Emporia app (current measurement basically ok). The house consumption (active power) on the smart meter only changes by 2-3W if I disconnect the cooker's LS. I trust Kostal's active power measurement, so the only conclusion left is that Emporia Vue does not display active power but apparent power. You already mentioned that above. 
I am on the way to install an air conditioning and a heat pump in my house. Both uses frequency converters to drive its compressors causing reactive power. My goal is to control those loads regarding solar excess which which requires a correct measurement. 
I am from Germany. Here you only pay for active power if you do not exceed a specific ratio which is for most of the house holds.
You did an amazing job running Emporia without the cloud by flashing the controller. Is it possible to change the setup to get active power?

**Reply by henfri** [reply]
Can someone confirm, that Power factor is considered?
Or ist the measurement purely VA and Not W?

I read in the manufacturers Forum a Report, that the big 200A clamps measure W and the Others VA...

**Reply by henfri** [reply]
Anyone?

**Comment by gekkehenkie11** [comment]
Actually this could easily be done if you could just multiply the raw current per CT times the Voltage for that CT. That's your apparent power. Then just devide the raw power (=real power) by that and there's your power factor.

How to access "Raw current" for the smaller CT's  in the YAML file, @flaviut ? I'm sure it should be already possible?

**Reply by gekkehenkie11** [reply]
Actually, already found it: 

- { phase_id: phase_b, input: "1", current: { id: cir17 } }
In the ct_clamps section to get the current for CT1. Then multiply with voltage and that's your VA. Then just divide real by VA. Done.

**Comment by ChestersGarage** [comment]
I have what I believe to be accurate power factor and apparent power.  Looks to me like power is properly calculated to be real power.  If it were apparent power, I wouldn't be able to calculate apparent power and power factor like this.

US power 120/240V split phase (L1/L2/N)

```
.defaultfilters:
  - &200a_ct
    # multiply by 4 to adjust for 200A CT (not needed for 50A CTs)
    multiply: 4.0
  - &throttle_avg
    # average all raw readings together over a 2 second span before publishing
    throttle_average: 2s

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
      # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
      - id: phase_a
        input: BLACK
        calibration: 0.0191
        voltage:
          name: "L1 Voltage"
          id: l1_voltage
          filters: [ *throttle_avg ]
          accuracy_decimals: 1
        frequency:
          name: "Line Frequency"
          id: line_frequency
          filters: [ offset: -0.153, *throttle_avg ]
          accuracy_decimals: 1
      - id: phase_b
        input: RED
        calibration: 0.0191
        voltage:
          name: "L2 Voltage"
          id: l2_voltage
          filters: [ *throttle_avg ]
          accuracy_decimals: 1

    ct_clamps:
      - phase_id: phase_a
        input: "A"
        current:
          id: l1_current
          name: "L1 Current"
          filters: [ *200a_ct, *throttle_avg ]
          accuracy_decimals: 1
        power:
          id: l1_power
          name: "L1 Power"
          filters: [ *throttle_avg ]
          accuracy_decimals: 1

      - phase_id: phase_b
        input: "B"
        current:
          accuracy_decimals: 1
          filters: [ *200a_ct, *throttle_avg ]
          id: l2_current
          name: "L2 Current"
        power:
          accuracy_decimals: 1
          filters: [ *throttle_avg ]
          id: l2_power
          name: "L2 Power"

  - platform: template
    id: l1_apparent_power
    lambda: return id(l1_voltage).state * id(l1_current).state;
    update_interval: never
    device_class: apparent_power
    state_class: measurement
    unit_of_measurement: "VA"
  - platform: template
    id: l2_apparent_power
    lambda: return id(l2_voltage).state * id(l2_current).state;
    update_interval: never
    device_class: apparent_power
    state_class: measurement
    unit_of_measurement: "VA"

  - platform: template
    id: l1_power_factor
    lambda: return id(l1_power).state / id(l1_apparent_power).state;
    update_interval: never
    device_class: power_factor
    state_class: measurement
  - platform: template
    id: l2_power_factor
    lambda: return id(l2_power).state / id(l2_apparent_power).state;
    update_interval: never
    device_class: power_factor
    state_class: measurement

  - platform: copy
    name: "L1 Power Apparent"
    accuracy_decimals: 1
    source_id: l1_apparent_power
    filters: [ *throttle_avg ]
  - platform: copy
    name: "L2 Power Apparent"
    accuracy_decimals: 1
    source_id: l2_apparent_power
    filters: [ *throttle_avg ]

  - platform: copy
    name: "L1 Power Factor"
    accuracy_decimals: 3
    source_id: l1_power_factor
    filters: [ *throttle_avg ]
  - platform: copy
    name: "L2 Power Factor"
    accuracy_decimals: 3
    source_id: l2_power_factor
    filters: [ *throttle_avg ]
```

<img width="517" height="828" alt="Screenshot 2025-07-30 at 10 23 43 PM" src="https://github.com/user-attachments/assets/186846fb-750b-4d9b-97c8-41e60004bb1a" />
