### DISCUSSION TITLE
3 circuits not available in HA Energy Dashboard

### DISCUSSION THREAD

**Discussion by mcarson75** [emporia-vue-local/esphome#22] [Q&A] [answered]
I've got everything working and installed with the below yaml.  I added the device to Home Assistant and all of the sensors are created correctly.  However, when I go to the energy dashboard config to add the circuits as individual devices, three of the circuits are not listed in the dropdown and I cannot add them - `Circuit 1 Daily Energy (AC)`, `Circuit 10 Daily Energy (Master Bath Plugs)`, and `Circuit 11 Daily Energy (Kids Bath Plugs)`.  The other 13 added correctly.  Interestingly, these 3 _are_ available in the `Consumption` dropdown.  What am I missing?  I am especially interested in getting the AC one added....

I have deleted the device and re-added it.  I even deleted the device and edited the HA database to remove all the Emporia sensors before re-adding, and deleted some old unused ones as well (I changed the circuit names at one point).  After doing that it is still these same three circuits that I cannot add.

```
esphome:
  name: emporiavue2

substitutions:
  display_name: Emporia_Vue

external_components:
  - source: github://flaviut/esphome@emporia-vue-2022.4.0
    components: [ emporia_vue ]

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable Home Assistant API
api: {"password": !secret api_pass}
ota: {"password": !secret api_pass}

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  ap:
    ssid: ${display_name}_AP
    password: !secret wifi_pass
    ap_timeout: 3min

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a
time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 2.88 seconds
      window_size: 12
      # we push a new value every 1.44 seconds
      send_every: 6
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg, *pos]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { name:  "Circuit 1 Power (AC)",                id:  cir1, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "2", power: { name:  "Circuit 5 Power (Oven)",              id:  cir2, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "3", power: { name:  "Circuit 9 Power (Garage Plugs)",      id:  cir3, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "4", power: { name: "Circuit 11 Power (Kids Bath Plugs)",   id:  cir4, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "5", power: { name: "Circuit 15 Power (Washer)",            id:  cir5, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "6", power: { name: "Circuit 22 Power (Outside Lights)",    id:  cir6, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "7", power: { name: "Circuit 24 Power (Living Room Plugs)", id:  cir7, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "8", power: { name: "Circuit 26 Power (Office Plugs)",      id:  cir8, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "9", power: { name:  "Circuit 2 Power (Dryer)",             id:  cir9, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input: "10", power: { name:  "Circuit 6 Power (Range)",             id: cir10, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input: "11", power: { name: "Circuit 10 Power (Master Bath Plugs)", id: cir11, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "12", power: { name: "Circuit 12 Power (Kitchen Plugs)",     id: cir12, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "13", power: { name: "Circuit 14 Power (Kitchen Plugs)",     id: cir13, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "14", power: { name: "Circuit 16 Power (Breakfast Plugs)",   id: cir14, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "15", power: { name: "Circuit 18 Power (Upstairs Heat)",     id: cir15, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "16", power: { name: "Circuit 20 Power (Microwave)",         id: cir16, filters: [ *moving_avg, *pos ] } }
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: 1s
    id: total_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 1 Daily Energy (AC)" }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 5 Daily Energy (Oven)" }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 9 Daily Energy (Garage Plugs)" }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 11 Daily Energy (Kids Bath Plugs)" }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 15 Daily Energy (Washer)" }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 22 Daily Energy (Outside Lights)" }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 24 Daily Energy (Living Room Plugs)" }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 26 Daily Energy (Office Plugs)" }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 2 Daily Energy (Dryer)" }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 6 Daily Energy (Range)" }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 10 Daily Energy (Master Bath Plugs)" }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 12 Daily Energy (Kitchen Plugs)" }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 14 Daily Energy (Kitchen Plugs)" }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 16 Daily Energy (Breakfast Plugs)" }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 18 Daily Energy (Upstairs Heat)" }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 20 Daily Energy (Microwave)" }
```
