### DISCUSSION TITLE
Template sensor not updating

### DISCUSSION THREAD

**Discussion by mfisher224** [emporia-vue-local/esphome#220] [Q&A]
I was using the emporia HA integration, but recently flashed with esphome and switched to that. However, my template card that uses data from the vuo has stopped updating. I don't think it knows that the sensor states are changing. It worked before with the emporia HA integration. Any ideas? Here is my template card 

```
 - type: custom:config-template-card
    variables:
      - entity: sensor.emporiavue2_kitchen_refrigerator
        name: Kitchen Refrigerator
      - entity: sensor.emporiavue2_well_pump
        name: Well Pump
      - entity: sensor.emporiavue2_balance_power
        name: Balance Power
      - entity: sensor.emporiavue2_dryer
        name: Dryer
      - entity: sensor.emporiavue2_garage_refrigerator
        name: Garage Refrigerator
      - entity: sensor.emporiavue2_stove
        name: Stove
      - entity: sensor.emporiavue2_microwave
        name: Microwave
      - entity: sensor.emporiavue2_wine_refrigerator
        name: Wine Fridge
      - entity: sensor.attic_fan_current_consumption
        name: Attic Fan
      - entity: sensor.humidifier_current_consumption
        name: Humidifier
      - entity: sensor.draw_collar_current_consumption
        name: Draw Collar
      - entity: sensor.air_purifier_current_consumption
        name: Air Purifier
      - entity: sensor.emporiavue2_furnace
        name: Furnace
      - entity: sensor.ac_first_floor_combined_1min
        name: 1st Flr AC
      - entity: sensor.ac_second_floor_combined_1min_2
        name: 2nd Flr AC
      - entity: sensor.emporiavue2_washing_machine
        name: Washing Machine
      - entity: sensor.emporiavue2_dishwasher
        name: Dishwasher
    entities: >-
      -sensor.ac_first_floor_combined_1min
      -sensor.ac_second_floor_combined_1min_2 -sensor.emporiavue2_microwave
      -sensor.emporiavue2_garage_refrigerator -sensor.emporiavue2_dryer
      -sensor.emporiavue2_stove -sensor.emporiavue2_kitchen_refrigerator
      -sensor.emporiavue2_furnace -sensor.emporiavue2_wine_refrigerator
      -sensor.emporiavue2_well_pump -sensor.emporiavue2_dishwasher
      -sensor.emporiavue2_washing_machine -sensor.attic_fan_current_consumption
      -sensor.humidifier_current_consumption
      -sensor.draw_collar_current_consumption
      -sensor.air_purifier_current_consumption -sensor.emporiavue2_balance_power
    element:
      type: custom:bar-card
      entities: >-
        ${vars.filter(v => states[v.entity].state > 5).sort((v1,v2) =>
        states[v2.entity].state-states[v1.entity].state)}
      direction: right
      entity_row: true
      min: 0
      max: 1000
      height: 25px
      stack: vertical
      decimal: 0
      icon: mdi:flash
      positions:
        icon: 'off'
        indicator: outside
        name: inside
        value: inside
      severity:
        - color: '#a1a1a18a'
          from: 0
          to: 2
        - color: '#3ea8328a'
          from: 2
          to: 10
        - color: '#85a8328a'
          from: 10
          to: 50
        - color: '#a8a4328a'
          from: 50
          to: 200
        - color: '#a887328a'
          from: 200
          to: 500
        - color: '#a867328a'
          from: 500
          to: 1000
        - color: '#a846328a'
          from: 1000
          to: 3000
        - color: '#a832328a'
          from: 3000
          to: 10000
      style: "#states > * {\n  margin: 1px;\n}\nbar-card-name,\nbar-card-value {\n  font-size: 0.9rem;\n  color: #ffffffaa;\n  font-weight: bold;\n}\nbar-card-value\t{\n  font-weight: bolder;\n}\nbar-card-indicator {\n  margin-top: 4px;\n  transform: scaleY(-1);\n}\n  ha-card {   \n  box-shadow: none;\n  border: none;\n  border-radius: 0;\n  background: white; \n}"
```
