### DISCUSSION TITLE
Can we allow the current clamp type to be configurable for each input?

### DISCUSSION THREAD

**Discussion by j9brown** [emporia-vue-local/esphome#224] [Ideas]
In my installation, I'm using the A & B ports to monitor individual circuits instead of the mains because the current clamp can't fit around the bus bars in my electrical box.  This works fine but the sensors are bulky.  As it happens, I will have some leftover CT clamps after replacing a defective sensor and it would be nice to use them in the A/B/C ports.

I don't remember what the inside of the Vue looks like but it wouldn't surprise me if the A/B/C ports were electrically identical to the other ports.  If so, then the only thing that would need to be modified is the [conversion constant](https://github.com/emporia-vue-local/esphome/blob/dev/esphome/components/emporia_vue/emporia_vue.cpp#L133) used in the firmware.

Would it be possible to add a property to specify the clamp type for each port?  By default, ports A/B/C and 1-16 could be configured to assume the big and small clamps are being used but a user could overridde this to allow the clamps to be mixed and matched in any configuration.

**Comment by flaviut** [comment]
Here's someone doing pretty much the exact opposite: https://github.com/emporia-vue-local/esphome/discussions/130

You'll need a physical adapter & to to update the multiplier.

**Reply by j9brown** [reply]
Sounds good.  The physical adapter I can manage easily enough.  I can also change the multiplier but I would prefer not to fork the project.  Any chance the configuration changes can be addressed in your project to facilitate such modifications?

**Reply by flaviut** [reply]
Take a look at `cir5` in the example config, and how it has a `multiply` filter applied:

```
      - { phase_id: phase_a, input:  "5", power: { id:  cir5, filters: [ *pos, multiply: 2 ] } }
```

In this case:

```
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          filters: [*pos, multiply: 0.25] # or whatever the correct value is for your application
```

the ABC clamps in the example config are formatted differently, but the data and available filters are exactly the same as the 1-16 clamps.
