### DISCUSSION TITLE
Sample config: Three phase grid, solar and heat pump, single phase battery with backup circuit, net metering

### DISCUSSION THREAD

**Discussion by tzapu** [emporia-vue-local/esphome#226] [Show and tell]
Just in case anyone is in need of some inspiration, I am quite happy with this:
```
esphome:
  name: power-meter
  friendly_name: Power Meter

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components:
      - emporia_vue

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

ota:
  # Create a secure password for pushing OTA updates.
  password: !secret esphome_secret

# Enable logging
logger:
  logs:
    # by default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO

wifi:
  # Wifi credentials are stored securely by new device wizard.
  ssid: !secret wifi_ssid
  password: !secret wifi_password

preferences:
  # the default of 1min is far too short--flash chip is rated
  # for approx 100k writes.
  flash_write_interval: "48h"

output:
  - platform: ledc
    pin: GPIO12
    id: buzzer
  - platform: gpio
    pin: GPIO27
    id: buzzer_gnd

rtttl:
  output: buzzer
  on_finished_playback:
    - logger.log: 'Song ended!'

button:
  - platform: template
    name: "Two Beeps"
    on_press:
      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

light:
  - platform: status_led
    name: "D3_LED"
    pin: 23
    restore_mode: ALWAYS_ON
    entity_category: config

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a

time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &neg
    # filter out any values above 0.
    lambda: 'return min(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'
  - &inv
    # invert and filter out any values below 0.
    lambda: 'return -x;'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.02276283  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.0223445351  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
      - id: phase_c  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLUE  # Vue device wire color
        calibration: 0.0219016992  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase C Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase C Phase Angle"
          filters: [*throttle_avg, *pos]          
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_power
          # filters: [*pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          # filters: [*pos]
      - phase_id: phase_c
        input: "C"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_c_power
          # filters: [*pos]        
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { id:  cir1, filters: [ *pos ] } }
      - { phase_id: phase_c, input:  "2", power: { id:  cir2, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "3", power: { id:  cir3, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "4", power: { id:  cir4, filters: [ *pos ] } }
      - { phase_id: phase_c, input:  "5", power: { id:  cir5, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "6", power: { id:  cir6, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "7", power: { id:  cir7, filters: [ *pos ] } }
      - { phase_id: phase_c, input:  "8", power: { id:  cir8, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "9", power: { id:  cir9 } }
      - { phase_id: phase_b, input: "10", power: { id: cir10 } }
      - { phase_id: phase_c, input: "11", power: { id: cir11 } }
      - { phase_id: phase_a, input: "12", power: { id: cir12 } }
      - { phase_id: phase_a, input: "13", power: { id: cir13 } }
      - { phase_id: phase_a, input: "14", power: { id: cir14, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "15", power: { id: cir15, filters: [ *pos ] } }
      # - { phase_id: phase_a, input: "16", power: { id: cir16, filters: [ *pos ] } }
    on_update:
      then:
        - component.update: total_power
        - component.update: total_solar_power
        - component.update: total_import_power
        - component.update: total_export_power
        - component.update: total_heat_pump_power
        - component.update: total_kitchen_range_power
        - component.update: load_phase_a_power
        - component.update: load_phase_b_power
        - component.update: load_phase_c_power
        - component.update: load_power

  # - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *throttle_avg }
  # - { platform: copy, name: "Circuit 16 Power", source_id: cir16, filters: *throttle_avg }
    
  # Main circuits
  - platform: template
    lambda: !lambda |-
      return id(phase_a_power).state + 
        id(phase_b_power).state +
        id(phase_c_power).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power # active_power?
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: template
    lambda: return max(id(total_power).state, 0.0f);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_import_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: template
    lambda: return min(id(total_power).state, 0.0f);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_export_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: template
    lambda: return id(phase_a_power).state + id(cir9).state + -id(cir12).state + id(cir13).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: load_phase_a_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: template
    lambda: return id(phase_b_power).state + id(cir10).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: load_phase_b_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: template
    lambda: return id(phase_c_power).state + id(cir11).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: load_phase_c_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: template
    lambda: !lambda |-
      return id(load_phase_a_power).state +
        id(load_phase_b_power).state +
        id(load_phase_c_power).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: load_power # active_power?
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Daily Imported Energy"
    power_id: total_import_power
    restore: false
    method: left
    accuracy_decimals: 0
    filters: [*throttle_time]
  - platform: total_daily_energy
    name: "Daily Exported Energy"
    power_id: total_export_power
    restore: false
    method: left
    accuracy_decimals: 0
    filters: [*invert, *throttle_time]
  - platform: total_daily_energy
    name: "Daily Load Energy"
    power_id: load_power
    restore: false
    method: left
    accuracy_decimals: 0
    filters: [*throttle_time]

  - { platform: copy, name: "Grid Phase A Power", source_id: phase_a_power, filters: *throttle_avg }
  - { platform: copy, name: "Grid Phase B Power", source_id: phase_b_power, filters: *throttle_avg }
  - { platform: copy, name: "Grid Phase C Power", source_id: phase_c_power, filters: *throttle_avg }
  - { platform: copy, name: "Grid Power", source_id: total_power, filters: *throttle_avg }

  - { platform: copy, name: "Load Phase A Power", source_id: load_phase_a_power, filters: *throttle_avg }
  - { platform: copy, name: "Load Phase B Power", source_id: load_phase_b_power, filters: *throttle_avg }
  - { platform: copy, name: "Load Phase C Power", source_id: load_phase_c_power, filters: *throttle_avg }
  - { platform: copy, name: "Load Power", source_id: load_power, filters: *throttle_avg }

  # 1 - Lighting circuits  
  - { platform: copy, name: "Lighting Power", source_id:  cir1, filters: *throttle_avg }

  - platform: total_daily_energy
    name: "Daily Lighting Energy"
    power_id: cir1
    restore: false
    method: left
    accuracy_decimals: 0
    filters: [*throttle_time]

  # 2 - Livingroom circuit
  - { platform: copy, name: "Livingroom Power", source_id:  cir2, filters: *throttle_avg }

  - platform: total_daily_energy
    name: "Livingroom Daily Energy"
    power_id: cir2
    restore: false
    method: left
    accuracy_decimals: 0
    filters: [*throttle_time]

  # 3 4 5 - Kitchen range
  - platform: template
    lambda: !lambda |-
      return id(cir3).state + 
        id(cir4).state +
        id(cir5).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_kitchen_range_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  - { platform: copy, name: "Kitchen Range Power", source_id: total_kitchen_range_power, filters: *throttle_avg }

  - platform: total_daily_energy
    name: "Daily Kitchen Range Energy"
    power_id: total_kitchen_range_power
    restore: false
    method: left
    accuracy_decimals: 0
    filters: [*throttle_time]

  # 6 7 8 - Heat pump
  - platform: template
    lambda: !lambda |-
      return id(cir6).state + 
        id(cir7).state +
        id(cir8).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_heat_pump_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  - { platform: copy, name: "Heat Pump Power", source_id: total_heat_pump_power, filters: *throttle_avg }

  - platform: total_daily_energy
    name: "Daily Heat Pump Energy"
    power_id: total_heat_pump_power
    restore: false
    method: left
    accuracy_decimals: 0
    filters: [*throttle_time]


  # 9 10 11 - Solar
  - platform: template
    lambda: !lambda |-
      return id(cir9).state + 
        id(cir10).state +
        id(cir11).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_solar_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Daily Solar Energy"
    power_id: total_solar_power
    restore: false
    method: left
    accuracy_decimals: 1
    filters: [*throttle_time]

  - { platform: copy, name: "Solar Phase A Power", source_id: cir9, filters: [*throttle_avg] }
  - { platform: copy, name: "Solar Phase B Power", source_id: cir10, filters: [*throttle_avg] }
  - { platform: copy, name: "Solar Phase C Power", source_id: cir11, filters: [*throttle_avg] }
  - { platform: copy, name: "Solar Power", source_id: total_solar_power, filters: *throttle_avg }

  # 12 - Battery Inverter AC In
  - { platform: copy, name: "ESS Power", source_id: cir12, filters: *throttle_avg }

  # 13 - Battery Inverter AC Out
  - { platform: copy, name: "EPS Power", source_id: cir13, filters: *throttle_avg }

  # 14
  - { platform: copy, name: "Kitchen Power", source_id: cir14, filters: *throttle_avg }

  # - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, name: "Kitchen Daily Energy", filters: *throttle_time }
  - platform: total_daily_energy
    name: "Kitchen Daily Energy"
    power_id: cir14
    restore: false
    method: left
    accuracy_decimals: 0
    filters: [*throttle_time]

  # 15
  - { platform: copy, name: "Bedroom 1 Power", source_id: cir15, filters: *throttle_avg }
 
  # - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, name: "Bedroom 1 Daily Energy", filters: *throttle_time }
  - platform: total_daily_energy
    name: "Bedroom 1 Daily Energy"
    power_id: cir15
    restore: false
    method: left
    accuracy_decimals: 0
    filters: [*throttle_time]

  # 16 - Broken CT sensor
```

Thank you for this amazing project
