### DISCUSSION TITLE
Return to grid

### DISCUSSION THREAD

**Discussion by davidadanieljr** [emporia-vue-local/esphome#23] [Q&A] [answered]
Apologies if this is obvious but I am fairly new to ESPHome so just want to make sure my understanding is correct.  I currently have a grid tied solar system and would like to be able to calculate the return to grid values.  Within the yaml configuration files for the Emporia the filter *pos is applied to both phases which removes any negative values.  Am I correct in thinking that removing that filter will allow me to get the return to grid values or am I oversimplifying it? 
I'm then taking the absolute value of those negatives and adding them to the HA Energy Dashboard as the Return to Grid.  

Again, apologies if this is obvious to some but I've spent several days trying to math this out and to find out it only took me removing a filter within the config feels overly simple

**Comment by flaviut** [comment, marked as answer]
> Within the yaml configuration files for the Emporia the filter *pos is applied to both phases which removes any negative values. Am I correct in thinking that removing that filter will allow me to get the return to grid values or am I oversimplifying it?

You are correct. I'm not sure if I'm missing some requirement you have, but you don't need to take the absolute value: negative values will be returned to grid, positive values will be received from grid.

> Again, apologies if this is obvious to some but I've spent several days trying to math this out and to find out it only took me removing a filter within the config feels overly simple

It happens. I've spent weeks on simple one-line issues before :)

**Reply by davidadanieljr** [reply]
Thanks for the graceful and quick reply. You are correct the abs value is not necessary it's mainly just for aesthetics, by creating separate values for to and from the grid they are listed separately in the graph. Based on the few hours of data I have the results appear to be the same for either approach.

**Reply by balsman225** [reply]
I stumbled on your post and it was very helpful in getting my sensor to show a negative reading when my solar is over producing and I’m returning to grid. But since it seems home assistant needs a dedicated return to grid sensor did you just create a separate template to read the negative total power and create its own sensor? I’m not very versed in templates so was curious how you were handling this.  Thanks!

**Reply by clowrey** [reply]
Yeah it's possible with template.. the help page on ESPhome.io should have all you need.

**Reply by davidadanieljr** [reply]
> I stumbled on your post and it was very helpful in getting my sensor to show a negative reading when my solar is over producing and I’m returning to grid. But since it seems home assistant needs a dedicated return to grid sensor did you just create a separate template to read the negative total power and create its own sensor? I’m not very versed in templates so was curious how you were handling this. Thanks!

Yes I created two template sensors : 

```
      power_to_grid:
        friendly_name: 'Power to Grid'
        unit_of_measurement: W
        device_class: power
        value_template: >-
          {% if states('sensor.total_power')|int < 0 %}
            {{ states('sensor.total_power') | int(0) | abs }}
          {% else %}
            0
          {% endif %}
          
      power_from_grid:
        friendly_name: 'Power from Grid'
        unit_of_measurement: W
        device_class: power
        value_template: >-
          {% if states('sensor.total_power')|int > 0 %}
            {{ states('sensor.total_power') | int(0) | abs }}
          {% else %}
            0
          {% endif %}
```
 Edited: Removed reference to a third sensor I created.  It was not needed for this scenario so I removed it to eliminate any confusion

**Reply by balsman225** [reply]
> > I stumbled on your post and it was very helpful in getting my sensor to show a negative reading when my solar is over producing and I’m returning to grid. But since it seems home assistant needs a dedicated return to grid sensor did you just create a separate template to read the negative total power and create its own sensor? I’m not very versed in templates so was curious how you were handling this. Thanks!
> 
> Yes I created a few template sensors :
> 
> First one to add together to 2 solar legs:
> 
> ```
>   - sensors:
>       total_solar_power:
>          friendly_name: Total Solar Power
>          unit_of_measurement: W
>          device_class: power
>          value_template: >-
>            {{ states('sensor.solar_1_power_a_15b') | int(0) + states('sensor.solar_2_power_b_16b') | int(0) `}}
> ```
> 
> and then two to track the to and from:
> 
> ```
>       power_to_grid:
>         friendly_name: 'Power to Grid'
>         unit_of_measurement: W
>         device_class: power
>         value_template: >-
>           {% if states('sensor.total_power')|int < 0 %}
>             {{ states('sensor.total_power') | int(0) | abs }}
>           {% else %}
>             0
>           {% endif %}
>           
>       power_from_grid:
>         friendly_name: 'Power from Grid'
>         unit_of_measurement: W
>         device_class: power
>         value_template: >-
>           {% if states('sensor.total_power')|int > 0 %}
>             {{ states('sensor.total_power') | int(0) | abs }}
>           {% else %}
>             0
>           {% endif %}
> ```

Thank you very much - I'll give this a shot a see how it works over the next few days. I appreciate your assistance.

**Reply by TommySharpNZ** [reply]
> Thanks for the graceful and quick reply. You are correct the abs value is not necessary it's mainly just for aesthetics, by creating separate values for to and from the grid they are listed separately in the graph. Based on the few hours of data I have the results appear to be the same for either approach.

Would you be able to share you entire Emporia ESPHome config here or somewhere so I can get a better understanding of how your approach fits together?

**Comment by TommySharpNZ** [comment]
Is it not possible to make ESPHome return the additional values so they just "show up" in Home Assistant?

**Reply by flaviut** [reply]
If you're asking about the YAML config above, that's ESPHome config, not HomeAssistant config. They do just "show up" in HA.

**Reply by TommySharpNZ** [reply]
Okay thanks.. It can get a bit confusing because they all look very similar now...

**Comment by balsman225** [comment]
Here is my current esphome yaml config in case its useful for reference. There may be better ways to achieve these sensors but  seems to be working for me so far.


```
  substitutions:
  device_name: Home Energy Monitor
  friendly_name: Home Energy Monitor # Displayed in HA frontend
  device_description: Emporia Vue 2 16 Clamp Energy Monitor

  circuit_1: "Upstairs Furnace"
  circuit_2: "Upstairs AC"
  circuit_3: "Clothes Dryer"
  circuit_4: "Dishwasher / G. Disposal"
  circuit_5: "Main AC & Heatpump"
  circuit_6: "Tesla Charger"
  circuit_7: "Server Rack"
  circuit_8: "Water Softner"
  circuit_9: "Shop Sub Panel"
  circuit_10: "Septic Areator"
  circuit_11: "Microwave"
  circuit_12: "HVAC Fan"
  circuit_13: "Stove"
  circuit_14: "Clothes Washer"
  circuit_15: "Fridge"
  circuit_16: "Septic Pump"


esphome:
  name: home-energy-monitor
  comment: ${device_description}

external_components:
  - source: github://flaviut/esphome@emporia-vue-2022.4.0
    components: [ emporia_vue ]

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Emporia Vue Fallback Hotspot"
    password: !secret esphome_fallback_ap_pass

api:
  password: !secret esphome_api

ota:
  password: !secret esphome_ota


i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a
time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 2.88 seconds
      window_size: 12
      # we push a new value every 1.44 seconds
      send_every: 6
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.02283201  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.021119637  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]

    ct_clamps:

# Phases with Return to Grid - No Filter
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg]

      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg]

# Phases with no Return to Grid - Filter out Negitive
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power - Positive"
          id: phase_a_power_positive
          device_class: power
          filters: [*moving_avg, *pos]

      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power - Positive"
          id: phase_b_power_positive
          device_class: power
          filters: [*moving_avg, *pos]

      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_b, input:  "1", power: { name:  "${circuit_1} Power", id:  cir1, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "2", power: { name:  "${circuit_2} Power", id:  cir2, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "3", power: { name:  "${circuit_3} Power", id:  cir3, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "4", power: { name:  "${circuit_4} Power", id:  cir4, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "5", power: { name:  "${circuit_5} Power", id:  cir5, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "6", power: { name:  "${circuit_6} Power", id:  cir6, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "7", power: { name:  "${circuit_7} Power", id:  cir7, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "8", power: { name:  "${circuit_8} Power", id:  cir8, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "9", power: { name:  "${circuit_9} Power", id:  cir9, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input: "10", power: { name: "${circuit_10} Power", id: cir10, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "11", power: { name: "${circuit_11} Power", id: cir11, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input: "12", power: { name: "${circuit_12} Power", id: cir12, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "13", power: { name: "${circuit_13} Power", id: cir13, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input: "14", power: { name: "${circuit_14} Power", id: cir14, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "15", power: { name: "${circuit_15} Power", id: cir15, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "16", power: { name: "${circuit_16} Power", id: cir16, filters: [ *moving_avg, *pos ] } }

# Power with Return to Grid - No Filter
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: 1s
    id: total_power
    unit_of_measurement: "W"

# Power with no Return to Grid - Filter out Negitive
  - platform: template
    name: "Total Power without Return"
    lambda: return id(phase_a_power_positive).state + id(phase_b_power_positive).state;
    update_interval: 1s
    id: total_power_positive
    unit_of_measurement: "W"

# Total House Watts Positive Reading
  - platform: template
    name: Total Power from Grid
    id: total_power_from_grid
    lambda: |-
      if (id(total_power_positive).state < 0) {
        return 0;
      } else {
        return id(total_power_positive).state ;
      }
    accuracy_decimals: 1
    unit_of_measurement: "W"
    device_class: power
    update_interval: 1s


 # Total House Watts Negitive Reading   
  - platform: template
    name: "Total Power to Grid"
    id: total_power_to_grid
    lambda: |-
      if (id(total_power).state > 0) {
        return 0;
      } else {
        return abs(id(total_power).state) ;
      }
    accuracy_decimals: 1
    unit_of_measurement: "W"
    device_class: power
    update_interval: 1s

# House Positive kWh
  - platform: total_daily_energy
    name: "Total Daily Energy from Grid"
    power_id: total_power_from_grid
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing

# House Negitive kWh
  - platform: total_daily_energy
    name: "Total Daily Energy to Grid"
    power_id: total_power_to_grid
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing


  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0

  - platform: total_daily_energy
    name: "Total Daily Energy - No Return"
    power_id: total_power_positive
    accuracy_decimals: 0
  
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_1} Daily Energy" }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_2} Daily Energy" }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_3} Daily Energy" }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_4} Daily Energy" }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_5} Daily Energy" }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_6} Daily Energy" }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_7} Daily Energy" }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_8} Daily Energy" }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_9} Daily Energy" }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_10} Daily Energy" }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_11} Daily Energy" }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_12} Daily Energy" }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_13} Daily Energy" }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_14} Daily Energy" }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_15} Daily Energy" }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, name: "${circuit_16} Daily Energy" }
```
