### DISCUSSION TITLE
Total Daily Energy Reset

### DISCUSSION THREAD

**Discussion by n00bhaxor** [emporia-vue-local/esphome#240] [Q&A]
Home Assistant noob here. This project is pretty damned amazing, and actually what made me want to give Home Assistant a go. Kudos to everyone who has put so much time and effort into REing the Emporia Vue2!

I've searched high and low for an answer, and have seen the discussions here for the total_daily_energy not resetting, but that's not quite the problem I'm having. This is just driving me crazy. I'm sure it's something stupid that I'm overlooking.

**Problem:** Daily reset of total energy usage happens around 30-45 seconds after midnight, so when I try to set up a Statistics Graph card for hourly or daily energy consumption, there's a spike in usage at midnight, and I've already got energy used for the current day. Not sure if the problem is my templates, my ESPHome config, or my graph, but I'm certain it's user error. I've got 2 panels, so a Vue2 in each panel, and a template sensor to add the 2 values together to get the daily usage. I'm using the stock config with just a couple of tweaks for sensor naming.

Here's the platform config in ESPHome for one of my Vue2s. I have a similar one in my other panel:

```
- platform: total_daily_energy
    name: "Left Panel Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
    filters: *throttle_time
```
And the sensor config that adds the 2 total_daily_energy values together:

```
- sensor:
        name: "Total Energy Consumed"
        unique_id: total_energy_consumed
        icon: mdi:electricity
        device_class: energy
        state_class: total_increasing
        unit_of_measurement: 'kWh'
        state: >
          {{ ( states('sensor.vue2_left_left_panel_total_daily_energy') | float(0) / 1000 ) + ( states('sensor.vue2_right_right_panel_total_daily_energy') | float(0) / 1000 ) }}
```

And here's a screenshot of what the statistics graph looks like. Ignore the ridiculously high values on the left. I'm still trying to figure things out. The important piece is at midnight on November 24th, there's a huge spike in the graph, and I can't for the life of me figure out why.

![hourly_power_usage](https://github.com/emporia-vue-local/esphome/assets/43417886/5f2426c5-c5b8-43b8-a9e0-996ec603efdf)

And a screenshot showing when the total daily energy gets reset. The time scale is 12:00am-12:10 am. First screenshot is from one of the panels, and the second one is from the total_energy_consumed sensor that adds the 2 panels together together.

![left_panel_reset](https://github.com/emporia-vue-local/esphome/assets/43417886/3d7ceb6a-569c-438f-844e-4897fa0ad697)

![total_energy_reset](https://github.com/emporia-vue-local/esphome/assets/43417886/613e4c55-6940-4708-9ddd-579fc14a0330)

WTH am I missing? Is it an issue with my ESPHome config, my total_energy_consumed sensor config, or my Statistics Graph?

** Edit to say that I've verified my time source and that it's syncing properly **
