### DISCUSSION TITLE
Voltage calibration via service

### DISCUSSION THREAD

**Discussion by blalor** [emporia-vue-local/esphome#260] [Show and tell]
I think this might be useful for other people. I figured out how to use a `number` and a service to calibrate the voltage for a phase using a known voltage (measured with a multimeter at the bus bars).  I find it faster and more convenient than calculating the calibration values manually and then re-flashing the device.  It does require changing the `preferences.flash_write_interval` value to something less long (I chose 30m, but I don't think there's a benefit in leaving it at 48h because the `total_daily_energy` instances have `restore: false`).  

With this config in place, in Home Assistant I go to Developer Tools → Services and call the appropriate service (one per phase):

```yaml
service: esphome.emporia_vue2_house_calibrate_phase_b
data:
  real_voltage: 121.2
```

That will recalculate the calibration value, and it will be restored from flash on boot.

Key changes to the config from this repo's `README.md` are:

```yaml
esphome:
  # …

  on_boot:
    then:
      # restore phase calibration from flash
      - lambda: |-
          id(phase_a).set_calibration(id(phase_a_calibration).state);
          id(phase_b).set_calibration(id(phase_b_calibration).state);

preferences:
  flash_write_interval: "30min"

api:
  # …
  services:
    # …

        ## calibrate phase A from measured voltage
        - service: calibrate_phase_a
          variables:
            real_voltage: float
          then:
            # <in-use calibration value> * <accurate voltage> / <reporting voltage>
            - number.set:
                id: phase_a_calibration
                value: !lambda |-
                  return id(phase_a).get_calibration() * real_voltage / id(phase_a_voltage).state;

        ## calibrate phase B from measured voltage
        - service: calibrate_phase_b
          variables:
            real_voltage: float
          then:
            # <in-use calibration value> * <accurate voltage> / <reporting voltage>
            - number.set:
                id: phase_b_calibration
                value: !lambda |-
                  return id(phase_b).get_calibration() * real_voltage / id(phase_b_voltage).state;

number:
  - platform: template
    id: phase_a_calibration
    
    min_value: 0.01
    max_value: 0.03
    step: 0.000000000000000001
    restore_value: true
    initial_value: 0.022
    
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(phase_a).set_calibration(x);

  - platform: template
    id: phase_b_calibration
    
    min_value: 0.01
    max_value: 0.03
    step: 0.000000000000000001
    restore_value: true
    initial_value: 0.022
    
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(phase_b).set_calibration(x);
```

<details>

<summary>full config based on example in <code>README.md<code></summary>

```yaml
esphome:
  name: emporiavue2
  friendly_name: vue2

  on_boot:
    then:
      # restore phase calibration from flash
      - lambda: |-
          id(phase_a).set_calibration(id(phase_a_calibration).state);
          id(phase_b).set_calibration(id(phase_b_calibration).state);

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components:
      - emporia_vue

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable Home Assistant API
api:
  encryption:
    # Encryption key is generated by the new device wizard.
    key: "<generated_key_from_new_device_wizard>"

  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

        ## calibrate phase A from measured voltage
        - service: calibrate_phase_a
          variables:
            real_voltage: float
          then:
            # <in-use calibration value> * <accurate voltage> / <reporting voltage>
            - number.set:
                id: phase_a_calibration
                value: !lambda |-
                  return id(phase_a).get_calibration() * real_voltage / id(phase_a_voltage).state;

        ## calibrate phase B from measured voltage
        - service: calibrate_phase_b
          variables:
            real_voltage: float
          then:
            # <in-use calibration value> * <accurate voltage> / <reporting voltage>
            - number.set:
                id: phase_b_calibration
                value: !lambda |-
                  return id(phase_b).get_calibration() * real_voltage / id(phase_b_voltage).state;

ota:
  # Create a secure password for pushing OTA updates.
  password: "<secure_password>"

# Enable logging
logger:
  logs:
    # by default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO

wifi:
  # Wifi credentials are stored securely by new device wizard.
  ssid: !secret wifi_ssid
  password: !secret wifi_password

preferences:
  # please also make sure `restore: false` is set on all `platform: total_daily_energy`
  # sensors below.
  flash_write_interval: "30min"

output:
  - platform: ledc
    pin: GPIO12
    id: buzzer
  - platform: gpio
    pin: GPIO27
    id: buzzer_gnd

rtttl:
  output: buzzer
  on_finished_playback:
    - logger.log: 'Song ended!'

button:
  - platform: template
    name: "Two Beeps"
    on_press:
      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

light:
  - platform: status_led
    name: "D3_LED"
    pin: 23
    restore_mode: ALWAYS_ON
    entity_category: config

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a

time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

number:
  - platform: template
    id: phase_a_calibration
    
    min_value: 0.01
    max_value: 0.03
    step: 0.000000000000000001
    restore_value: true
    initial_value: 0.022
    
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(phase_a).set_calibration(x);

  - platform: template
    id: phase_b_calibration
    
    min_value: 0.01
    max_value: 0.03
    step: 0.000000000000000001
    restore_value: true
    initial_value: 0.022
    
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(phase_b).set_calibration(x);

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # Copy sensors will filter and then send power measurements to HA
      # These non-throttled power sensors are used for accurately calculating energy
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_power
          filters: [*pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          filters: [*pos]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { id:  cir1, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "2", power: { id:  cir2, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "3", power: { id:  cir3, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "4", power: { id:  cir4, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "5", power: { id:  cir5, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "6", power: { id:  cir6, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "7", power: { id:  cir7, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "8", power: { id:  cir8, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "9", power: { id:  cir9, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "10", power: { id: cir10, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "11", power: { id: cir11, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input: "12", power: { id: cir12, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input: "13", power: { id: cir13, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "14", power: { id: cir14, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "15", power: { id: cir15, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "16", power: { id: cir16, filters: [ *pos ] } }
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power
  # The copy sensors filter and send the power state to HA
  - { platform: copy, name: "Phase A Power", source_id: phase_a_power, filters: *throttle_avg }
  - { platform: copy, name: "Phase B Power", source_id: phase_b_power, filters: *throttle_avg }
  - { platform: copy, name: "Total Power", source_id: total_power, filters: *throttle_avg }
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 1 Power", source_id:  cir1, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 2 Power", source_id:  cir2, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 3 Power", source_id:  cir3, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 4 Power", source_id:  cir4, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 5 Power", source_id:  cir5, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 6 Power", source_id:  cir6, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 7 Power", source_id:  cir7, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 8 Power", source_id:  cir8, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 9 Power", source_id:  cir9, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 10 Power", source_id: cir10, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 11 Power", source_id: cir11, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 12 Power", source_id: cir12, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 13 Power", source_id: cir13, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 14 Power", source_id: cir14, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 15 Power", source_id: cir15, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 16 Power", source_id: cir16, filters: *throttle_avg }
  - platform: template
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - platform: template
    lambda: !lambda |-
      return max(0.0f, id(total_power).state -
        id( cir1).state -
        id( cir2).state -
        id( cir3).state -
        id( cir4).state -
        id( cir5).state -
        id( cir6).state -
        id( cir7).state -
        id( cir8).state -
        id( cir9).state -
        id(cir10).state -
        id(cir11).state -
        id(cir12).state -
        id(cir13).state -
        id(cir14).state -
        id(cir15).state -
        id(cir16).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: balance_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Balance Daily Energy"
    power_id: balance_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 1 Daily Energy", filters: *throttle_time }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 2 Daily Energy", filters: *throttle_time }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 3 Daily Energy", filters: *throttle_time }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 4 Daily Energy", filters: *throttle_time }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 5 Daily Energy", filters: *throttle_time }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 6 Daily Energy", filters: *throttle_time }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 7 Daily Energy", filters: *throttle_time }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 8 Daily Energy", filters: *throttle_time }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 9 Daily Energy", filters: *throttle_time }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 10 Daily Energy", filters: *throttle_time }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 11 Daily Energy", filters: *throttle_time }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 12 Daily Energy", filters: *throttle_time }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 13 Daily Energy", filters: *throttle_time }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 14 Daily Energy", filters: *throttle_time }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 15 Daily Energy", filters: *throttle_time }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 16 Daily Energy", filters: *throttle_time }
```

</details>

**Comment by stherien** [comment]
First thanks for sharing the code to ease voltage calibration via a service.

Quick questions:

How often do you have to recalibrate the voltage for each phase?

Did you automate the call to the calibration service? For example, when there is a certain delta between the accurate voltage and the reporting voltage.

Last, just to mention that I had to define "id: phase_a_voltage" and "id: phase_b_voltage: under each phase "voltage:" definition for the code to compile correctly.

**Reply by blalor** [reply]
I only calibrate on initial setup of the device. I haven’t checked to compare it to anything else; it hadn’t occurred to me, and I’d need to open the panel to expose the bus bars. So for me doing it manually via the HA developer tools page was sufficient.

**Comment by eebrains** [comment]
I'm confused as to what is the advantage over hard-coding the cal values?
For voltage just follow the formula  in the comment `<in-use calibration value> * <accurate voltage> / <reporting voltage> `
```yaml
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.023103773
        # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*fast_avg ]
        frequency:
          disabled_by_default: true
          name: "Phase A Frequency"
          filters: [*moving_avg ]
    ...
```

For power I used a linear model based on a very accurate power meter I have, and for current I didn't really care about accuracy.  Unsure about the underlying mechanics - I played it safe and did voltage first, then power after.  If doing current, I'd have done that 2nd.  Implemented using the multiply and offset filters in the sensor definitions like below:
```yaml
    < SNIP >
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { name: "Circuit 01 Power", disabled_by_default: true, id:  cir1, filters: [ *moving_avg, multiply: 0.996185684142185, offset: 1.66162960558336, *pos ] }
                                      , current: { name: "Cicruit 01 Current", disabled_by_default: true, id: cur1, filters: [*fast_avg ] } }
      - { phase_id: phase_a, input:  "2", power: { name: "Circuit 02 Power", disabled_by_default: true, id:  cir2, filters: [ *moving_avg, multiply: 2, multiply: 0.989759716174811, offset: 1.49379938719562, *pos ] }
                                      , current: { name: "Cicruit 02 Current", disabled_by_default: true, id: cur2, filters: [*fast_avg ] } }
    < SNIP >

```
