### DISCUSSION TITLE
D3_LED without function

### DISCUSSION THREAD

**Discussion by ThomDietrich** [emporia-vue-local/esphome#265] [Q&A]
Hey there,
this might be a simple question or I might be mistaken all together. This is related to D3_LED:

```yaml
light:
  - platform: status_led
    name: "D3_LED"
    pin: 23
    restore_mode: ALWAYS_ON
    entity_category: config
```

This entity does not seem to have any effect. Toggling the switch does not turn an LED on/off. Is it just me or is this an error with e.g. an updated PCB? Cheers!
