### DISCUSSION TITLE
Explanation of YAML sample file

### DISCUSSION THREAD

**Discussion by MatejKovacic** [emporia-vue-local/esphome#276] [Q&A]
Hi,
I have bought Emporia Vue 2 and went through your guide to flash it. It went well, however I have three questions.

**First**. Do I understand correctly, that I have to identify which phase (I have three phases) connect to which circuit breaker and I should put that to YAML. So YAML example:
```
- { phase_id: phase_b, input: "2", power: { id: cir2, filters: [ *pos ] } }
- { phase_id: phase_a, input: "3", power: { id: cir3, filters: [ *pos ] } }
```

Means:
- sensor No. 2 is connected to phase B
- sensor No. 3 is connected to phase A

Is that correct?

Second. YAML example is describing just two phases - phase_a and phase_b. However, I have three phases. In example YAML only BLACK and RED Vue device wire color are used, but I also have BLUE (and WHITE connects to neutral). Vue documentation says that Black provides power and voltage sensing, while and Blue and Red enable voltage sensing only. Should I add also `phase_c` to the YAML? What would be the entry?
```
      - id: phase_c
        input: BLUE 
```
would be OK?

And **third**. In example YAML file I can see entries like:
```
- { phase_id: phase_a, input: "4", power: { id: cir4, filters: [ *pos ] } }
- { phase_id: phase_a, input: "5", power: { id: cir5, filters: [ *pos, multiply: 2 ] } }

```
What is the meaning of `[ *pos ]` and `[ *pos, multiply: 2 ]`?

I have "normal" pole breakers (sorry, I am not electrician), B 16 and B 10 (I am from Europe), however, there is one bigger - triple actually - C 16 - for oven and hob (induction). So I guess, I should leave filters set to `[ *pos ] ` for all, except for this bigger one pole breaker, where it should be `[ *pos, multiply: 3 ]`? Or I am getting this completely wrong?

Thanks for any help.

**Comment by flaviut** [comment]
You're pretty much right about everything here.

> First. Do I understand correctly, that I have to identify which phase (I have three phases) connect to which circuit breaker and I should put that to YAML.

yup

> Vue documentation says that Black provides power and voltage sensing, while and Blue and Red enable voltage sensing only. Should I add also phase_c to the YAML? What would be the entry?

your config is right, but you may want to include the `voltage` & `phase_angle:` entries if you need that data. Not required though, and to be honest I don't think I've ever looked at it.

> So I guess, I should leave filters set to [ *pos ] for all, except for this bigger one pole breaker, where it should be [ *pos, multiply: 3 ]?

Your approach is good, but [see "Step 9 (continued): A note about multi-pole breakers" in the manual](https://www.emporiaenergy.com/wp-content/uploads/2024/01/81681238-cd2e-472a-9f53-6d4146079cef.pdf). Depending on how your appliances work and whether they are an unbalanced load, you may need to use 3 clamps for best accuracy.

`*pos` is explained in the example config, around `.defaultfilters:`, and [`multiply: 2` is explained in the esphome docs](https://esphome.io/components/sensor/index.html#multiply) and does exactly what you expect.

**Comment by MatejKovacic** [comment]
Thank you very much for your answer. Actually, I have one three-pole breaker and I think that electrician installed three clamps on it. So I guess in my case I should not use any multiplier at all.


Sorry, I don't understand this:
#your config is right, but you may want to include the voltage & phase_angle: entries if you need that data. Not required though, and to be honest I don't think I've ever looked at it.

And I still don't fully understand how to include the third phase. Should my config look like this:  

```
phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        ...
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        ...
      # SHOULD I ADD THIS?
      - id: phase_c  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLUE  # Vue device wire color
        ...
```
