### DISCUSSION TITLE
Wh vs W in Home Assistant

### DISCUSSION THREAD

**Discussion by FedgarLurch** [emporia-vue-local/esphome#280] [Q&A] [answered]
I have this weird quirk (although maybe its not a quirk and I am just off base)
When I add my sensors via the ESPhome integration, the individual circuits come in as W as they should. 
Over time, (not certain how long) they convert themselves to Wh and it really throws off my monitoring. 

Here is my code below:

I have two of them because I have about 28 circuits, I have the main on one of them, then about 8 circuits leftover on another one. 
I am only including one of the configurations because they are functionally identical, and I don't want this to be crazy long. 

```
esphome:
  name: $explicit_devicename
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

substitutions:
  explicit_devicename: emporia-primary
  devicename: emporia-primary
  cir_1_name: 1 - Closet & Bathroom Lights
  cir_2_name: 2 - Kitchen & Dining area Lights
  cir_3_name: 3 - Stove
  cir_4_name: 4 - Stove
  cir_5_name: 5 - Kitchen & Living room Lights
  cir_6_name: 6 - Refridgerator
  cir_7_name: 7 - Guest Bath GFCI
  cir_8_name: 8 - Spare
  cir_9_name: 9 - Spare
  cir_10_name: 10 - Spare
  cir_11_name: 11 - Spare
  cir_12_name: 12 - Spare
  cir_13_name: 13 - Media Plugs
  cir_14_name: 14 - Outside GFCI
  cir_15_name: 15 - Dryer
  cir_16_name: 16 - Dryer

wifi:
  #use_address: 10.10.10.154
  networks:
  - ssid: !secret home_wifi_ssid
    password: !secret home_wifi_password
    manual_ip:
      static_ip: 10.10.10.135
      gateway: 10.10.10.1
      subnet: 255.255.255.0
# Secondary backup network.
  - ssid: !secret rashas_wifi_ssid
    password: !secret rashas_wifi_password
    
# Added to combat instability
# Turn this off if you need to save power. 
  power_save_mode: none

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename Hotspot"
    password: !secret AP_hotspot_password

#Need this if you want to use the fallback hotspot
captive_portal:
  
api:
  encryption:
    key: 

  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

ota:
  password: 


# Enable logging
logger:
  logs:
    # by default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO


# Device Specific Config

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components:
      - emporia_vue


preferences:
  # please also make sure `restore: false` is set on all `platform: total_daily_energy`
  # sensors below.
  flash_write_interval: "48h"

output:
  - platform: ledc
    pin: GPIO12
    id: buzzer
  - platform: gpio
    pin: GPIO27
    id: buzzer_gnd

rtttl:
  output: buzzer
  on_finished_playback:
    - logger.log: 'Song ended!'

button:
  - platform: template
    name: "Two Beeps"
    on_press:
      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

light:
  - platform: status_led
    name: "D3_LED"
    pin: 23
    restore_mode: ALWAYS_ON
    entity_category: config

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a

time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # Copy sensors will filter and then send power measurements to HA
      # These non-throttled power sensors are used for accurately calculating energy
      - phase_id: phase_b
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          filters: [*pos, multiply: 2]
      - phase_id: phase_a
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_power
          filters: [*pos, multiply: 2]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_b, input:  "1", power: { id:  cir1, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "2", power: { id:  cir2, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "3", power: { id:  cir3, filters: [ *pos, multiply: .5 ] } }
      - { phase_id: phase_a, input:  "4", power: { id:  cir4, filters: [ *pos, multiply: .5 ] } }
      - { phase_id: phase_b, input:  "5", power: { id:  cir5, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "6", power: { id:  cir6, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "7", power: { id:  cir7, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "8", power: { id:  cir8, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "9", power: { id:  cir9, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "10", power: { id: cir10, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "11", power: { id: cir11, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "12", power: { id: cir12, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "13", power: { id: cir13, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "14", power: { id: cir14, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "15", power: { id: cir15, filters: [ *pos, multiply: .5 ] } }
      - { phase_id: phase_a, input: "16", power: { id: cir16, filters: [ *pos, multiply: .5 ] } }
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power

  # These are the copy sensors. These are what send the data along to HASS
  # The copy sensors filter and send the power state to HA
  - { platform: copy, name: "Phase A Power", source_id: phase_b_power, filters: *throttle_avg }
  - { platform: copy, name: "Phase B Power", source_id: phase_a_power, filters: *throttle_avg }
  - { platform: copy, name: "Total Power", source_id: total_power, filters: *throttle_avg }
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *throttle_avg }
  - { platform: copy, name: $cir_1_name, source_id:  cir1, filters: *throttle_avg }
  - { platform: copy, name: $cir_2_name, source_id:  cir2, filters: *throttle_avg }
  - { platform: copy, name: $cir_3_name, source_id:  cir3, filters: *throttle_avg }
  - { platform: copy, name: $cir_4_name, source_id:  cir4, filters: *throttle_avg }
  - { platform: copy, name: $cir_5_name, source_id:  cir5, filters: *throttle_avg }
  - { platform: copy, name: $cir_6_name, source_id:  cir6, filters: *throttle_avg }
  - { platform: copy, name: $cir_7_name, source_id:  cir7, filters: *throttle_avg }
  # - { platform: copy, name: $cir_8_name, source_id:  cir8, filters: *throttle_avg }
  # - { platform: copy, name: $cir_9_name, source_id:  cir9, filters: *throttle_avg }
  # - { platform: copy, name: $cir_10_name, source_id: cir10, filters: *throttle_avg }
  # - { platform: copy, name: $cir_11_name, source_id: cir11, filters: *throttle_avg }
  # - { platform: copy, name: $cir_12_name, source_id: cir12, filters: *throttle_avg }
  - { platform: copy, name: $cir_13_name, source_id: cir13, filters: *throttle_avg }
  - { platform: copy, name: $cir_14_name, source_id: cir14, filters: *throttle_avg }
  - { platform: copy, name: $cir_15_name, source_id: cir15, filters: *throttle_avg }
  - { platform: copy, name: $cir_16_name, source_id: cir16, filters: *throttle_avg }
  - platform: template
    lambda: return id(phase_b_power).state + id(phase_a_power).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - platform: template
    lambda: !lambda |-
      return max(0.0f, id(total_power).state -
        id( cir1).state -
        id( cir2).state -
        id( cir3).state -
        id( cir4).state -
        id( cir5).state -
        id( cir6).state -
        id( cir7).state -
        id( cir8).state -
        id( cir9).state -
        id(cir10).state -
        id(cir11).state -
        id(cir12).state -
        id(cir13).state -
        id(cir14).state -
        id(cir15).state -
        id(cir16).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: balance_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Balance Daily Energy"
    power_id: balance_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_1_name, filters: *throttle_time }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_2_name, filters: *throttle_time }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_3_name, filters: *throttle_time }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_4_name, filters: *throttle_time }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_5_name, filters: *throttle_time }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_6_name, filters: *throttle_time }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_7_name, filters: *throttle_time }
  # - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_8_name, filters: *throttle_time }
  # - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_9_name, filters: *throttle_time }
  # - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_10_name, filters: *throttle_time }
  # - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_11_name, filters: *throttle_time }
  # - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_12_name, filters: *throttle_time }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_13_name, filters: *throttle_time }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_14_name, filters: *throttle_time }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_15_name, filters: *throttle_time }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: $cir_16_name, filters: *throttle_time }
```
