### DISCUSSION TITLE
Solar excess using with devices at Vue plugs - possible? Switching time accuracy?

### DISCUSSION THREAD

**Discussion by ZXBnu** [emporia-vue-local/esphome#291] [General]
Hi,

great project, before I deep dive into, I want to find out:

Is it possible like at the origin FW, in case  of solar excess to switch on some Vue plugs with heaters - to avoid giving energy to the net outside?

If yes:

Can I set the reaction time of switching on after upcoming solar excess?

Can I define thresholds in Watts? 

The same with the switch off criteria.

And can I do sth. like 'best consumption settings', when I have e.g. one 250W and two 500W heaters - to use the 250W heater in case of 300 Watts excess and one 500W (and switching off the 250W) in case of 600 W excess.

Main wish: I would like to have fast reaction times of switching after upcoming solar excess. Does this FW make this possible?

Many thanks

Background:
I see at the origin FW sometimes a huge delay for the switching on after upcoming solar excess. (In Germany I must avoid to give too much Watts to extern for legal reasons. Even for seconds, as there is a smart two direction counter, which can see that.)

The Vu support chat mentioned to me, they'd have a delay about 1 min, not to switch too often. This is not configurable at all. (And regarding the consumption of energy amount self learning, what I really do not like.)

However I see _sometimes_ a switch on or off, right after the amount of sunlight changed or my internal consumption changed.

So 1 minute fix reaction time delay is not correct, but the reaction time at all is a matter of luck.

**Comment by ZXBnu** [comment]
Does someone please give a comment? Especially regarding accuracy of switching time in case of solar excess?

**Comment by flaviut** [comment]
> Vue plugs with heaters

I'm pretty sure the Vue plugs do not support HomeAssistant, so the answer to that precise question is no. But there are many smart plugs which do support ESPHome & HomeAssistant.

> I would like to have fast reaction times of switching after upcoming solar excess. Does this FW make this possible?

Yes, it does. The reaction time can be less than 5 seconds.

> Can I set the reaction time of switching on after upcoming solar excess?
>
> Can I define thresholds in Watts?
> 
> The same with the switch off criteria.

For details on what you can do, you can look at [the HomeAssistant automation documentation](https://www.home-assistant.io/docs/automation/trigger/). For example, and I have not tested this, this could be a potential automation:

![2024-07-03_20-53](https://github.com/emporia-vue-local/esphome/assets/5213469/e54c45b9-73e4-4188-8107-47512d197b03)

As an example from my own use, I have an automation to reduce my peak demand by turning off my hot water heater when I'm already using a lot of energy:

![Screenshot 2024-07-03 a](https://github.com/emporia-vue-local/esphome/assets/5213469/d8d17a9e-40ea-4ce1-9aaa-bcab9eb3291e)

```yaml
alias: Turn off water heater during high demand
description: >-
  Turns the water heater temperature down when we're in a period of high demand,
  and turns it back up when we have low energy demand.
trigger:
  - platform: numeric_state
    entity_id: sensor.peak_total_power_1h
    for:
      hours: 0
      minutes: 2
      seconds: 30
    above: "3000"
    id: trigger_high
  - platform: numeric_state
    entity_id: sensor.peak_total_power_1h
    below: "2500"
    for:
      hours: 0
      minutes: 5
      seconds: 0
    id: trigger_low
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: trigger_high
        sequence:
          - service: climate.set_temperature
            target:
              device_id: baf3249597b4aa1708d23538d996660f
            data:
              temperature: 110
      - conditions:
          - condition: trigger
            id: trigger_low
        sequence:
          - service: climate.set_temperature
            target:
              device_id: baf3249597b4aa1708d23538d996660f
            data:
              temperature: 150
    default: []
mode: single
```
