### DISCUSSION TITLE
Calculating Unmonitored Balance with Net Metering

### DISCUSSION THREAD

**Discussion by chrisgilldc** [emporia-vue-local/esphome#308] [Q&A]
Good morning!
I converted my Vue 2 to esphome as part of my new solar installation, and am not quite sure how to properly get it to calculate the "balance", that consumed power which isn't monitored on a specific clamp. I also think I have Total Power and Total Power Return configured incorrectly, as I don't get any consumption read when I'm both consuming and contributing. It does seem to work correctly when I have no solar production and am only on grid, or when my total use is greater than solar production.

For example, currently I have:
Solar: 2367 W
Power Return: 1568 W
Total Power: 0 W 
Balance: 0 W
Sum of all monitored circuits: 317 W
Thus, Total Power should be 799 W (Solar - Power Return) and Balance should be 482 W (Total - Monitored).

I did my best to assemble the config from the README and other posts here. Those together got me close, but I'm assuming I'm still missing something.

Here's my circuit and template configurations. I could fix up some of this in HA, I assume, but it seems more correct to fix this on the monitor itself.

I also have an issue with seeing small amounts of power, between 0 and 1 W, on circuits with no load, even when the breaker is off. From reading other posts, maybe this is a phase setting issue?

Appreciate an guidance. Thanks!

```
# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # Copy sensors will filter and then send power measurements to HA
      # These non-throttled power sensors are used for accurately calculating energy
      - phase_id: phase_a
        input: "A"  # Verified 8/7/2024
        power:
          id: phase_a_power
          filters: [*invert]
      - phase_id: phase_b
        input: "B"  # Verified 8/7/2024
        power:
          id: phase_b_power
          filters: [*invert]
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power Return"
          id: phase_a_power_return
          filters: [*throttle_avg, *pos]  # This measures energy uploaded to grid on phase A
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power Return"
          id: phase_b_power_return
          filters: [*throttle_avg, *pos]  # This measures energy uploaded to grid on phase B
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { id:  cir1, filters: [ *pos, multiply: 2 ] } } # Dryer
      - { phase_id: phase_a, input:  "2", power: { id:  cir2, filters: [ *pos ] } } # OK! Fridge
      - { phase_id: phase_b, input:  "3", power: { id:  cir3, filters: [ *pos ] } } # Solar
      - { phase_id: phase_b, input:  "4", power: { id:  cir4, filters: [ *pos, multiply: 2 ] } } # EV Charger
      - { phase_id: phase_b, input:  "5", power: { id:  cir5, filters: [ *pos ] } } # Furnace Lower
      - { phase_id: phase_b, input:  "6", power: { id:  cir6, filters: [ *pos ] } } # OK! Living Room
      - { phase_id: phase_b, input:  "7", power: { id:  cir7, filters: [ *invert ] } } # OK! ESG Study 
      - { phase_id: phase_a, input:  "8", power: { id:  cir8, filters: [ *invert, multiply: 2 ] } } # OK! A/C Upper
      - { phase_id: phase_a, input:  "9", power: { id:  cir9, filters: [ *invert, multiply: 2 ] } } # OK! Water Heater
      - { phase_id: phase_a, input: "10", power: { id: cir10, filters: [ *invert, multiply: 2 ] } } # OK! A/C Lower
      - { phase_id: phase_a, input: "11", power: { id: cir11, filters: [ *pos ] } } # Dishwasher
      - { phase_id: phase_a, input: "12", power: { id: cir12, filters: [ *invert ] } } # Loft
      - { phase_id: phase_a, input: "13", power: { id: cir13, filters: [ *pos ] } } # Washer
      - { phase_id: phase_a, input: "14", power: { id: cir14, filters: [ *pos ] } } # Furnace Upper
      - { phase_id: phase_a, input: "15", power: { id: cir15, filters: [ *pos ] } } # Chris' Study
      - { phase_id: phase_a, input: "16", power: { id: cir16, filters: [ *pos ] } } # Solar
      # 3 and 16 for Solar
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power
  # The copy sensors filter and send the power state to HA
  - { platform: copy, name: "Phase A Power", source_id: phase_a_power, filters: *throttle_avg }
  - { platform: copy, name: "Phase B Power", source_id: phase_b_power, filters: *throttle_avg }
  - { platform: copy, name: "Total Power", source_id: total_power, filters: *throttle_avg }
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *throttle_avg }
  - { platform: copy, name: "Dryer Power", source_id: cir1, filters: *throttle_avg }
  - { platform: copy, name: "Refrigerator Power", source_id: cir2, filters: *throttle_avg }
  - { platform: copy, name: "Solar Phase 2 (Red) Power", source_id: cir3, filters: *throttle_avg }
  - { platform: copy, name: "EV Charger Power", source_id: cir4, filters: *throttle_avg }
  - { platform: copy, name: "Furnace Lower Power", source_id: cir5, filters: *throttle_avg }
  - { platform: copy, name: "Living Room Power", source_id: cir6, filters: *throttle_avg }
  - { platform: copy, name: "Emily's Study Power", source_id: cir7, filters: *throttle_avg }
  - { platform: copy, name: "A/C Upper Power", source_id: cir8, filters: *throttle_avg }
  - { platform: copy, name: "Water Heater Power", source_id: cir9, filters: *throttle_avg }
  - { platform: copy, name: "A/C Lower Power", source_id: cir10, filters: *throttle_avg }
  - { platform: copy, name: "Dishwasher Power", source_id: cir11, filters: *throttle_avg }
  - { platform: copy, name: "Loft Power", source_id: cir12, filters: *throttle_avg }
  - { platform: copy, name: "Washer Power", source_id: cir13, filters: *throttle_avg }
  - { platform: copy, name: "Furnace Upper Power", source_id: cir14, filters: *throttle_avg }
  - { platform: copy, name: "Chris' Study Power", source_id: cir15, filters: *throttle_avg }
  - { platform: copy, name: "Solar Phase 1 (Black) Power", source_id: cir16, filters: *throttle_avg }  
  - platform: template
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - platform: template
    lambda: !lambda |-
      return max(0.0f, id(total_power).state -
        id( cir1).state -
        id( cir2).state -
        id( cir3).state -
        id( cir4).state -
        id( cir5).state -
        id( cir6).state -
        id( cir7).state -
        id( cir8).state -
        id( cir9).state -
        id(cir10).state -
        id(cir11).state -
        id(cir12).state -
        id(cir13).state -
        id(cir14).state -
        id(cir15).state -
        id(cir16).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: balance_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Balance Daily Energy"
    power_id: balance_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Dryer Daily Energy", filters: *throttle_time }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Refrigerator Daily Energy", filters: *throttle_time }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Solar Phase 2 (Red) Daily Energy", filters: *throttle_time }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "EV Charger Daily Energy", filters: *throttle_time }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Furnace Lower Daily Energy", filters: *throttle_time }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Living Room Daily Energy", filters: *throttle_time }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Emily's Study Daily Energy", filters: *throttle_time }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "A/C Upper Daily Energy", filters: *throttle_time }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Water Heater Daily Energy", filters: *throttle_time }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "A/C Lower Daily Energy", filters: *throttle_time }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Dishwasher Daily Energy", filters: *throttle_time }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Loft Daily Energy", filters: *throttle_time }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Washer Daily Energy", filters: *throttle_time }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Furnace Upper Daily Energy", filters: *throttle_time }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Chris' Study Daily Energy", filters: *throttle_time }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Solar Phase 1 (Black) Daily Energy", filters: *throttle_time }  
  - platform: template
    name: "Total Power Return"
    lambda: return id(phase_a_power_return).state + id(phase_b_power_return).state;
    update_interval: 1s
    id: total_power_return
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy Return"
    power_id: total_power_return
    accuracy_decimals: 0
  - platform: template
    name: "Solar Power"
    lambda: return id(cir3).state + id(cir16).state;
    id: solar_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Solar Daily Energy"
    power_id: solar_power
    accuracy_decimals: 01```

**Comment by wadesherman** [comment]
Assuming:
-  `phase_a_power` is positive when you are buying electricity and negative when you are selling
- `cir3` and `cir16` are both positive when you are producing solar

Your total energy consumed would be `total_power` + `solar_power` 
and your balance power would be `(total_power + solar_power) - cir1 - cir2 -cir4 ... etc.`

**Comment by chrisgilldc** [comment]
Each phase has a regular `_power` and a `_power_return`.

When importing, `phase_a_power` is positive and `phase_a_power_return` is 0. When exporting, `phase_a_power` is 0 and `phase_a_power_return` is positive. That looked like the right way to do it from the README, noting that it definitions for those returns should be added. I'll note in my installation, both phase clamps are backwards, so the inflow uses the `invert` template while the return doesn't.

Because of how this is split, to adjust the balance I need to add solar phases A and B and then subtract out the power return as well. I'd previously been including the solar phase A and B, which is clearly wrong.

`return max(0.0f, id(total_power).state + id(cir3).state + id(cir16).state - ... - id(total_power_return).state`

I just pushed that update out and will see how it goes.

**Reply by wadesherman** [reply]
Sounds reasonable! Nice yeah its a little confusing why you have to split the consumption from the return, but it will make sense when you setup the HA Energy Dashboard.  It expects the grid consumption and grid return to be separate total_power entities with positive values.

**Reply by chrisgilldc** [reply]
I believe I have this mostly sorted with one exception. The Total Power Return had been negative, which means I've accumulated negative Total Daily Energy Return. I've tried to reset that in HA, but it appears to be coming from the monitor. Since I can see it decreasing now, I know the new positive power values are being aggregated into the previous negative value. I presume there's no way to unsnarl that data, which is fine, but how can I reset it to zero inside the monitor?

**Reply by wadesherman** [reply]
check out this discussion on adding `restore: false` to the `total_daily_energy` sensors: https://github.com/emporia-vue-local/esphome/discussions/264#discussioncomment-10331240

They also reset at midnight, so make sure you are setting the time correctly including timezone

**Reply by chrisgilldc** [reply]
Thanks for all the feedback, @wadesherman.

I found myself getting frustrated at the way entities were named so reworked them to have a `total_power_import` and `total_power_export`. Otherwise, after being away from things for a bit, I'd find myself looking at `total_power` and wondering, wait, is that consumption or import? I also created a `total_power_consumption`, which *should* be all use from both sources, if I added it up right.

My branch sensors seem kind of out of whack. For instance the living room consistently reads ~100W, even when I turn the breaker off, which means it's probably on the wrong breaker, but as I turn other breakers off I can't find the *right* one. I'll have to wait until the family is out, turn off everything except the monitor and go one by one. Here's my current config and that might be helpful in making a more detailed guide for others.

```
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # Copy sensors will filter and then send power measurements to HA
      # These non-throttled power sensors are used for accurately calculating energy
      - phase_id: phase_a
        input: "A"  # Verified 8/7/2024
        power:
          id: phase_a_power_import
          filters: [*throttle_avg, *invert]
      - phase_id: phase_b
        input: "B"  # Verified 8/7/2024
        power:
          id: phase_b_power_import
          filters: [*throttle_avg, *invert]
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power Export"
          id: phase_a_power_export
          filters: [*throttle_avg, *pos]  # This measures energy uploaded to grid on phase A
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power Export"
          id: phase_b_power_export
          filters: [*throttle_avg, *pos]  # This measures energy uploaded to grid on phase B
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { id:  cir1, filters: [ *pos, multiply: 2 ] } } # Dryer
      - { phase_id: phase_a, input:  "2", power: { id:  cir2, filters: [ *pos ] } } # OK! Fridge
      - { phase_id: phase_b, input:  "3", power: { id:  cir3, filters: [ *pos ] } } # Solar
      - { phase_id: phase_b, input:  "4", power: { id:  cir4, filters: [ *pos, multiply: 2 ] } } # EV Charger
      - { phase_id: phase_b, input:  "5", power: { id:  cir5, filters: [ *pos ] } } # Furnace Lower
      - { phase_id: phase_b, input:  "6", power: { id:  cir6, filters: [ *pos ] } } # OK! Living Room
      - { phase_id: phase_b, input:  "7", power: { id:  cir7, filters: [ *invert ] } } # OK! ESG Study 
      - { phase_id: phase_a, input:  "8", power: { id:  cir8, filters: [ *invert, multiply: 2 ] } } # OK! A/C Upper
      - { phase_id: phase_a, input:  "9", power: { id:  cir9, filters: [ *invert, multiply: 2 ] } } # OK! Water Heater
      - { phase_id: phase_a, input: "10", power: { id: cir10, filters: [ *invert, multiply: 2 ] } } # OK! A/C Lower
      - { phase_id: phase_a, input: "11", power: { id: cir11, filters: [ *pos ] } } # Dishwasher
      - { phase_id: phase_a, input: "12", power: { id: cir12, filters: [ *invert ] } } # Loft
      - { phase_id: phase_a, input: "13", power: { id: cir13, filters: [ *pos ] } } # Washer
      - { phase_id: phase_a, input: "14", power: { id: cir14, filters: [ *pos ] } } # Furnace Upper
      - { phase_id: phase_a, input: "15", power: { id: cir15, filters: [ *pos ] } } # Chris' Study
      - { phase_id: phase_a, input: "16", power: { id: cir16, filters: [ *pos ] } } # Solar
      # 3 and 16 for Solar
    on_update:
      then:
        - component.update: total_power_export
        - component.update: total_power_import
        - component.update: solar_power
        - component.update: balance_power
  # The copy sensors filter and send the power state to HA
  - { platform: copy, name: "Phase A Power Import", source_id: phase_a_power_import, filters: *throttle_avg }
  - { platform: copy, name: "Phase A Power Export", source_id: phase_a_power_export, filters: *throttle_avg }  
  - { platform: copy, name: "Phase B Power Import", source_id: phase_b_power_import, filters: *throttle_avg }
  - { platform: copy, name: "Phase B Power Export", source_id: phase_b_power_export, filters: *throttle_avg }
  - { platform: copy, name: "Total Power Import", source_id: total_power_import, filters: *throttle_avg }
  - { platform: copy, name: "Total Power Export", source_id: total_power_export, filters: *throttle_avg }
  - { platform: copy, name: "Total Power Consumption", source_id: total_power_consumption, filters: *throttle_avg }  
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *throttle_avg }
  - { platform: copy, name: "Dryer Power", source_id: cir1, filters: *throttle_avg }
  - { platform: copy, name: "Refrigerator Power", source_id: cir2, filters: *throttle_avg }
  - { platform: copy, name: "Solar Phase 2 (Red) Power", source_id: cir3, filters: *throttle_avg }
  - { platform: copy, name: "EV Charger Power", source_id: cir4, filters: *throttle_avg }
  - { platform: copy, name: "Furnace Lower Power", source_id: cir5, filters: *throttle_avg }
  - { platform: copy, name: "Living Room Power", source_id: cir6, filters: *throttle_avg }
  - { platform: copy, name: "Emily's Study Power", source_id: cir7, filters: *throttle_avg }
  - { platform: copy, name: "A/C Upper Power", source_id: cir8, filters: *throttle_avg }
  - { platform: copy, name: "Water Heater Power", source_id: cir9, filters: *throttle_avg }
  - { platform: copy, name: "A/C Lower Power", source_id: cir10, filters: *throttle_avg }
  - { platform: copy, name: "Dishwasher Power", source_id: cir11, filters: *throttle_avg }
  - { platform: copy, name: "Loft Power", source_id: cir12, filters: *throttle_avg }
  - { platform: copy, name: "Washer Power", source_id: cir13, filters: *throttle_avg }
  - { platform: copy, name: "Furnace Upper Power", source_id: cir14, filters: *throttle_avg }
  - { platform: copy, name: "Chris' Study Power", source_id: cir15, filters: *throttle_avg }
  - { platform: copy, name: "Solar Phase 1 (Black) Power", source_id: cir16, filters: *throttle_avg }  
  - platform: template
    lambda: return id(phase_a_power_import).state + id(phase_b_power_import).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power_import
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy Import"
    power_id: total_power_import
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - platform: template
    lambda: !lambda |-
      return max(0.0f, id(total_power_import).state + id(solar_power).state -
        id( cir1).state -
        id( cir2).state -
        id( cir4).state -
        id( cir5).state -
        id( cir6).state -
        id( cir7).state -
        id( cir8).state -
        id( cir9).state -
        id(cir10).state -
        id(cir11).state -
        id(cir12).state -
        id(cir13).state -
        id(cir14).state -
        id(cir15).state -
        id(total_power_export).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: balance_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Balance Daily Energy"
    power_id: balance_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Dryer Daily Energy", filters: *throttle_time }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Refrigerator Daily Energy", filters: *throttle_time }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Solar Phase 2 (Red) Daily Energy", filters: *throttle_time }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "EV Charger Daily Energy", filters: *throttle_time }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Furnace Lower Daily Energy", filters: *throttle_time }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Living Room Daily Energy", filters: *throttle_time }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Emily's Study Daily Energy", filters: *throttle_time }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "A/C Upper Daily Energy", filters: *throttle_time }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Water Heater Daily Energy", filters: *throttle_time }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "A/C Lower Daily Energy", filters: *throttle_time }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Dishwasher Daily Energy", filters: *throttle_time }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Loft Daily Energy", filters: *throttle_time }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Washer Daily Energy", filters: *throttle_time }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Furnace Upper Daily Energy", filters: *throttle_time }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Chris' Study Daily Energy", filters: *throttle_time }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Solar Phase 1 (Black) Daily Energy", filters: *throttle_time }  
  - platform: template
    name: "Total Power Export"
    lambda: return id(phase_a_power_export).state + id(phase_b_power_export).state;
    update_interval: 1s
    id: total_power_export
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy Export"
    power_id: total_power_export
    accuracy_decimals: 0
  - platform: template
    name: "Solar Power"
    lambda: return id(cir3).state + id(cir16).state;
    id: solar_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Solar Daily Energy"
    power_id: solar_power
    accuracy_decimals: 0
  - platform: template
    name: "Total Power Consumption"
    lambda: return id(total_power_import).state + id(solar_power).state - id(total_power_export).state;
    id: total_power_consumption
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0
  - platform: total_daily_energy
    name: "Total Daily Energy Consumption"
    power_id: total_power_consumption
    accuracy_decimals: 0
```
