### DISCUSSION TITLE
Why do my phases seem opposite or wrong?  (picture inside)

### DISCUSSION THREAD

**Discussion by sofakng** [emporia-vue-local/esphome#311] [Q&A] [answered]
Here is the wiring diagram of my panel:
![annotely_image](https://github.com/user-attachments/assets/0827670a-bace-4f45-ab5d-1b2da35e17aa)

Here is a snippet of my esphome yaml:
```
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a
        input: BLACK
        calibration: 0.0194
        voltage:
          name: "Phase L Voltage"
          filters: [*pos, *pos]
      - id: phase_b
        input: RED
        calibration: 0.0194
        voltage:
          name: "Phase R Voltage"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"
        power:
          name: "Phase L Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_b
        input: "B"
        power:
          name: "Phase R Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg, *pos]
      - { phase_id: phase_a, input:  "1", power: { name:  "Circuit 1 Power", id:  cir1, filters: [ *moving_avg, *pos ] } }
```

However, if I use phase_a for circuit 1 it doesn't work (ie. displays zero).  I need to use phase_b but this is not the correct phase according to my panel.

What am I doing wrong?  It's easy enough for me to specify phase_b instead of phase_a for circuit 1 but I want to understand why this seems wrong?
