### DISCUSSION TITLE
Power sensor not showing actual sensor value updates but values do (eventually) appear in History under that same sensor

### DISCUSSION THREAD

**Discussion by snarlingllama** [emporia-vue-local/esphome#314] [Q&A]
Hey everyone! Hoping someone might have some insight into an issues I am experiencing with my Emporia Vue 2.

**PROBLEM DESCRIPTION:**
Very strange issue, which seems to be happening with only 1 clamp. I have a supplementary AC unit running at 240v (like the ones you see under hotel room windows). What is really strange is that the sensor reading updates were working fine at first, but then after I updated the phases correctly for other circuits in my YAML, this clamp does not update power values (other clamps on different circuits seem to be functioning fine). 

For example, I have a 240v oven with a separate clamp connected to it. Within 5 seconds, it shows updates for the entity. The clamp connected to the 240v AC does show the data in History (including wattage spikes when I turn the unit on), but not so much the actual entity value. I say "not so much" because last night, I ran the AC for about 5 mins, and around 5 mins later, I noticed the entity value spiked up to the approximate wattage expected. I was not able to replicate this after a second attempt, but I was also reviewing my YAML so I may have missed it.

**TROUBLESHOOTING PERFORMED SO FAR:**
- Verified clamp is on the correct circuit (2-pole circuit, 1 clamp attached to 1 wire)
- Verified the clamp is installed with the breaker arrow pointing towards the breaker
- Verified the 3.5mm connection is securely attached to the unit
- Tried changing the phase from A to B and back again (etc.)

**MY DUMB THOUGHTS/IDEAS/CURIOSITIES:**
- Faulty clamp? (was working fine originally and is giving updates in History though)
- HA just can't keep up with all the value writes/overwrites? (this seems likely, not sure how to resolve it)
- Overlooked something obvious in my YAML?
- Needs to be clamped onto the other wire/pole connected to the same circuit? (would be strange it this were the case, because it was originally working and does provide updates in History after a couple minutes)

**HA SYSTEM INFO:**
I am running HA on a hefty Intel NUC with an SSD drive, along with the follow specs:

Core:  2024.10.1
Supervisor: 2024.10.0
ESPHome Version: 2024.9.2

**YAML CODE:**
Here is my current YAML code. Also note the problematic entity is for this circuit/CT:

  - { phase_id: phase_b, input:  "5", power: { id:  cir5, filters: [ *pos, multiply: 2  ] } }
  - { platform: copy, name:  "Circuit 22 CT5 Sunroom AC Power", source_id:  cir5, filters: *throttle_avg }

```
esphome:
  name: emporiavue2
  friendly_name: Emporia Vue 2

#  on_boot:
#    priority: 500
#    then:
#    - delay: 5s

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components:
      - emporia_vue

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable Home Assistant API
api:
  encryption:
    # Encryption key is generated by the new device wizard.
    key: "<REDACTED>"

  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

ota:
  # Create a secure password for pushing OTA updates.
  - platform: esphome
    password: "<REDACTED>"

# Enable logging
logger:
  logs:
    # by default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO

wifi:
  ssid: <REDACTED>
  password: "<REDACTED>"
  use_address: <REDACTED>
  manual_ip:
    static_ip: <REDACTED>
    gateway: <REDACTED>
    subnet: 255.255.255.0
    dns1: <REDACTED>

preferences:
  # please also make sure `restore: false` is set on all `platform: total_daily_energy`
  # sensors below.
  flash_write_interval: "48h"

output:
  - platform: ledc
    pin: GPIO12
    id: buzzer
  - platform: gpio
    pin: GPIO27
    id: buzzer_gnd

rtttl:
  output: buzzer
  on_finished_playback:
    - logger.log: 'Song ended!'

button:
  - platform: template
    name: "Two Beeps"
    on_press:
      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

light:
  - platform: status_led
    name: "D3_LED"
    pin: 23
    restore_mode: ALWAYS_ON
    entity_category: config

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a

time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # Copy sensors will filter and then send power measurements to HA
      # These non-throttled power sensors are used for accurately calculating energy
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_power
          filters: [*pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          filters: [*pos]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { id:  cir1, filters: [  ] } }
      - { phase_id: phase_b, input:  "2", power: { id:  cir2, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "3", power: { id:  cir3, filters: [ multiply: 2 ] } }
      - { phase_id: phase_b, input:  "4", power: { id:  cir4, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "5", power: { id:  cir5, filters: [ *pos, multiply: 2  ] } }
      - { phase_id: phase_b, input:  "6", power: { id:  cir6, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "7", power: { id:  cir7, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "8", power: { id:  cir8, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "9", power: { id:  cir9, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input: "10", power: { id: cir10, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input: "11", power: { id: cir11, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "12", power: { id: cir12, filters: [ *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input: "13", power: { id: cir13, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "14", power: { id: cir14, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "15", power: { id: cir15, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "16", power: { id: cir16, filters: [ *pos ] } }
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power
  # The copy sensors filter and send the power state to HA
  - { platform: copy, name: "Phase A Power", source_id: phase_a_power, filters: *throttle_avg }
  - { platform: copy, name: "Phase B Power", source_id: phase_b_power, filters: *throttle_avg }
  - { platform: copy, name: "Total Power", source_id: total_power, filters: *throttle_avg }
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 8 CT1 Dishwasher Power", source_id:  cir1, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 10 CT2 Water Heater Power", source_id:  cir2, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 14 CT3 Dryer Power", source_id:  cir3, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 18 CT4 Kitchen Range Cooktop Power", source_id:  cir4, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 22 CT5 Sunroom AC Power", source_id:  cir5, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 28 CT6 Basement Baseboard Heater Power", source_id:  cir6, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 25 CT7 Kitchen Oven Power", source_id:  cir7, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 21 CT8 Furnace Power", source_id:  cir8, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 17 CT9 Water Pump Power", source_id:  cir9, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 11 CT10 Septic Pump Power", source_id: cir10, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 9 CT11 Septic Alarm Panel Power", source_id: cir11, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 3.2 CT12 Hot Tub Power", source_id: cir12, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 13 Power", source_id: cir13, filters: *throttle_time }
  - { platform: copy, name: "Circuit 14 Power", source_id: cir14, filters: *throttle_time }
  - { platform: copy, name: "Circuit 15 Power", source_id: cir15, filters: *throttle_time }
  - { platform: copy, name: "Circuit 16 Power", source_id: cir16, filters: *throttle_time }
  - platform: template
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - platform: template
    lambda: !lambda |-
      return max(0.0f, id(total_power).state -
        id( cir1).state -
        id( cir2).state -
        id( cir3).state -
        id( cir4).state -
        id( cir5).state -
        id( cir6).state -
        id( cir7).state -
        id( cir8).state -
        id( cir9).state -
        id(cir10).state -
        id(cir11).state -
        id(cir12).state -
        id(cir13).state -
        id(cir14).state -
        id(cir15).state -
        id(cir16).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: balance_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Balance Daily Energy"
    power_id: balance_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 1 Daily Energy", filters: *throttle_time }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 2 Daily Energy", filters: *throttle_time }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 3 Daily Energy", filters: *throttle_time }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 4 Daily Energy", filters: *throttle_time }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 5 Daily Energy", filters: *throttle_time }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 6 Daily Energy", filters: *throttle_time }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 7 Daily Energy", filters: *throttle_time }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 8 Daily Energy", filters: *throttle_time }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 9 Daily Energy", filters: *throttle_time }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 10 Daily Energy", filters: *throttle_time }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 11 Daily Energy", filters: *throttle_time }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 12 Daily Energy", filters: *throttle_time }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 13 Daily Energy", filters: *throttle_time }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 14 Daily Energy", filters: *throttle_time }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 15 Daily Energy", filters: *throttle_time }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 16 Daily Energy", filters: *throttle_time }
```

Any thoughts would be greatly appreciated!

**Comment by flaviut** [comment]
This is some seriously methodical troubleshooting! I think your suggestion it's HA failing to keep up might be right, although I've never heard of that before. If you remove the `sensor: INFO` line in your configuration, it should start write each value to the serial port and esphome console logs.

There's drawbacks to enabling it, so disable the verbose logs once you're done, but it will at least help narrow it down

**Reply by pgwipeout** [reply]
Hello there, I suspect that a few issues here are all experiencing the same problem.
(Symptom: Missing or lossed updates to HomeAssistant when using the HA Platform, ESP appearing to crash)

I started having problems recently with my Emporia Vue2 dying after running for a short while. It would start with dropped updates, then no updates, and eventually it would stop responding to pings. I found that toggling my router would kick it back into gear for a short while. 
I've since enabled debugging, and I've noticed the following message starts off rarely than becomes increasingly more common until the symptoms manifest:
`[21:53:32][V][api.connection:1298]: Cannot send message because of TCP buffer space`

I suspect something has changed in the HA API that causes it to block messages more often, and it looks to me like the blocked messages aren't getting cleaned up leading to a memory leak:
https://github.com/esphome/esphome/blob/dev/esphome/components/api/api_connection.cpp#L1534

Enabling the debugger module has let me track heap size, which becomes extremely unstable when it is in the process of dying. I've added a few filters that delay the submission of reports to HA and increased the time to 10s which seems to have helped but doesn't stop it entirely. I suspect the recent change in ESPHome mandating the increase to 400ms is also not helping, as it's increasing the rate that messages are sent to HA. Essentially, it's a perfect storm of dumping a lot of data all at once.

I recommend enabling verbose logging, as this message should be higher than verbose but it isn't. You'll probably want to reduce your component logging back to debug, like mine is below:
```
# Enable logging
logger:
  level: VERBOSE
  logs:
    # by default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO
    wifi: VERBOSE
    i2c: DEBUG
    emporia_vue: DEBUG
    ```
