### DISCUSSION TITLE
yml for solar please.

### DISCUSSION THREAD

**Discussion by tung256** [emporia-vue-local/esphome#327] [Q&A]
im in US. 
just got the Emporia GEN 3. can someone please share the yml code for solar? 

so far, this is what i have [from digiblur ](https://digiblur.com/2024/03/14/emporia-vue-gen3-esp32-esphome-home-assistant/)along with ethernet connection, i wont be using wifi at all.  i am not sure where to put the yml code for solar or if i need to change any code below to accomodate solar.

```
esphome:
  name: emporiavue3

substitutions:
  display_name: EmpVu3

external_components:
#  - source: github://emporia-vue-local/esphome@dev
  - source: github://digiblur/esphome-vue3@dev
    components:
      - emporia_vue
      
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

preferences:
  # the default of 1min is far too short--flash chip is rated
  # for approx 100k writes.
  flash_write_interval: "48h"   

api:
ota:
  platform: esphome

logger:
  logs:
    sensor: INFO

ethernet:
  type: RTL8201
  mdc_pin: GPIO32
  mdio_pin: GPIO33
  clk_mode: GPIO0_IN

captive_portal:

i2c:
  sda: 5
  scl: 18
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a

switch:
  - platform: restart
    name: Restart  

time:
  - platform: sntp
    id: sntp_time    

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 2.88 seconds
      window_size: 24
      # we push a new value every 1.44 seconds
      send_every: 12
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.0194  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase R Voltage"
          filters: [*pos, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.0194  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase L Voltage"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase R Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase L Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg, *pos]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { name:  "Circuit 1 Power", id:  cir1, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "2", power: { name:  "Circuit 2 Power", id:  cir2, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "3", power: { name:  "Circuit 3 Power", id:  cir3, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "4", power: { name:  "Circuit 4 Power", id:  cir4, filters: [ *moving_avg, *pos ] } }
#      - { phase_id: phase_a, input:  "5", power: { name:  "Circuit 5 Power", id:  cir5, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "5", power: { name:  "Circuit 5 Power", id:  cir5, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "6", power: { name:  "Circuit 6 Power", id:  cir6, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "7", power: { name:  "Circuit 7 Power", id:  cir7, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "8", power: { name:  "Circuit 8 Power", id:  cir8, filters: [ *moving_avg, *pos ] } }
#      - { phase_id: phase_a, input:  "9", power: { name:  "Circuit 9 Power", id:  cir9, filters: [ *moving_avg, *pos ] } }
#      - { phase_id: phase_b, input: "10", power: { name: "Circuit 10 Power", id: cir10, filters: [ *moving_avg, *pos ] } }
#      - { phase_id: phase_a, input: "11", power: { name: "Circuit 11 Power", id: cir11, filters: [ *moving_avg, *pos ] } }
#      - { phase_id: phase_a, input: "12", power: { name: "Circuit 12 Power", id: cir12, filters: [ *moving_avg, *pos ] } }
#      - { phase_id: phase_a, input: "13", power: { name: "Circuit 13 Power", id: cir13, filters: [ *moving_avg, *pos ] } }
#      - { phase_id: phase_a, input: "14", power: { name: "Circuit 14 Power", id: cir14, filters: [ *moving_avg, *pos ] } }
#      - { phase_id: phase_b, input: "15", power: { name: "Circuit 15 Power", id: cir15, filters: [ *moving_avg, *pos ] } }
#      - { phase_id: phase_a, input: "16", power: { name: "Circuit 16 Power", id: cir16, filters: [ *moving_avg, *pos ] } }
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: 10s
    id: total_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 1 Daily Energy" }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 2 Daily Energy" }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 3 Daily Energy" }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 4 Daily Energy" }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 5 Daily Energy" }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 6 Daily Energy" }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 7 Daily Energy" }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 8 Daily Energy" }
#  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 9 Daily Energy" }
#  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 10 Daily Energy" }
#  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 11 Daily Energy" }
#  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 12 Daily Energy" }
#  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 13 Daily Energy" }
#  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 14 Daily Energy" }
#  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 15 Daily Energy" }
#  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 16 Daily Energy" }
```

**Comment by abhi08638** [comment]
This is my setup 
https://github.com/abhi08638/esphome-vue3

**Reply by raidflex** [reply]
How would this work if your solar is connected at the mains, mine is lined spliced I do not have breakers? I can see returned power, but the total energy use just shows 0 when I am exporting more than the current usage. I am not sure what I need to change in the YAML code to see the current energy use even when exporting more energy from solar then I am currently using.

Edit: I was able to figured out how to add the loads of the CT clamps to get a total. But since I am not monitoring all breakers I still have some unmonitored load, how would I be able to figured out the unmonitored load as well and add it to the total? I updated the below yaml code to the latest revision. 

```
esphome:
  name: "emporiavue"
  friendly_name: "emporiavue"

external_components:
  - source: github://emporia-vue-local/esphome@vue3
    components:
      - emporia_vue

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

logger:
  logs:
    sensor: INFO
api:
ota:
  platform: esphome

ethernet:
  type: RTL8201
  mdc_pin: GPIO32
  mdio_pin: GPIO33
  clk_mode: GPIO0_IN

# Configure the two status LEDs on the Emporia Vue v3 case
light:
  - platform: status_led
    id: wifi_led
    name: "Wifi LED"
    pin:
      number: 2
      ignore_strapping_warning: true
    restore_mode: ALWAYS_ON
    entity_category: diagnostic
  - platform: status_led
    id: ethernet_led
    name: "Ethernet LED"
    pin: 4
    entity_category: config
    restore_mode: ALWAYS_OFF

preferences:
  flash_write_interval: "48h"

i2c:
  sda: 5
  scl: 18
  scan: false
  frequency: 400kHz
  timeout: 1ms
  id: i2c_a

switch:
  - platform: restart
    name: Restart

time:
  - platform: sntp
    id: my_time

# YAML references to reuse filter configurations
.defaultfilters:
  - &throttle_avg
    throttle_average: 5s
  - &throttle_time
    throttle: 60s
  - &moving_avg
    sliding_window_moving_average:
      window_size: 24
      send_every: 12
  - &invert
    lambda: 'return max(-x, 0.0f);'
  - &pos
    lambda: 'return max(x, 0.0f);'
  - &abs
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a
        input: BLACK
        calibration: 0.0192
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*moving_avg, *pos]
      - id: phase_b
        input: RED
        calibration: 0.0193
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
    ct_clamps:
      # Grid Imported Energy (Mains) - Raw sensors
      - { phase_id: phase_a, input: "A", power: { name: "Grid Import Phase A", id: phase_a_power, device_class: power, filters: [*moving_avg, *pos] } }
      - { phase_id: phase_b, input: "B", power: { name: "Grid Import Phase B", id: phase_b_power, device_class: power, filters: [*moving_avg, *pos] } }
      # Grid Exported Energy (Mains) - Raw sensors
      - { phase_id: phase_a, input: "A", power: { name: "Grid Export Phase A", id: phase_a_power_return, filters: [*moving_avg, *invert] } }
      - { phase_id: phase_b, input: "B", power: { name: "Grid Export Phase B", id: phase_b_power_return, filters: [*moving_avg, *invert] } }
      # Individual Load Circuits (1-16)
      - { phase_id: phase_b, input:  "1", power: { name:  "Circuit 1 Power", id:  cir1, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "2", power: { name:  "Circuit 2 Power", id:  cir2, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "3", power: { name:  "Circuit 3 Power", id:  cir3, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "4", power: { name:  "Circuit 4 Power", id:  cir4, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "5", power: { name:  "Circuit 5 Power", id:  cir5, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "6", power: { name:  "Circuit 6 Power", id:  cir6, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "7", power: { name:  "Circuit 7 Power", id:  cir7, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "8", power: { name:  "Circuit 8 Power", id:  cir8, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "9", power: { name:  "Circuit 9 Power", id:  cir9, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input: "10", power: { name: "Circuit 10 Power", id: cir10, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "11", power: { name: "Circuit 11 Power", id: cir11, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "12", power: { name: "Circuit 12 Power", id: cir12, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input: "13", power: { name: "Circuit 13 Power", id: cir13, filters: [ *moving_avg, *pos, multiply: 2 ] } }
      - { phase_id: phase_a, input: "14", power: { name: "Circuit 14 Power", id: cir14, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "15", power: { name: "Circuit 15 Power", id: cir15, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "16", power: { name: "Circuit 16 Power", id: cir16, filters: [ *moving_avg, *pos ] } }

  # --- TOTALS AND CALCULATED SENSORS ---

  # Total Grid Export (from Mains)
  - platform: template
    name: "Grid Export"
    id: total_power_return
    lambda: 'return id(phase_a_power_return).state + id(phase_b_power_return).state;'
    update_interval: 10s
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  # Total Grid Import (from Mains)
  - platform: template
    name: "Grid Import"
    id: total_power
    lambda: 'return id(phase_a_power).state + id(phase_b_power).state;'
    update_interval: 10s
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  # Total Home Consumption (Sum of all 16 monitored circuits)
  # Unmonitored load calculation has been removed. This is the sum of all measured circuits.
  - platform: template
    name: "Total Energy"
    id: total_home_consumption
    lambda: |-
      return id(cir1).state + id(cir2).state + id(cir3).state + id(cir4).state + 
             id(cir5).state + id(cir6).state + id(cir7).state + id(cir8).state + 
             id(cir9).state + id(cir10).state + id(cir11).state + id(cir12).state + 
             id(cir13).state + id(cir14).state + id(cir15).state + id(cir16).state;
    update_interval: 10s
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0

  # --- DAILY ENERGY SENSORS (RIEMANN SUMS) ---

  - platform: total_daily_energy
    name: "Total Daily Grid Export"
    power_id: total_power_return
  - platform: total_daily_energy
    name: "Total Daily Grid Import"
    power_id: total_power
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_home_consumption

  # Daily energy for each individual circuit
  - { power_id:  cir1, platform: total_daily_energy, name:  "Circuit 1 Daily Energy" }
  - { power_id:  cir2, platform: total_daily_energy, name:  "Circuit 2 Daily Energy" }
  - { power_id:  cir3, platform: total_daily_energy, name:  "Circuit 3 Daily Energy" }
  - { power_id:  cir4, platform: total_daily_energy, name:  "Circuit 4 Daily Energy" }
  - { power_id:  cir5, platform: total_daily_energy, name:  "Circuit 5 Daily Energy" }
  - { power_id:  cir6, platform: total_daily_energy, name:  "Circuit 6 Daily Energy" }
  - { power_id:  cir7, platform: total_daily_energy, name:  "Circuit 7 Daily Energy" }
  - { power_id:  cir8, platform: total_daily_energy, name:  "Circuit 8 Daily Energy" }
  - { power_id:  cir9, platform: total_daily_energy, name:  "Circuit 9 Daily Energy" }
  - { power_id: cir10, platform: total_daily_energy, name: "Circuit 10 Daily Energy" }
  - { power_id: cir11, platform: total_daily_energy, name: "Circuit 11 Daily Energy" }
  - { power_id: cir12, platform: total_daily_energy, name: "Circuit 12 Daily Energy" }
  - { power_id: cir13, platform: total_daily_energy, name: "Circuit 13 Daily Energy" }
  - { power_id: cir14, platform: total_daily_energy, name: "Circuit 14 Daily Energy" }
  - { power_id: cir15, platform: total_daily_energy, name: "Circuit 15 Daily Energy" }
  - { power_id: cir16, platform: total_daily_energy, name: "Circuit 16 Daily Energy" }

```
