### DISCUSSION TITLE
Inaccurate Readings - Emporia Vue 3/Home Assistant

### DISCUSSION THREAD

**Discussion by duckdude555** [emporia-vue-local/esphome#331] [Q&A]
Just installed Emporia Vue 3 in my box - but I’m getting weird readings that don’t make sense. 

1) Power = Current * Voltage. Across all my circuits, the reported power value does not match the phase voltage and reported current. This is for all my individual CTs and the main phases as well. For example - my Circuit * is reported 124.1 V and 2.5 A = 310W, not 268W like what's reported (almost 15% off). I verified the voltage readings are correct and recalibrated myself. The measured current values *seem* to be accurate but I do not have a way to verify them. 

2) Phase A & B reported current do not get even close to the sum of my individual CT’s and are obviously inaccurate - I WISH my entire home was only pulling 3 Amps. Am I calling the main phase CT’s incorrectly? 

Any ideas? Is this an issue with my config? My YAML is below, along with a picture of what a snippet of my Home Assistant sensors look like and by wiring. Thank you!!!

```
substitutions:

  name: vue
  friendly_name: Emporia Home Energy Monitor

  # Circuit Labels used for publishing to Home Assistant
  circuit_1:  "Circuit 1"
  circuit_2:  "Circuit 2"
  circuit_3:  "Circuit 3"
  circuit_4:  "Circuit 4"
  circuit_5:  "Circuit 5"
  circuit_6:  "Circuit 6"
  circuit_7:  "Circuit 7"
  circuit_8:  "Circuit 8"
  circuit_9:  "Circuit 9"
  circuit_10: "Circuit 10"
  circuit_11: "Circuit 11"
  circuit_12: "Circuit 12"
  circuit_13: "Circuit 13"
  circuit_14: "Circuit 14"
  circuit_15: "Circuit 15"
  circuit_16: "Circuit 16"

  # Icons for Home Assistant
  icon_circuit: "mdi:power-plug"
  icon_current: "mdi:current-ac"
  icon_meter:   "mdi:meter-electric"
  icon_phase:   "mdi:angle-acute"
  icon_power:   "mdi:transmission-tower-import"
  icon_voltage: "mdi:transmission-tower"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  #on_boot:
  #  priority: 200  
  #  then:
  #    - wait_until:  
  #        condition:
  #          wifi.connected: 
  #        timeout: 5s

external_components:
  - source: github://emporia-vue-local/esphome@vue3
    components:
      - emporia_vue

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable Home Assistant API
api:
  password: "xxxx"

 

ota:
  # Create a secure password for pushing OTA updates.
  platform: esphome
  password: "xxxx"

# Enable logging
logger:
  logs:
    # by default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO

wifi:
  ssid: "xxxx"
  password: "xxxx"
  manual_ip:
    static_ip: 192.168.xxx.xxx
    gateway: 192.168.xxx.xxx
    subnet: 255.255.255.0

   #E nable fallback hotspot in case wifi connection fails
  ap:
    ssid: "emporia-vue-3-1"
    password: "fallback"

preferences:
  # please also make sure `restore: false` is set on all `platform: total_daily_energy`
  # sensors below.
  flash_write_interval: "48h"

light:
  - platform: status_led
    #name: "D3_LED"
    id: wifi_led
    #pin: 2
    pin:
      number: 2
      ignore_strapping_warning: true
    restore_mode: ALWAYS_OFF
    #entity_category: config
  - platform: status_led
    #name: "D31_LED"
    id: ethernet_led
    pin: 4
    restore_mode: ALWAYS_OFF
    #entity_category: config

# The restart button platform allows you to restart your node remotely through Home Assistant.
button:
  - platform: restart
    name: Restart
    id: restart_button
    icon: mdi:restart
  - platform: safe_mode
    name: Restart (Safe Mode)
    id: safe_mode_button
    icon: mdi:restart-alert



i2c:
  sda: 5
  scl: 18
  scan: false
  frequency: 400kHz  # recommended range is 50-200kHz
  id: i2c_a
  timeout: 1ms

#time:
#  - platform: sntp
#    id: my_time
time:
  - platform: homeassistant
# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  # throttle_avg - emporia-vue-local
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s

  # moving_avg - digitalblur
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 2.88 seconds
      window_size: 24
      # we push a new value every 1.44 seconds
      send_every: 12
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'
  - &zero
    # Use for disconnected circuits to return 0
    lambda: "return 0.0f;"
  - &double
    # Use to double the measurement for 240V breakers
    multiply: 2

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      # Verify that this specific phase/leg is connected to correct input wire color on device listed below
      - id: phase_a
        # Vue device wire color
        input: RED
        # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        calibration: 0.01925
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        phase_angle:
          name: "Phase A Phase Angle"
          filters: [*moving_avg, *pos]
      # Verify that this specific phase/leg is connected to correct input wire color on device listed below
      - id: phase_b
        # Vue device wire color
        input: BLACK
        # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        calibration: 0.01912
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase B Frequency"
          filters: [*moving_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # These non-throttled power sensors are used for accurately calculating energy.
      # Copy sensors defined later will filter and then send power measurements to Home Assistant.
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # Copy sensors will filter and then send power measurements to HA
      # These non-throttled power sensors are used for accurately calculating energy
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_power
          filters: [*pos]
        current:
          id: phase_a_current
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          filters: [*pos]
        current:
          id: phase_b_current
      # Main Service CT Clamps (up to 3)
      # Verify the correct input on the device is connected to the CT clamp phase defined (Vue 3 inputs are inverted)
      #- { input: "A", phase_id: phase_a, power: { id: phase_a_power, filters: *invert }, current: { id: phase_a_current } }
      #- { input: "B", phase_id: phase_b, power: { id: phase_b_power, filters: *invert }, current: { id: phase_b_current } }
      # - { input: "C", phase_id: phase_c, power: { id: phase_c_power, filters: *invert } }

      # Circuit CT Clamps (up to 16)
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      # Use *abs filter to always take the positive absolute value
      # Use *invert filter for inverted positive values (Vue 3 inputs are inverted) or *zero for un-used inputs
      # Use *double filter for double (240v) breakers (this will assume power is evenly divided between the two legs)
      # example for double breaker
      #- { phase_id: phase_a, input: "9", power: { name: "Breaker 2a", id: circuit_9, filters: [ *moving_avg, *invert, multiply: 2 ] } }
      # example for phase b
      #- { phase_id: phase_b, input: "10", power: { name: "Breaker 2b - XYZ", id: circuit_10, filters: [ *moving_avg, *invert ] } }
      - { input: "1",  phase_id: phase_a, power: { id: c1_pwr,  filters: [ *abs ] }, current: { id: c1_cur,  filters: [ *abs ] } } 
      - { input: "2",  phase_id: phase_a, power: { id: c2_pwr,  filters: [ *abs ] }, current: { id: c2_cur,  filters: [ *abs ] } } 
      - { input: "3",  phase_id: phase_b, power: { id: c3_pwr,  filters: [ *abs ] }, current: { id: c3_cur,  filters: [ *abs ] } } 
      - { input: "4",  phase_id: phase_a, power: { id: c4_pwr,  filters: [ *abs ] }, current: { id: c4_cur,  filters: [ *abs ] } } 
      - { input: "5",  phase_id: phase_a, power: { id: c5_pwr,  filters: [ *abs ] }, current: { id: c5_cur,  filters: [ *abs ] } } 
      - { input: "6",  phase_id: phase_b, power: { id: c6_pwr,  filters: [ *abs ] }, current: { id: c6_cur,  filters: [ *abs ] } } 
      - { input: "7",  phase_id: phase_a, power: { id: c7_pwr,  filters: [ *abs ] }, current: { id: c7_cur,  filters: [ *abs ] } } 
      - { input: "8",  phase_id: phase_b, power: { id: c8_pwr,  filters: [ *abs ] }, current: { id: c8_cur,  filters: [ *abs ] } } 
      - { input: "9",  phase_id: phase_b, power: { id: c9_pwr,  filters: [ *abs ] }, current: { id: c9_cur,  filters: [ *abs ] } } 
      - { input: "10", phase_id: phase_a, power: { id: c10_pwr, filters: [ *abs ] }, current: { id: c10_cur,  filters: [ *abs ] } } 
      - { input: "11", phase_id: phase_b, power: { id: c11_pwr, filters: [ *abs ] }, current: { id: c11_cur,  filters: [ *abs ] } }
      - { input: "12", phase_id: phase_a, power: { id: c12_pwr, filters: [ *abs, *double ] }, current: { id: c12_cur, filters: [ *abs, *double ] } } 
      - { input: "13", phase_id: phase_a, power: { id: c13_pwr, filters: [ *abs, *double ] }, current: { id: c13_cur, filters: [ *abs, *double ] } } 
      - { input: "14", phase_id: phase_a, power: { id: c14_pwr, filters: [ *abs, *double ] }, current: { id: c14_cur, filters: [ *abs, *double ] } } 
      - { input: "15", phase_id: phase_b, power: { id: c15_pwr, filters: [ *abs, *double ] }, current: { id: c15_cur, filters: [ *abs, *double ] } } 
      - { input: "16", phase_id: phase_b, power: { id: c16_pwr, filters: [ *abs, *double ] }, current: { id: c16_cur, filters: [ *abs, *double ] } } 

    # Update total power and balance power readings at the same time.
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power

      
  # The total power sensor will be updated after all power sensors update via on_update trigger.
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    id: total_power
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: template
    name: "Total Current"
    lambda: return id(phase_a_current).state + id(phase_b_current).state;
    id: total_current
    update_interval: never
    device_class: current
    state_class: measurement
    unit_of_measurement: "A"

  # The balance power sensor will be updated after all power sensors update via on_update trigger.
  - platform: template
    id: balance_power
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    lambda: !lambda |-
      return max(0.0f, id(total_power).state
        - id( c1_pwr).state
        - id( c2_pwr).state
        - id( c3_pwr).state
        - id( c4_pwr).state
        - id( c5_pwr).state
        - id( c6_pwr).state
        - id( c7_pwr).state
        - id( c8_pwr).state
        - id( c9_pwr).state
        - id(c10_pwr).state
        - id(c11_pwr).state
        - id(c12_pwr).state
        - id(c13_pwr).state
        - id(c14_pwr).state
        - id(c15_pwr).state
        - id(c16_pwr).state
      );

  # Copy sensors to publish the each power state to Home Assistant.
  - { platform: copy, name: "Phase A Power", source_id: phase_a_power, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Phase B Power", source_id: phase_b_power, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Total Power",   source_id: total_power,   filters: *moving_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "${circuit_1} Power",  source_id: c1_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_2} Power",  source_id: c2_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_3} Power",  source_id: c3_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_4} Power",  source_id: c4_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_5} Power",  source_id: c5_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_6} Power",  source_id: c6_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_7} Power",  source_id: c7_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_8} Power",  source_id: c8_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_9} Power",  source_id: c9_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_10} Power", source_id: c10_pwr, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_11} Power", source_id: c11_pwr, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_12} Power", source_id: c12_pwr, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_13} Power", source_id: c13_pwr, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_14} Power", source_id: c14_pwr, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_15} Power", source_id: c15_pwr, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_16} Power", source_id: c16_pwr, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }

  # Copy sensors to publish the each current state to Home Assistant.
  - { platform: copy, name: "${circuit_1} Current",  source_id: c1_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_2} Current",  source_id: c2_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_3} Current",  source_id: c3_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_4} Current",  source_id: c4_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_5} Current",  source_id: c5_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_6} Current",  source_id: c6_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_7} Current",  source_id: c7_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_8} Current",  source_id: c8_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_9} Current",  source_id: c9_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_10} Current", source_id: c10_cur, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_11} Current", source_id: c11_cur, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_12} Current", source_id: c12_cur, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_13} Current", source_id: c13_cur, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_14} Current", source_id: c14_cur, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_15} Current", source_id: c15_cur, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_16} Current", source_id: c16_cur, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "Phase A Current", source_id: phase_a_current, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "Phase B Current", source_id: phase_b_current, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }

  # The total daily energy sensors to be published to Home Assistant
  - { platform: total_daily_energy, name: "Total Daily Energy", power_id: total_power,     filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "Balance Daily Energy", power_id: balance_power, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_1} Daily Energy",  power_id: c1_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_2} Daily Energy",  power_id: c2_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_3} Daily Energy",  power_id: c3_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_4} Daily Energy",  power_id: c4_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_5} Daily Energy",  power_id: c5_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_6} Daily Energy",  power_id: c6_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_7} Daily Energy",  power_id: c7_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_8} Daily Energy",  power_id: c8_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_9} Daily Energy",  power_id: c9_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_10} Daily Energy", power_id: c10_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_11} Daily Energy", power_id: c11_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_12} Daily Energy", power_id: c12_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_13} Daily Energy", power_id: c13_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_14} Daily Energy", power_id: c14_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_15} Daily Energy", power_id: c15_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_16} Daily Energy", power_id: c16_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
``` 

![IMG_0062](https://github.com/user-attachments/assets/62b9d06e-e758-4039-b355-79319ef7ecd6)
![IMG_8846](https://github.com/user-attachments/assets/f8c691b4-5810-49e1-8881-d90d21ef2743)
