### DISCUSSION TITLE
Questions on Phase, Multi-Pole Breakers and Terminology and Setup for Vue Gen 3

### DISCUSSION THREAD

**Discussion by shull49** [emporia-vue-local/esphome#332] [Q&A] [answered]
Little background, I have a large 100yr old house.  We have the main electrical panel on the main floor of the house.  Then 100A from there runs to a panel in the basement, and another 100A runs from the basement to the garage panel.  Almost everything I want to really monitor is in the basement and garage panels.  Thankfully, because there is no way in hell I'm fitting any clips into the main panel!

I am not great with electrical and I'm new to Home Assistant (yeah, not a great combo right now), so please excuse my dumb questions.

![Basement_Panel_1](https://github.com/user-attachments/assets/cd758db9-b24e-4639-a52c-c01bd8e55059)
![Basement_Panel_2](https://github.com/user-attachments/assets/0aafb628-6e4d-4c74-abdf-1528bd0cb806)
![Basement_Panel_3](https://github.com/user-attachments/assets/60611b83-9e9d-4292-b5d5-381012dcc9eb)
The basement panel has 3 wires coming into it.  Black goes to the left side, red/black to the right, and the black/white connects in the middle which is the neutral.  The #1 big clip is connected to the black (left), and #2 to the red (right).  So I assume #1 is phase a, and #2 is phase b?

```
 # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { name:  "Circuit 1 Power", id:  cir1, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "2", power: { name:  "Circuit 2 Power", id:  cir2, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "3", power: { name:  "Circuit 3 Power", id:  cir3, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "4", power: { name:  "Circuit 4 Power", id:  cir4, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "5", power: { name:  "Circuit 5 Power", id:  cir5, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "6", power: { name:  "Circuit 6 Power", id:  cir6, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "7", power: { name:  "Circuit 7 Power", id:  cir7, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "8", power: { name:  "Circuit 8 Power", id:  cir8, filters: [ *moving_avg, *pos ] } }
```

Right now I have everything set to phase a, which could be part of my issue.  Circuit clips 5-8 are on the right side, so I need to change all of those to "phase b"

Circuit clips 2 and 3 are connected to the 30A breaker for the dryer.  Clip 2 is on the black wire, and clip 3 is on the red wire.  When I run the dryer I get quite the reading 2,124.8W, which seems a BIT high, on clip 3, but nothing on clip 2.  So something doesn't seem right with that.  I've read that you can put clips on both of the wires, but you don't need to.  It wasn't clear if using both clips provides better results, or if adding "multiply: 2" is good/close enough, but if I multiply I'm thinking 5000W is WAY wrong!  I'd prefer to free up the clip if I can, most of the breakers in the garage are 2-pole, so I'd rather not use 2 clips for each one.
![Vue3_2](https://github.com/user-attachments/assets/195bce06-ebbf-4c87-b80a-ecf17f87b486)
![LG Dryer](https://github.com/user-attachments/assets/a05514e1-5776-47a2-bfe8-4fdca365865a)

What exactly is the "Circuit # Daily Energy"?  I THINK it's a running total of the energy used on that circuit.  When does it reset?  Midnight?  Is there a way to view this as a bar graph for time (hours/days) vs the line graph?

It doesn't look like the Total Power is being calculated.  Is something wrong with my YAML?
![Vue3_3](https://github.com/user-attachments/assets/2bf829c0-66ae-4728-90f5-67e880ae7137)

```
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: 10s
    id: total_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 1 Daily Energy" }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 2 Daily Energy" }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 3 Daily Energy" }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 4 Daily Energy" }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 5 Daily Energy" }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 6 Daily Energy" }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 7 Daily Energy" }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 8 Daily Energy" }
```

If I'm reading the YAML correctly, the "Total Power" is the current power usage and it's reading the power usage from the big clips, correct?  
Then it looks like the "Total Daily Energy" is using the sum of the individual  circuits.  I guess that makes sense if you are only interested in monitored circuits.  But what if I want to also track all the power used, even the unmonitored power.

I think I need 4 variables.  
Total Power Usage - Current Total Power Usage from the big clips
Total Monitored Power Usage - Current Total Power Usage from all monitored circuits
Total Daily Usage - Sum of "Total Power Usage" for the day
Total Monitored Usage - Sum of "Total Monitored Power Usage" for the day

How would I modify the YAML to accomplish this?

**Comment by shull49** [comment]
Oh yeah.  When the electrician connected the Vue Gen 3 he put in a 2-pole 20A just for the Vue.  That seems like a waste of space, particularly when the panel is so packed I can't put the cover on it.  Can't it be connected to existing breakers?

**Reply by flaviut** [reply]
Sure. Page 17 of [the installation manual](https://www.emporiaenergy.com/wp-content/uploads/2024/03/Emporia-Vue-Gen-3-Installation-Guide-v1.20.pdf) shows that as one of the options.

**Comment by flaviut** [comment]
> The #1 big clip is connected to the black (left), and 2 to the red (right). So I assume #1 is phase a, and 2 is phase b?

The phase mapping doesn't come from the big clamps. It comes from the voltage sense wires, which aren't in the pictures. Which... oof that is a cramped panel, I'm glad mine had a bit more space.

It is possible to have the wrong phase mapping on the main clamps.

> I have everything set to phase a, which could be part of my issue

Definitely!

>  When I run the dryer I get quite the reading 2,124.8W, which seems a BIT high, on clip 3, but nothing on clip 2.

4.2kW seems reasonable, standard US dryers are huge power hogs. Flip clip 2 around, and you will see data. Electricity flows in a loop, and since your clamp arrows are pointed in the same direction, `filters: [ *pos ]` floors the readings at 0 rather than letting them go negative.

For a dryer though, I would just remove the second clamp and use the `multiply: 2` filter to double the power. They are simple devices electrically. Same thing for a resistive water heater.

> What exactly is the "Circuit # Daily Energy"?

Yup, it's a running total that resets around midnight. It is really intended to be used by Home Assistant's energy tab, not by you directly though. You can use the Home Assistant energy tab to view it as a bar chart, [see the first screenshot here](https://github.com/emporia-vue-local/esphome?tab=readme-ov-file#setting-up-emporia-vue-2-with-esphome).

> It doesn't look like the Total Power is being calculated. Is something wrong with my YAML?

Your Phase L & Phase R power are zero. So it makes sense that zero integrated over time is still zero.

Your main power readings are zero because you've got the phases reversed.

>  Total Power Usage - Current Total Power Usage from the big clips

"Total Power"

> Total Daily Usage - Sum of "Total Power Usage" for the day

"Total Daily Energy"

> Total Monitored Power Usage - Current Total Power Usage from all monitored circuits
> Total Monitored Usage - Sum of "Total Monitored Power Usage" for the day

I'm not sure why you want this, but the example config already has "Balance Power" = "Total Power" - "All Clamps Power". Or in English, "how much of the overall power draw is not captured by the small clamps," which I think may be your actual goal here.

**Reply by shull49** [reply]
Thanks for your reply!!

>  oof that is a cramped panel, I'm glad mine had a bit more space.

Sadly the main panel is far, far worse.  You can't even fit another wire in there let alone clips and the Vue device.

> > The #1 big clip is connected to the black (left), and 2 to the red (right). So I assume #1 is phase a, and 2 is phase b?
> 
> The phase mapping doesn't come from the big clamps. It comes from the voltage sense wires, which aren't in the pictures.

Big clip 1 is plugged into A, and big clip 2 is plugged into B on the Vue, that's where I thought the phase a and phase b came from.
I have NO idea how you get the phases from the voltage sense wires, but...
N is connected to the Neutral bar, L1 and L2 are both connected to the 20A 2-Pole on the lower left side of the panel.  L1 is connected to the top screw, and L2 is connected to the lower screw on the breaker.  The blue wire isn't connected at all.
I'm looking at step 7(a) in the instructions, and it says to use two breakers (not a 2-pole) and it has both the white AND blue connected to the neutral.
 
> > I have everything set to phase a, which could be part of my issue
> 
> Definitely!

How do I know what is phase a and b so I can correct them?
 
> > When I run the dryer I get quite the reading 2,124.8W, which seems a BIT high, on clip 3, but nothing on clip 2.
> 
> 4.2kW seems reasonable, standard US dryers are huge power hogs.
> For a dryer though, I would just remove the second clamp and use the `multiply: 2` filter to double the power. They are simple devices electrically. Same thing for a resistive water heater.

I dug up the paperwork for the dryer and it says peak is 4000-5000W, wow, I had no idea!  Now I know I need to make sure my wife and daughter aren't using it to dry like two items of clothing!

> Flip clip 2 around, and you will see data. Electricity flows in a loop, and since your clamp arrows are pointed in the same direction, `filters: [ *pos ]` floors the readings at 0 rather than letting them go negative.

On page 15, the instructions say "IMPORTANT! The Breaker imprint on the bottom of the CTs should point toward the breakers"  I assumed that was true of both big clips.  I was going to flip it just so I could see if it works, but I can't really get it the latch without shoving my hand back in there, and I'm just not brave/stupid enough to do that.  I THINK if I turn off the breaker that feeds the basement panel that it would be safe, but if I'm wrong it could kill me, so... yeah...

> For a dryer though, I would just remove the second clamp and use the `multiply: 2` filter to double the power. They are simple devices electrically. Same thing for a resistive water heater.

Excellent.  Not sure what a resistive water heater is, we have an old school boiler.  It kicks ass, even with TWO TEENS taking absurdly long showers there was enough for my wife and I BOTH to take showers afterwards!
I have several mini-splits (aka ductless heat pump), I assume I can do the same thing and just monitor the one line and double it.

> > It doesn't look like the Total Power is being calculated. Is something wrong with my YAML?
> 
> Your Phase L & Phase R power are zero. So it makes sense that zero integrated over time is still zero.
> Your main power readings are zero because you've got the phases reversed.

So if I reverse big clip 2 it should fix that?

> I'm not sure why you want this, but the example config already has "Balance Power" = "Total Power" - "All Clamps Power". Or in English, "how much of the overall power draw is not captured by the small clamps," which I think may be your actual goal here.

Yeah, I think the terminology is throwing me off.  I am sure once I get the readings straightened out I'd be able to look at the numbers and see what makes sense.  I'm a data geek, so I'm looking forward to crunching numbers to see what I find!

**Reply by flaviut** [reply]
This is the part of the config that specifies the phase-to-color mapping:

```
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
```

> How do I know what is phase a and b so I can correct them?

> So if I reverse big clip 2 it should fix that?

If you want to get it right the first time, you can look at the panel schematic. But since you know it's backwards now, you just need to flip "RED" and "BLACK" in the config above. You definitely don't need to change the installation.

> On page 15, the instructions say "IMPORTANT! The Breaker imprint on the bottom of the CTs should point toward the breakers"

It's talking about the main breaker clamps in that picture. Page 27 is about the branch clamps, and it doesn't specify a direction since the app will guess. I'm a bit of a control freak, and anyway writing the code to guess is significantly more work, so I suggest installing the clamps pointing in the direction the current is flowing so you don't need to change the config `*pos` to `*invert`. If you do need to use `*invert`, use it. There's no downside.

> Excellent. Not sure what a resistive water heater is, we have an old school boiler. It kicks ass, even with TWO TEENS taking absurdly long showers there was enough for my wife and I BOTH to take showers afterwards!

Depends how old school! If it's electric, then yup it'll be resistive, but if you're having to fill it with coal every morning then that's something else!

> I have several mini-splits (aka ductless heat pump), I assume I can do the same thing and just monitor the one line and double it.

I would not assume a mini-split is balanced. You can measure to see, but mini-splits are a lot more complicated than traditional appliances and HVAC systems.

**Reply by shull49** [reply]
I just don't get the phases and how you know which is which and how to know which one to use for a breaker.  Can you explain it like I'm 5yrs old?

I just installed another Vue Gen3 in my garage panel.  THANKFULLY this one has plenty of room, and I can turn it off from the basement panel so I don't have to worry about killing myself.  My daughter insisted on sitting there to watch "just in case".  She doesn't trust me after I ran my hand through the table saw... On the literal last cut needed to finish the kitchen reno!

I have two minisplit condensers, and a 50A outlet for charging our EVs on it.  I connected everything to see what I'd get.  Interestingly the EV charger and both minisplits only gave me data from one of the two clips that were on each of them.  So looks like I will double those.

In the basement I moved some clips and added a few to test some things.  Oddly enough one of the minisplits gave me data from BOTH clips, and they were pretty close to each other 537.1 and 534.9, so I think I can pull one and double.  I find that very odd since all of these are the same brand (MrCool).

The oven needs both clips though.  How can I combine them so I only have one output?  They are cir7 and cir8.

Last thing.  The power to the garage panel runs from the basement panel.  Is there a way I can subtract the power of the garage panel from the totals for the basement panel?

**Reply by flaviut** [reply, marked as answer]
This is what a panel looks like empty:

![s-l1600](https://github.com/user-attachments/assets/dc114c1e-35a4-4d82-bfc1-0288332f4a0c)

When you put a breaker in, it either connects to the left side (phase A), or the right side (phase B). Or if it is a dual-pole breaker, it connects to both. There should be a sticker on the back of the panel door that shows you a diagram.

>  She doesn't trust me after I ran my hand through the table saw

That is terrifying! I hope you kept your fingers

> only gave me data from one of the two clips

Both clips are giving you data, but for one of them the data is negative, and `*pos` is flooring it at zero. You can use `*invert` to negate it.

>  How can I combine them so I only have one output? They are cir7 and cir8.

This is a bit complicated. You can look at https://github.com/emporia-vue-local/esphome/discussions/326#discussioncomment-12025858 for a starting point.

>  Is there a way I can subtract the power of the garage panel from the totals for the basement panel?

This would be something for your home assistant configuration. I'm not really familiar with that.

**Reply by shull49** [reply]
> That is terrifying! I hope you kept your fingers

Yes, the blade caught my thumb.  All things considered, it's about the best injury I could have gotten.  Only caught flesh, no nerve, bone, etc.  Got 4 stitches, and I swear to God that the injections to "numb" it hurt worst than the initial injury!!

**Comment by shull49** [comment]
Just called the electrician, he's going to come out tomorrow to swap the 20A 2-pole with two 15A, connect the blue wire to the neutral bar, and flip clip 2

**Reply by flaviut** [reply]
That sounds fine, but IMO none of that stuff with either hurt or help.

**Reply by shull49** [reply]
@flaviut Ok, I have spent a lot of time playing with the garage panel vue.  Here is what I have:

![PXL_20250221_055604997 MP](https://github.com/user-attachments/assets/18de7e02-a7a6-4159-937e-bd7764f2379a)
I need the left side to be Phase A, and Phase L Power and the right side to be Phase B/Phase R Power or my head will literally explode!

![PXL_20250221_055711597 MP](https://github.com/user-attachments/assets/820cc314-405e-4bec-b9c5-dbb3f52fedae)
I looked for a diagram, but all I found was this on the box.

![PXL_20250221_052257280 MP~2](https://github.com/user-attachments/assets/00407692-9047-4a39-96ac-c5705a575f11)
Here is how my breakers are laid out and the clip numbers are next to them.  The EV Charger and Kitchen/Dining Minisplit are both two pole breakers.

![garage-panel-pwoer](https://github.com/user-attachments/assets/d71fdf30-3a4f-44b0-8a40-b20a1388dd54)
This is how things are looking now, but the math isn't mathing for the Phase and Total powers considering the EV alone is pulling 6900W

If I add up "phase_a" (clips 3, 4, 7, 8, 9, 11) I get about 808.2
If I add up "phase_b" (clips 1, 2, 5, 6, 10) I get about 7024.5

I did have several that I had to invert to get a positive number.  Even when I changed the phase they still gave me a negative number.

Here is my code:
```
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
	
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.0194  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase L Voltage"
          filters: [*moving_avg]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.0194  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase R Voltage"
          filters: [*moving_avg]
		  
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase L Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase R Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg]

      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "7", power: { name:  "07- Center Pole Power",            id:  cir7, filters: [ *invert, *moving_avg ] } }
      - { phase_id: phase_a, input:  "9", power: { name:  "09- Ceiling Outlets",              id:  cir9, filters: [ *moving_avg ] } }
      - { phase_id: phase_a, input:  "3", power: { name:  "03- Dining/Kitchen MiniSplit(a)",  id:  cir3, filters: [ *moving_avg ] } }
      - { phase_id: phase_a, input:  "4", power: { name:  "04- Dining/Kitchen MiniSplit(b)",  id:  cir4, filters: [ *invert, *moving_avg ] } }
      - { phase_id: phase_a, input: "11", power: { name:  "11- Under Cabinet Power",          id: cir11, filters: [ *moving_avg ] } }
      - { phase_id: phase_a, input:  "8", power: { name:  "08- Back Room Power",              id:  cir8, filters: [ *moving_avg ] } }

      - { phase_id: phase_b, input:  "1", power: { name:  "01- EV Charger(a)",                id:  cir1, filters: [ *invert, *moving_avg ] } }
      - { phase_id: phase_b, input:  "2", power: { name:  "02- EV Charger(b)",                id:  cir2, filters: [ *moving_avg ] } }
      - { phase_id: phase_b, input:  "6", power: { name:  "06- Freezers",                     id:  cir6, filters: [ *invert, *moving_avg ] } }
      - { phase_id: phase_b, input:  "5", power: { name:  "05- Back Room MiniSplit",          id:  cir5, filters: [ *moving_avg ] } }
      - { phase_id: phase_b, input: "10", power: { name:  "10- Back Wall Power",              id: cir10, filters: [ *moving_avg ] } }
      
      
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: 10s
    id: total_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
```

The EV Charger is on the right leg (phase_b), but the top wire is returning a negative if I use phase_a or phase_b.  Similar issue with the Dining/Kitchen Minisplit.  Since its 2-pole I wasn't sure if they should be the same or not.
The Center Pole Power and the Freezers are throwing me though. They are single pole but return negative values using phase_a or phase_b. The other single pole breakers seems to be fine though.

"Phase L Power" and "Phase R Power" are reading from the big clips (A and B in my pic). I'm monitoring almost every breaker in the box, so the readings should be pretty close to what I have.  So what am I doing wrong?

I'm trying to get this one cleaned up since it's smaller, and way easier/safer to work in the panel.  Then I will apply it to the basement panel :D
