### DISCUSSION TITLE
Where is the update rate (240ms) specified or how was that determined?

### DISCUSSION THREAD

**Discussion by sofakng** [emporia-vue-local/esphome#333] [Q&A]
The README says that new samples are captured every 0.24 seconds (ie. 240ms).

Does the Emporia Vue push these updates to the ESP32 or are they polled?

Has anybody confirmed the update rate is the same on the Vue 3 and the Vue 2?

**Comment by jamesphw** [comment]
I would also like to know. And know how to adjust the publishing to HA. The 240ms is generating far too much data in HA, and slows down loading graphs and history.

I thought it was controlled with the filtering. But I have this throttle_avg filter defined:

```
.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s

```
The filter is used on the main phase definitions:

`voltage:
      name: "Phase A Voltage"
      filters: [*throttle_avg, *pos]`

I also use it on the publishing for each value:

`  - { platform: copy, name: "Phase A Power", source_id: phase_a_power, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_power }`

But it's still publishing the data to HA multiple times per second....

**Reply by flaviut** [reply]
![2025-02-21_19-14_1](https://github.com/user-attachments/assets/ada8616e-73ae-49b8-9af4-f9cded9765cb)
![2025-02-21_19-14](https://github.com/user-attachments/assets/c97f9aa8-b36b-4e45-b4d6-51635df8544f)

the throttling is working for me.

**Reply by jamesphw** [reply]
@flaviut Could you share your config YAML? I'm scratching my head why it doesnt work for me.

**Reply by flaviut** [reply]
my config is almost exactly the same as the one in the readme. Are you recompiling and uploading your configuration after each change? How are you checking the push interval?

```
esphome:
  name: emporiavue2

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components: [ emporia_vue ]

esp32:
  board: d-duino-32
  framework:
    type: esp-idf
    version: recommended

<<: !include _base.yaml

logger:
  logs:
    sensor: INFO

output:
  - platform: ledc
    pin: GPIO12
    id: buzzer
  - platform: gpio
    pin: GPIO27
    id: buzzer_gnd

rtttl:
  output: buzzer
  on_finished_playback:
    - logger.log: 'Song ended!'

button:
  - platform: template
    name: "Two Beeps"
    on_press:
      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

light:
  - platform: status_led
    name: "D3_LED"
    pin: 23
    restore_mode: ALWAYS_ON
    entity_category: config

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 400kHz  # recommended range is 50-200kHz
  timeout: 1ms
  id: i2c_a

time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_power
          filters: [*pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          filters: [*pos]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { id:  cir1, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "2", power: { id:  cir2, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "3", power: { id:  cir3, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "4", power: { id:  cir4, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "5", power: { id:  cir5, filters: [ *pos, multiply: 1.7333 ] } }
      - { phase_id: phase_a, input:  "6", power: { id:  cir6, filters: [ *pos, multiply: 1.7333 ] } }
      - { phase_id: phase_a, input:  "7", power: { id:  cir7, filters: [ *pos, multiply: 1.7333 ] } }
      - { phase_id: phase_b, input:  "8", power: { id:  cir8, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "9", power: { id:  cir9, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "10", power: { id: cir10, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "11", power: { id: cir11, filters: [ *pos, multiply: 1.7333 ] } }
      - { phase_id: phase_a, input: "12", power: { id: cir12, filters: [ *pos, multiply: 1.7333 ] } }
      - { phase_id: phase_a, input: "13", power: { id: cir13, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "14", power: { id: cir14, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "15", power: { id: cir15, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "16", power: { id: cir16, filters: [ *pos ] } }
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power
  - { platform: copy, name: "Phase A Power", source_id: phase_a_power, filters: *throttle_avg }
  - { platform: copy, name: "Phase B Power", source_id: phase_b_power, filters: *throttle_avg }
  - { platform: copy, name: "Total Power", source_id: total_power, filters: *throttle_avg }
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 1 Power", source_id:  cir1, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 2 Power", source_id:  cir2, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 3 Power", source_id:  cir3, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 4 Power", source_id:  cir4, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 5 Power", source_id:  cir5, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 6 Power", source_id:  cir6, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 7 Power", source_id:  cir7, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 8 Power", source_id:  cir8, filters: *throttle_avg }
  - { platform: copy, name:  "Circuit 9 Power", source_id:  cir9, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 10 Power", source_id: cir10, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 11 Power", source_id: cir11, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 12 Power", source_id: cir12, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 13 Power", source_id: cir13, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 14 Power", source_id: cir14, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 15 Power", source_id: cir15, filters: *throttle_avg }
  - { platform: copy, name: "Circuit 16 Power", source_id: cir16, filters: *throttle_avg }
  - platform: template
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
    filters: *throttle_time
  - platform: template
    lambda: !lambda |-
      return max(0.0f, id(total_power).state -
        id( cir1).state -
        id( cir2).state -
        id( cir3).state -
        id( cir4).state -
        id( cir5).state -
        id( cir6).state -
        id( cir7).state -
        id( cir8).state -
        id( cir9).state -
        id(cir10).state -
        id(cir11).state -
        id(cir12).state -
        id(cir13).state -
        id(cir14).state -
        id(cir15).state -
        id(cir16).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: balance_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Balance Daily Energy"
    power_id: balance_power
    accuracy_decimals: 0
    filters: *throttle_time
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 1 Daily Energy", filters: *throttle_time }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 2 Daily Energy", filters: *throttle_time }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 3 Daily Energy", filters: *throttle_time }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 4 Daily Energy", filters: *throttle_time }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 5 Daily Energy", filters: *throttle_time }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 6 Daily Energy", filters: *throttle_time }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 7 Daily Energy", filters: *throttle_time }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 8 Daily Energy", filters: *throttle_time }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "Circuit 9 Daily Energy", filters: *throttle_time }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 10 Daily Energy", filters: *throttle_time }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 11 Daily Energy", filters: *throttle_time }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 12 Daily Energy", filters: *throttle_time }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 13 Daily Energy", filters: *throttle_time }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 14 Daily Energy", filters: *throttle_time }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 15 Daily Energy", filters: *throttle_time }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "Circuit 16 Daily Energy", filters: *throttle_time }
```

**Reply by jamesphw** [reply]
I'm installing via ESPHome Builder in HA. The update frequency is fine on my Vue 2, it's just the Vue 3 that does this. 

In HA history, there is a value recorded every second. If I use a card to view the real-time value on the front end, it updates multiple times per second. But as far as I can see I'm using the throttle_filter exactly the same as you! 

```
substitutions:
  name: emporiavue3
  friendly_name: emporia vue3
  area: "Home"

  # Circuit Labels used for publishing to Home Assistant
  circuit_1:  "Heat Pump"
  circuit_2:  "Dryer"
  circuit_3:  "Basement Fridge"
  circuit_4:  "Upstairs Cooktop"
  circuit_5:  "Upstairs Oven"
  circuit_6:  "Kitchen West A"
  circuit_7:  "Upstairs Kitchen Microwave"
  circuit_8:  "Washer"
  circuit_9:  "James Office"
  circuit_10: "Furnace Rm 20"
  circuit_11: "Furnace Rm 15"
  circuit_12: "Baby Rm Kitchen Lights Under Stairs"
  circuit_13: "Furnace Blower"
  circuit_14: "TV Room"
  circuit_15: "Upstairs Fridge"
  circuit_16: "Living and Front"

  # Icons for Home Assistant
  icon_circuit: "mdi:power-plug"
  icon_current: "mdi:current-ac"
  icon_meter:   "mdi:meter-electric"
  icon_phase:   "mdi:angle-acute"
  icon_power:   "mdi:transmission-tower-import"
  icon_voltage: "mdi:transmission-tower"


esphome:
  name: ${name}
  area: ${area}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

external_components:
  # Update for Vue 3
  - source: github://emporia-vue-local/esphome@vue3
    components:
      - emporia_vue
      
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

preferences:
  # the default of 1min is far too short--flash chip is rated
  # for approx 100k writes.
  flash_write_interval: "48h"   

logger:
  logs:
    sensor: INFO

api:
  encryption:
    key: "REMOVED"

safe_mode:
  disabled: false

ota:
  platform: esphome
  password: "REMOVED"

wifi:
  # Wifi credentials are stored securely by new device wizard.
  ssid: "REMOVED"
  password: !secret wifi_password
  on_connect:
    - light.turn_on: wifi_led
  on_disconnect:
    - light.turn_off: wifi_led

  ap: 
    ssid: "emporiaVue3"
    password: "emporiaVue3"

#ethernet:
#  type: RTL8201
#  mdc_pin: GPIO32
#  mdio_pin: GPIO33
#  clk_mode: GPIO0_IN
  # Optional manual IP
#  manual_ip:
#    static_ip: x.x.x.x
#    gateway: x.x.x.x
#    subnet: 255.255.255.0

#text_sensor:
#  - platform: ethernet_info
#    ip_address:
#      name: ESP IP Address
#    dns_address:
#      name: ESP DNS Address
#    mac_address:
#      name: ESP MAC Address

# Enable Web server.
web_server:
  port: 80

captive_portal:

i2c:
  sda: 5
  scl: 18
  scan: false
  frequency: 400kHz  # recommended range is 50-200kHz
  timeout: 1ms
  id: i2c_a

time:
  #- platform: sntp
  #  id: sntp_time    
  - platform: homeassistant

# Configure the two status LEDs on the Emporia Vue v3 case
# https://github.com/emporia-vue-local/esphome/discussions/264#discussioncomment-9788390
light:
  - platform: status_led
    #name: "D3_LED"
    id: wifi_led
    #pin: 2
    pin:
      number: 2
      ignore_strapping_warning: true
    restore_mode: ALWAYS_OFF
    #entity_category: config
  - platform: status_led
    #name: "D31_LED"
    id: ethernet_led
    pin: 4
    restore_mode: ALWAYS_OFF
    #entity_category: config

# The restart button platform allows you to restart your node remotely through Home Assistant.
button:
  - platform: restart
    name: Restart
    id: restart_button
    icon: mdi:restart

  - platform: safe_mode
    name: Restart (Safe Mode)
    id: safe_mode_button
    icon: mdi:restart-alert

# Using button above instead switch
#switch:
#  - platform: restart
#    name: Restart  

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  # throttle_avg - emporia-vue-local
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s

  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'
  - &zero
    # Use for disconnected circuits to return 0
    lambda: "return 0.0f;"
  - &double
    # Use to double the measurement for 240V breakers
    multiply: 2

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      # Verify that this specific phase/leg is connected to correct input wire color on device listed below
      - id: phase_a
        # Vue device wire color
        input: BLACK
        # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        calibration: 0.01916
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      # Verify that this specific phase/leg is connected to correct input wire color on device listed below
      - id: phase_b
        # Vue device wire color
        input: RED
        # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        calibration: 0.01912
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # These non-throttled power sensors are used for accurately calculating energy.
      # Copy sensors defined later will filter and then send power measurements to Home Assistant.

      # Main Service CT Clamps (up to 3)
      # Verify the correct input on the device is connected to the CT clamp phase defined (Vue 3 inputs are inverted)
      - { input: "A", phase_id: phase_a, power: { id: phase_a_power, filters: *pos } }
      - { input: "B", phase_id: phase_b, power: { id: phase_b_power, filters: *pos } }
      # - { input: "C", phase_id: phase_c, power: { id: phase_c_power, filters: *invert } }

      # Circuit CT Clamps (up to 16)
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      # Use *abs filter to always take the positive absolute value
      # Use *invert filter for inverted positive values (Vue 3 inputs are inverted) or *zero for un-used inputs
      # Use *double filter for double (240v) breakers (this will assume power is evenly divided between the two legs)
      # example for double breaker
      #- { phase_id: phase_a, input: "9", power: { name: "Breaker 2a", id: circuit_9, filters: [ *moving_avg, *invert, multiply: 2 ] } }
      # example for phase b
      #- { phase_id: phase_b, input: "10", power: { name: "Breaker 2b - XYZ", id: circuit_10, filters: [ *moving_avg, *invert ] } }
      - { input: "1",  phase_id: phase_a, power: { id: c1_pwr,  filters: [ *invert, multiply: 2 ] }, current: { id: c1_cur } }
      - { input: "2",  phase_id: phase_b, power: { id: c2_pwr,  filters: [ *invert, multiply: 2 ] }, current: { id: c2_cur } }
      - { input: "3",  phase_id: phase_a, power: { id: c3_pwr,  filters: [ *invert ] }, current: { id: c3_cur } }
      - { input: "4",  phase_id: phase_a, power: { id: c4_pwr,  filters: [ *invert, multiply: 2 ] }, current: { id: c4_cur } }
      - { input: "5",  phase_id: phase_a, power: { id: c5_pwr,  filters: [ *invert, multiply: 2 ] }, current: { id: c5_cur } }
      - { input: "6",  phase_id: phase_a, power: { id: c6_pwr,  filters: [ *invert ] }, current: { id: c6_cur } }
      - { input: "7",  phase_id: phase_b, power: { id: c7_pwr,  filters: [ *invert ] }, current: { id: c7_cur } }
      - { input: "8",  phase_id: phase_b, power: { id: c8_pwr,  filters: [ *invert ] }, current: { id: c8_cur } }
      - { input: "9",  phase_id: phase_a, power: { id: c9_pwr,  filters: [ *invert ]}, current: { id: c9_cur } }
      - { input: "10", phase_id: phase_a, power: { id: c10_pwr, filters: [ *invert ]}, current: { id: c10_cur } }
      - { input: "11", phase_id: phase_a, power: { id: c11_pwr, filters: [ *invert ]}, current: { id: c11_cur } }
      - { input: "12", phase_id: phase_a, power: { id: c12_pwr, filters: [ *invert ]}, current: { id: c12_cur } }
      - { input: "13", phase_id: phase_b, power: { id: c13_pwr, filters: [ *invert ]}, current: { id: c13_cur } }
      - { input: "14", phase_id: phase_b, power: { id: c14_pwr, filters: [ *invert ]}, current: { id: c14_cur } }
      - { input: "15", phase_id: phase_b, power: { id: c15_pwr, filters: [ *invert ]}, current: { id: c15_cur } }
      - { input: "16", phase_id: phase_b, power: { id: c16_pwr, filters: [ *invert ]}, current: { id: c16_cur } }
    # Update total power and balance power readings at the same time.
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power

      
  # The total power sensor will be updated after all power sensors update via on_update trigger.
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    id: total_power
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  # The balance power sensor will be updated after all power sensors update via on_update trigger.
  - platform: template
    id: balance_power
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    lambda: !lambda |-
      return max(0.0f, id(total_power).state
        - id( c1_pwr).state
        - id( c2_pwr).state
        - id( c3_pwr).state
        - id( c4_pwr).state
        - id( c5_pwr).state
        - id( c6_pwr).state
        - id( c7_pwr).state
        - id( c8_pwr).state
        - id( c9_pwr).state
        - id(c10_pwr).state
        - id(c11_pwr).state
        - id(c12_pwr).state
        - id(c13_pwr).state
        - id(c14_pwr).state
        - id(c15_pwr).state
        - id(c16_pwr).state
      );

  # Copy sensors to publish the each power state to Home Assistant.
  - { platform: copy, name: "Phase A Power", source_id: phase_a_power, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Phase B Power", source_id: phase_b_power, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Total Power",   source_id: total_power,   filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "${circuit_1} Power",  source_id: c1_pwr,  filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_2} Power",  source_id: c2_pwr,  filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_3} Power",  source_id: c3_pwr,  filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_4} Power",  source_id: c4_pwr,  filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_5} Power",  source_id: c5_pwr,  filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_6} Power",  source_id: c6_pwr,  filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_7} Power",  source_id: c7_pwr,  filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_8} Power",  source_id: c8_pwr,  filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_9} Power",  source_id: c9_pwr,  filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_10} Power", source_id: c10_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_11} Power", source_id: c11_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_12} Power", source_id: c12_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_13} Power", source_id: c13_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_14} Power", source_id: c14_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_15} Power", source_id: c15_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_16} Power", source_id: c16_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }

  # Copy sensors to publish the each current state to Home Assistant.
  - { platform: copy, name: "${circuit_1} Current",  source_id: c1_cur,  filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_2} Current",  source_id: c2_cur,  filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_3} Current",  source_id: c3_cur,  filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_4} Current",  source_id: c4_cur,  filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_5} Current",  source_id: c5_cur,  filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_6} Current",  source_id: c6_cur,  filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_7} Current",  source_id: c7_cur,  filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_8} Current",  source_id: c8_cur,  filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_9} Current",  source_id: c9_cur,  filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_10} Current", source_id: c10_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_11} Current", source_id: c11_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_12} Current", source_id: c12_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_13} Current", source_id: c13_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_14} Current", source_id: c14_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_15} Current", source_id: c15_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_16} Current", source_id: c16_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }

  # The total daily energy sensors to be published to Home Assistant
  - { platform: total_daily_energy, name: "Total Daily Energy", power_id: total_power,     filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "Balance Daily Energy", power_id: balance_power, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_1} Daily Energy",  power_id: c1_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_2} Daily Energy",  power_id: c2_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_3} Daily Energy",  power_id: c3_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_4} Daily Energy",  power_id: c4_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_5} Daily Energy",  power_id: c5_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_6} Daily Energy",  power_id: c6_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_7} Daily Energy",  power_id: c7_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_8} Daily Energy",  power_id: c8_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_9} Daily Energy",  power_id: c9_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_10} Daily Energy", power_id: c10_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_11} Daily Energy", power_id: c11_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_12} Daily Energy", power_id: c12_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_13} Daily Energy", power_id: c13_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_14} Daily Energy", power_id: c14_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_15} Daily Energy", power_id: c15_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_16} Daily Energy", power_id: c16_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }

```

**Reply by flaviut** [reply]
Try pressing the "Clean Build Files" button and re-uploading. This part of the logic and hardware is identical for the Vue 2 or Vue 3, so it shouldn't matter.

**Reply by jamesphw** [reply]
I never did figure this out (cleaning build files didn't help). It's like the copy platform ignores the filters entirely.

What I did as a workaround is simply add a filter to the Total Power template, and that works correctly to throttle the values sent to HA:

```
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    id: total_power
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    filters: 
      - throttle_average: 2s
```
