### DISCUSSION TITLE
"Component took a long time for an operation" warning on Vue Gen3

### DISCUSSION THREAD

**Discussion by shull49** [emporia-vue-local/esphome#334] [Q&A] [answered]
I got my YAML looking nice, and everything is reading correctly, but I am now getting this warning:
[13:38:01][W][component:237]: Component emporia_vue.sensor took a long time for an operation (74 ms).
[13:38:01][W][component:238]: Components should block for at most 30 ms.

I was getting it last night when I removed the filters from all my circuits, but when I added them all back it went away.

Any thoughts?  Add moving_avg to the phase ct_clamps?

```
#GARAGE ELECTRICAL PANEL

substitutions:

  name: emporiavue-1
  friendly_name: Garage Panel

  circuit_1:  "EV Charger(a)"
  circuit_2:  "EV Charger(b)"
  circuit_3:  "Kitchen/Dining MiniSplit(b)"
  circuit_4:  "Kitchen/Dining MiniSplit(a)"
  circuit_5:  "Back Room MiniSplit"
  circuit_6:  "Freezer"
  circuit_7:  "Center Pole"
  circuit_8:  "Back Roomr"
  circuit_9:  "Ceiling Outlet"
  circuit_10: "Back Wall"
  circuit_11: "Under Cabinet"


  # Icons for Home Assistant
  icon_circuit: "mdi:power-plug"
  icon_current: "mdi:current-ac"
  icon_meter:   "mdi:meter-electric"
  icon_phase:   "mdi:angle-acute"
  icon_power:   "mdi:transmission-tower-import"
  icon_voltage: "mdi:transmission-tower"


esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false  

external_components:
#  - source: github://emporia-vue-local/esphome@dev
  - source: github://digiblur/esphome-vue3@dev
    components:
      - emporia_vue
      
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

preferences:
  # the default of 1min is far too short--flash chip is rated
  # for approx 100k writes.
  flash_write_interval: "48h"   

light:
  - platform: status_led
    id: wifi_led
    pin:
      number: 2
      ignore_strapping_warning: true
    restore_mode: ALWAYS_ON
    #entity_category: config
  - platform: status_led
    id: ethernet_led
    pin: 4
    restore_mode: ALWAYS_OFF
    #entity_category: config

api:
ota:
  platform: esphome

logger:
  logs:
    sensor: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: 

captive_portal:

i2c:
  sda: 5
  scl: 18
  scan: false
  frequency: 400kHz  # recommended range is 50-200kHz, was 200kHz but 150kHz stops errors (2024.8)
  timeout: 1ms
  id: i2c_a

switch:
  - platform: restart
    name: Restart  

#time:
#  - platform: sntp
#    id: sntp_time
time:
  - platform: homeassistant
# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  # throttle_avg - emporia-vue-local
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s  
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 2.88 seconds
      window_size: 24
      # we push a new value every 1.44 seconds
      send_every: 12
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'
  - &zero
    # Use for disconnected circuits to return 0
    lambda: "return 0.0f;"
  - &double
    # Use to double the measurement for 240V breakers
    multiply: 2

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase is connected to correct Vue device wire color
        input: RED  # Vue device wire color
        calibration: 0.0194  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [ *moving_avg, *pos ]
        phase_angle:
          name: "Phase A Phase Angle"
          filters: [*moving_avg, *pos]

      - id: phase_b  # Verify that this specific phase is connected to correct Vue device wire color
        input: BLACK  # Vue device wire color
        calibration: 0.0194  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [ *moving_avg, *pos ]
        frequency:
          name: "Phase B Frequency"
          filters: [*moving_avg, *pos]

    
    # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
    # These non-throttled power sensors are used for accurately calculating energy.
    # Copy sensors defined later will filter and then send power measurements to Home Assistant.
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
#          name: "Phase A Power"
          id: phase_a_power
#          device_class: power  
          filters: [*pos]
        current:
          id: phase_a_current
      
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
#          name: "Phase B Power"
          id: phase_b_power
#          device_class: power
          filters: [*pos]
        current:
          id: phase_b_current

      
      # Circuit CT Clamps (up to 16)
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      # Use *abs filter to always take the positive absolute value
      # Use *invert filter for inverted positive values (Vue 3 inputs are inverted) or *zero for un-used inputs
      # Use *double filter for double (240v) breakers (this will assume power is evenly divided between the two legs)
      # example for double breaker
      #- { phase_id: phase_a, input: "9", power: { name: "Breaker 2a", id: circuit_9, filters: [ *moving_avg, *invert, multiply: 2 ] } }
      # example for phase b
      #- { phase_id: phase_b, input: "10", power: { name: "Breaker 2b - XYZ", id: circuit_10, filters: [ *moving_avg, *invert ] } }
      - { input: "1",  phase_id: phase_a, power: { id: c1_pwr,  filters: [ *abs ] }, current: { id: c1_cur,  filters: [ *abs ] } }
      - { input: "2",  phase_id: phase_b, power: { id: c2_pwr,  filters: [ *abs ] }, current: { id: c2_cur,  filters: [ *abs ] } } 
      - { input: "3",  phase_id: phase_b, power: { id: c3_pwr,  filters: [ *abs ] }, current: { id: c3_cur,  filters: [ *abs ] } } 
      - { input: "4",  phase_id: phase_a, power: { id: c4_pwr,  filters: [ *abs ] }, current: { id: c4_cur,  filters: [ *abs ] } } 
      - { input: "5",  phase_id: phase_b, power: { id: c5_pwr,  filters: [ *abs ] }, current: { id: c5_cur,  filters: [ *abs ] } } 
      - { input: "6",  phase_id: phase_a, power: { id: c6_pwr,  filters: [ *abs ] }, current: { id: c6_cur,  filters: [ *abs ] } } 
      - { input: "7",  phase_id: phase_a, power: { id: c7_pwr,  filters: [ *abs ] }, current: { id: c7_cur,  filters: [ *abs ] } } 
      - { input: "8",  phase_id: phase_b, power: { id: c8_pwr,  filters: [ *abs ] }, current: { id: c8_cur,  filters: [ *abs ] } } 
      - { input: "9",  phase_id: phase_a, power: { id: c9_pwr,  filters: [ *abs ] }, current: { id: c9_cur,  filters: [ *abs ] } } 
      - { input: "10", phase_id: phase_b, power: { id: c10_pwr, filters: [ *abs ] }, current: { id: c10_cur,  filters: [ *abs ] } } 
      - { input: "11", phase_id: phase_b, power: { id: c11_pwr, filters: [ *abs ] }, current: { id: c11_cur,  filters: [ *abs ] } }
#      - { input: "12", phase_id: phase_a, power: { id: c12_pwr, filters: [ *abs, *double ] }, current: { id: c12_cur, filters: [ *abs, *double ] } } 
#      - { input: "13", phase_id: phase_a, power: { id: c13_pwr, filters: [ *abs, *double ] }, current: { id: c13_cur, filters: [ *abs, *double ] } } 
#      - { input: "14", phase_id: phase_a, power: { id: c14_pwr, filters: [ *abs, *double ] }, current: { id: c14_cur, filters: [ *abs, *double ] } } 
#      - { input: "15", phase_id: phase_b, power: { id: c15_pwr, filters: [ *abs, *double ] }, current: { id: c15_cur, filters: [ *abs, *double ] } } 
#      - { input: "16", phase_id: phase_b, power: { id: c16_pwr, filters: [ *abs, *double ] }, current: { id: c16_cur, filters: [ *abs, *double ] } } 
      
    # Update total power and balance power readings at the same time.
    on_update:
      then:
        - component.update: ev_charger_power
        - component.update: kitchen_minisplit
        - component.update: balance_power
        - component.update: total_power
        - component.update: total_current
        

###########################
#
# Combined Entities
#
###########################
  - platform: template
    name: "EV Charger"
    id: ev_charger_power
    lambda: return id(c1_pwr).state + id(c2_pwr).state;
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  - platform: template
    name: "Kitchen/Dining MiniSplit"
    id: kitchen_minisplit
    lambda: return id(c3_pwr).state + id(c4_pwr).state;
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

    
###########################
#
# Entities for Total Power
#
###########################  
  - platform: template
    name: "Total Power"
    id: total_power
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  - platform: template
    name: "Total Current"
    id: total_current
    lambda: return id(phase_a_current).state + id(phase_b_current).state;
    update_interval: never
    device_class: current
    state_class: measurement
    unit_of_measurement: "A"

  - platform: template
    id: balance_power
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    lambda: !lambda |-
      return max(0.0f, id(total_power).state
        - id( c1_pwr).state
        - id( c2_pwr).state
        - id( c3_pwr).state
        - id( c4_pwr).state
        - id( c5_pwr).state
        - id( c6_pwr).state
        - id( c7_pwr).state
        - id( c8_pwr).state
        - id( c9_pwr).state
        - id(c10_pwr).state
        - id(c11_pwr).state
      );

  - platform: total_daily_energy
    name: "EV Charger Daily Energy"
    power_id: ev_charger_power
    accuracy_decimals: 0

  - platform: total_daily_energy
    name: "Kitchen/Dining MiniSplit Daily Energy"
    power_id: kitchen_minisplit
    accuracy_decimals: 0

  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0


 # Copy sensors to publish the each power state to Home Assistant.
  - { platform: copy, name: "Phase A Power", source_id: phase_a_power, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Phase B Power", source_id: phase_b_power, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Total Power",   source_id: total_power,   filters: *moving_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "EV Charger Power", source_id: ev_charger_power, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "Kitchen/Dining MiniSplit Power", source_id: kitchen_minisplit, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }


#  - { platform: copy, name: "${circuit_1} Power",  source_id: c1_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
#  - { platform: copy, name: "${circuit_2} Power",  source_id: c2_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
#  - { platform: copy, name: "${circuit_3} Power",  source_id: c3_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
#  - { platform: copy, name: "${circuit_4} Power",  source_id: c4_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_5} Power",  source_id: c5_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_6} Power",  source_id: c6_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_7} Power",  source_id: c7_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_8} Power",  source_id: c8_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_9} Power",  source_id: c9_pwr,  filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_10} Power", source_id: c10_pwr, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_11} Power", source_id: c11_pwr, filters: *moving_avg, accuracy_decimals: 0, icon: $icon_circuit }

  # Copy sensors to publish the each current state to Home Assistant.
  - { platform: copy, name: "Phase A Current", source_id: phase_a_current, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "Phase B Current", source_id: phase_b_current, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
#  - { platform: copy, name: "${circuit_1} Current",  source_id: c1_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
#  - { platform: copy, name: "${circuit_2} Current",  source_id: c2_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
#  - { platform: copy, name: "${circuit_3} Current",  source_id: c3_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
#  - { platform: copy, name: "${circuit_4} Current",  source_id: c4_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_5} Current",  source_id: c5_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_6} Current",  source_id: c6_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_7} Current",  source_id: c7_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_8} Current",  source_id: c8_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_9} Current",  source_id: c9_cur,  filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_10} Current", source_id: c10_cur, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_11} Current", source_id: c11_cur, filters: *moving_avg, accuracy_decimals: 1, icon: $icon_current }
  

  # The total daily energy sensors to be published to Home Assistant
  - { platform: total_daily_energy, name: "Total Daily Energy",                     power_id: total_power,        filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "Balance Daily Energy",                   power_id: balance_power,      filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "EV Charger Daily Energy",                power_id: ev_charger_power,   filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "Kitchen/Dining MiniSplit Daily Energy",  power_id: kitchen_minisplit,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }

#  - { platform: total_daily_energy, name: "${circuit_1} Daily Energy",  power_id: c1_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
#  - { platform: total_daily_energy, name: "${circuit_2} Daily Energy",  power_id: c2_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
#  - { platform: total_daily_energy, name: "${circuit_3} Daily Energy",  power_id: c3_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
#  - { platform: total_daily_energy, name: "${circuit_4} Daily Energy",  power_id: c4_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_5} Daily Energy",  power_id: c5_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_6} Daily Energy",  power_id: c6_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_7} Daily Energy",  power_id: c7_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_8} Daily Energy",  power_id: c8_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_9} Daily Energy",  power_id: c9_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_10} Daily Energy", power_id: c10_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_11} Daily Energy", power_id: c11_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }

```
