### DISCUSSION TITLE
Reporting current on mains?

### DISCUSSION THREAD

**Discussion by Erotemic** [emporia-vue-local/esphome#337] [Q&A] [answered]
Looking at example configs for the Vue3, I only see entities published to home assistant for total_power. I'm wondering if there is also way to get a current measurement on phase A and phase B, and then publish total current. (I suppose I could divide by volts, but I imagine the CT clamps are measuring this directly?).

Can I report and publish current for the 200A CT clamps on the mains like I can with the smaller 50A CT clamps on individual panel slots?

Or more generally, is there some list of all possible direct sensor readings I can take and report to home assistant?

I also noticed the YAML editor say that some measurements are only supported for BLACK or RED wires on the mains. I was wondering why that is.

**Comment by Erotemic** [comment]
I took steps towards trying to figure this out myself. But I'm getting weird results. 

I noticed that each 50A ct-clamp input has both a power and current entry (each containing an id) corresponding to a later entry in the config that published to HA. I saw the current entry in the entry for the main service ct clamps was not there, so I added it. 

In the `sensor[0].ct_clamps` section I changed the config for the main CT clamp from:

```yaml
      - { input: "A", phase_id: phase_a, power: { id: phase_a_power, filters: *pos }}
      - { input: "B", phase_id: phase_b, power: { id: phase_b_power, filters: *invert }}  # Dont know why this is inverted, but it seems to work.
```

to 

```yaml
      - { input: "A", phase_id: phase_a, power: { id: phase_a_power, filters: *pos }, current: { id: phase_a_cur } }
      - { input: "B", phase_id: phase_b, power: { id: phase_b_power, filters: *invert }, current: { id: phase_b_cur } }  # Dont know why this is inverted, but it seems to work.
```

And then later on in the `sensor` list, I added:

```
  - { platform: copy, name: "Phase A Left Current", source_id: phase_a_cur, filters: *throttle_avg, accuracy_decimals: 2, icon: $icon_current }
  - { platform: copy, name: "Phase B Right Current", source_id: phase_b_cur, filters: *throttle_avg, accuracy_decimals: 2, icon: $icon_current }
```

This did create an entity in HA, but the reported values on the left and right mains are far too low. I'm getting 1.02A on PhaseA main and 1.53A on PhaseB main, but individual circuits have amp readings of 2.42, 3.10, 1.77, and a bunch of lower numbers. So this clearly isn't correct.

**Reply by Erotemic** [reply]
I was able to get something reasonably by computing the current via the voltage and the power. This required adding an "id" to the properties of each sensor phase:

```yaml
      - id: phase_a
        input: RED
        calibration: 0.01916
        voltage:
          id: 'phase_a_voltage'   # << ADD THIS
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        phase_angle:
          name: "Phase A Phase Angle"
          filters: [*throttle_avg, *pos]
      - id: phase_b
        input: BLACK
        calibration: 0.01916
        voltage:
          id: 'phase_b_voltage'   # << ADD THIS
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase B Frequency"
          filters: [*throttle_avg, *pos]
```

And then modifying on_update:

```yaml
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power
        - component.update: phase_a_cur
        - component.update: phase_b_cur
        - component.update: total_cur
        - component.update: balance_cur
```

Defining templates:

```yaml
  - platform: template
    lambda: return id(phase_a_power).state / id(phase_a_voltage).state;
    id: phase_a_cur
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "A"

  - platform: template
    lambda: return id(phase_b_power).state / id(phase_b_voltage).state;
    id: phase_b_cur
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "A"

  - platform: template
    lambda: return id(phase_a_cur).state + id(phase_b_cur).state;
    id: total_cur
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "A"

  - platform: template
    id: balance_cur
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "A"
    lambda: !lambda |-
      return max(0.0f, id(total_cur).state
        - id( c1_cur).state
        - id( c2_cur).state
        - id( c3_cur).state
        - id( c4_cur).state
        - id( c5_cur).state
        - id( c6_cur).state
        - id( c7_cur).state
        - id( c8_cur).state
        - id( c9_cur).state
        - id(c10_cur).state
        - id(c11_cur).state
        - id(c12_cur).state
        - id(c13_cur).state
        - id(c14_cur).state
        - id(c15_cur).state
        - id(c16_cur).state
      );
```

And then publishing values:

```
  - { platform: copy, name: "Total Current", source_id: total_cur, filters: [], accuracy_decimals: 2, icon: $icon_current }
  - { platform: copy, name: "Balance Current", source_id: balance_cur, filters: [], accuracy_decimals: 2, icon: $icon_current }

  - { platform: copy, name: "Phase A Current", source_id: phase_a_cur, filters: [], accuracy_decimals: 2, icon: $icon_current }
  - { platform: copy, name: "Phase A Voltage", source_id: phase_a_voltage, filters: [], accuracy_decimals: 2, icon: $icon_voltage }

  - { platform: copy, name: "Phase B Current", source_id: phase_b_cur, filters: [], accuracy_decimals: 2, icon: $icon_current }
  - { platform: copy, name: "Phase B Voltage", source_id: phase_b_voltage, filters: [], accuracy_decimals: 2, icon: $icon_voltage }
```

I'd still like to know why the `phase_a_cur_raw` measurements didn't work, but at least this workaround works for now.

**Reply by Erotemic** [reply]
I should note that it looks like the "balance current" doesn't work out to a postive number. I'm guessing this has to do with either a misconfiguration on my end, noise in the system, or reactive power (which I don't really understand well enough). Perhaps it is a fools errand to measure things in terms of amps.

**Reply by maxromanovsky** [reply]
I have also just today tried adding current.
`231 V` * `0.19 A` = `43.89 W` is far too much for `6.5 W` (also reported by Emporia) light bulb. Clamp amper meter measures `0.034 A` = `7.854 W` (not very precise), but much closer.
Light bulb is rated for `6.3 W`, so Emporia is spot on!

@flaviut is `current` measurement accurate?

**Reply by flaviut** [reply, marked as answer]
Current measurement is completely wrong for unknown reasons. Nothing can be done about it—it's just how the firmware reports the data, it is not a bug.

I would suggest using template sensors to divide by voltage if you need current for your application.

**Comment by maxromanovsky** [comment]
I think this is the answer by @flaviut : https://github.com/emporia-vue-local/esphome/discussions/337#discussioncomment-12519032

> Current measurement is completely wrong for unknown reasons. Nothing can be done about it—it's just how the firmware reports the data, it is not a bug.
>
> I would suggest using template sensors to divide by voltage if you need current for your application.

**Comment by alexruffell** [comment]
@Erotemic @flaviut - Multiply Phase A/B/C Current raw measurement * 4 to get the correct value.

I am pretty sure the issue is that all voltage inputs on the Emporia Vue have the same voltage range (likely 0-1V) but the CTs used for Phase A/B/C are 4x higher in max current (200A vs 50A for all other channels) which means that they output 4x lower voltage for the same measured amperage.

EDIT: I checked and the Emporia CTs appear to be of the 333mV at full scale variety. I am leaving the rest of the post as if they were the 1000mV type as the concept remains the same.

In other words....

A 50A CT will output 20mV for each 1A of current it measures (1000 / 50 = 20)
A 200A CT will output 5mV for each 1A of current it measures (1000 / 200 = 5)

So...

A 50A CT measuring 10A will output 200mV (10 * 20 = 200mV or 0.2V)
A 50A CT measuring 50A will output 1000mV (50 * 20 = 1000mV or 1V)

A 200A CT measuring 10A will output 50mV (10 * 5 = 50mV or 0.05V)
A 200A CT measuring 50A will output 250mV (50 * 5 = 250mV or 0.25V)
A 200A CT measuring 200A will output 1000mV (200 * 5 = 1000mV or 1V)

Given the Emporia Vue does NOT know what CT is connected, it is calculating all voltage inputs as if a 50A CT were connected. To correct this, just multiply by 4 any raw measurements from inputs where you connected a 200A CT.

A side effect of this setup is that your measurement using a 200A CT will be less accurate than a 50CT when measuring 50A and below... Not getting into any details on this but for home energy monitoring it is likely trivial.

The YAML fix:

```
.defaultfilters:

  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  
  - &200a_ct
    # multiply by 4 to adjust for 200A CT (not needed for 50A CTs)
    multiply: 4.0

```


```
      - phase_id: phase_a
        input: "A" # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_power
          filters: [*pos]
        current:
          id: phase_a_current
          filters: [*200a_ct, *pos]

      - phase_id: phase_b
        input: "B" # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          filters: [*pos]
        current:
          id: phase_b_current
          filters: [*200a_ct, *pos]
```

I have Phase A & B connected to the same 120V circuit, and all clamps measuring the same current with a messy jig I setup. 
<img width="617" alt="image" src="https://github.com/user-attachments/assets/9b792e3e-758c-4c80-b876-f0620918bcb4" />
The reason I did this is to calibrate all inputs to show the same thing when measuring the same current/voltage. Also, this jig allows me to fake a 4x load simply by wrapping the same wire 4 times around the two lag screws (so the same wire/signal passes through the CTs 4 times). This allows me to use a 150W filament lightbulb and measure 600W, or a smaller bulb that I am using right now plugged into the outlet shown in the picture.

Unfortunately, for current measurements I can only reference a clamp meter as I don't have a CT probe for my benchtop DMM which is way more accurate.

The two voltage readings are as close as I can get them to the reading on my 5 1/2 digit benchtop DMM.
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/9b58b62f-b7ad-4719-8529-280eabd9ed2b" />

These are the readings I get right now... still going through the calibration process:
<img width="1914" alt="image" src="https://github.com/user-attachments/assets/c48fc330-88c4-4608-9e0c-e77ddb7cbe3d" />

Notice the "Summed Current" for A and B are wrong because it is just the sum of ch 1-8 and ch 9-16 respectively BUT all my CTs are measuring the same 1.7A, including the 200A CTs... Having corrected the issue with the 200A CTs, I just need to remove the template doing the sum.

There is also something wrong with the Energy readings as they increase way too fast...

**Reply by flaviut** [reply]
It's interesting that you need to multiply ABC by 4. [The code divides them by 4!](https://github.com/emporia-vue-local/esphome/commit/b0d1536acc18a9882b7871d4f9e3c753b3b61511)

Maybe this is a bug/oversight in the original Emporia code that has made it into this implementation? I don't think current readings are a feature of the Emporia app, or perhaps if they are, they fix up the numbers on their side.

**Reply by alexruffell** [reply]
@flaviut That is very strange... All CTs (50A and 200A) supplied with the Emporia Vue3 have an output of 333mV. In my testing it appears that all inputs (1 to 16 & A, B, C) are configured for the 50A:333mV ratio which results in the multiplier being needed wherever you use a 200A CT (x4 the current for same 333mV output). In other words, you can connect a 200CT to any input, but you need to multiply the reading by 4. Conversely, if you connect a 50A to A, B or C - you should get a correct reading without needing to multiply by 4.

In my test/cal rig shown above, I was measuring the current from the same wire on all inputs so the issue became obvious right away. All 1-16 inputs were reading ~1.7A, while the A, and B inputs were reading ~0.43A which is 1/4 of 1.7. The divide by 4 in the code would explain why if the input was designed for 200A:333mV and retroactively changed in code to make it a 50A input by default... buy why? Maybe to cater to regions in the world where 200A CTs are super overkill? 

The way it is currently set up, if you use a 50A CT, no multiplier/divider is needed, if you use a 100A  CT then multiply by 2, if 200A then multiply by 4, and so on. Of course you lose a bit of resolution but that is likely of secondary importance in this application.

Any chance that division can be made optional so the supplied 200A CTs can be used on A, B and C without requiring a multiplier? Had the hardware been designed for 50A, then multiplying by 4 would be necessary, but as it looks, dividing to just multiply it right back seems 'not ideal'.

<img width="323" alt="image" src="https://github.com/user-attachments/assets/39f60066-9bdb-4946-8c9a-39bbb64f3ff6" />

**Reply by flaviut** [reply]
> Any chance that division can be made optional so the supplied 200A CTs can be used on A, B and C without requiring a multiplier?

Can you make a pull request? Just completely remove it, no need to make it optional. I think you're the only one who's seriously looked into this.

**Reply by alexruffell** [reply]
@flaviut I wish I knew how to do it. Unfortunately I also lack the time to figure it out.

**Reply by madcatzfight** [reply]
It appears that this is due to the Vue 3 swapping the inputs on A and C.  See https://github.com/digiblur/esphome-vue3/pull/1

**Comment by ChestersGarage** [comment]
I've got accurate current on A and B with the 4x multiplier.  But C doesn't need it, and is accurate without.

```
external_components:
  - source: github://emporia-vue-local/esphome@vue3
 
.defaultfilters:
  - &200a_ct
    # multiply by 4 to adjust for 200A CT (ONLY for A and B inputs, not C nor 50A CTs)
    multiply: 4.0

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    ct_clamps:
...
      - phase_id: phase_a
        input: "A"
        current:
          id: l1_current
          name: "L1 Current"
          filters: [ *200a_ct ]
          accuracy_decimals: 3
        power:
          id: l1_power
          name: "L1 Power"
          filters: []
          accuracy_decimals: 3

      - phase_id: phase_b
        input: "B"
        current:
          id: l2_current
          name: "L2 Current"
          accuracy_decimals: 3
          filters: [ *200a_ct ]
        power:
          id: l2_power
          name: "L2 Power"
          accuracy_decimals: 3
          filters: []

      - phase_id: phase_c
        input: "C"
        current:
          id: neutral_current
          name: "N Current"
          accuracy_decimals: 3
          filters: []
```
