### DISCUSSION TITLE
Emporia Vue Gen 3 config - feedback needed

### DISCUSSION THREAD

**Discussion by maxromanovsky** [emporia-vue-local/esphome#339] [Q&A]
Dear community,

I've spent quite some time reading through the gen 3 thread https://github.com/emporia-vue-local/esphome/discussions/264, as well as few issues referenced there.
I have tried  to combine multiple best practices, tweaks, tips & tricks into a working config.

The config that I'm sharing is:
- for gen 3
- for wifi
- 3 phase EU installation
- 16 clamp sensors
- one 3 phase wall plug (pin 14-16)
- gets rid of pin strapping warnings
- gets rid of too frequent `Component emporia_vue.sensor took a long time for an operation` (only once a minute now)
- has current measurements commented out because they don't work: https://github.com/emporia-vue-local/esphome/discussions/337#discussioncomment-12519032 (but template instead of them is not implemented in this config)
- adds wifi connection data
- adds led signaling if wifi is connected
- hopefully reduces the flash wear

I am asking for your feedback, in particular:
- did I make any obvious mistakes that would lead to incorrect data?
- is this config writes to ESP32 flash as infrequently as possible?
- have I overcomplicated something?
- does everything follow the best practices?
- can something be implemented differently, in a more performant way?

```yaml
# This config is inspired by many code snippets and full configs on different discussion threads and PRs,
# but mainly by https://github.com/emporia-vue-local/esphome/discussions/264
# Config is for WiFi gen 3 3-phase EU installation
#
# All currency-related config is commented, but left in code
# https://github.com/emporia-vue-local/esphome/discussions/337#discussioncomment-12519032
# Current measurement is completely wrong for unknown reasons.
# Nothing can be done about it—it's just how the firmware reports the data, it is not a bug.
# I would suggest using template sensors to divide by voltage if you need current for your application.

substitutions:
  # https://github.com/emporia-vue-local/esphome/discussions/334
  socket_3phase_garage: "Socket garage 3-phase"

  circuit_01: "01"
  circuit_02: "02"
  circuit_03: "03"
  circuit_04: "04"
  circuit_05: "05"
  circuit_06: "06"
  circuit_07: "07"
  circuit_08: "08"
  circuit_09: "09"
  circuit_10: "10"
  circuit_11: "11"
  circuit_12: "12"
  circuit_13: "13"
  circuit_14: "14"
  circuit_15: "15"
  circuit_16: "16"


  # Icons for Home Assistant
  icon_circuit: "mdi:power-plug"
  # icon_current: "mdi:current-ac"
  icon_meter:   "mdi:meter-electric"
  icon_power:   "mdi:transmission-tower-import"

esphome:
  name: emporia-vue-3
  friendly_name: Emporia Vue 3

external_components:
  - source: github://emporia-vue-local/esphome@vue3
    components:
      - emporia_vue

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# https://github.com/emporia-vue-local/esphome/discussions/264?sort=old#discussioncomment-8894510
# ethernet:
#   type: RTL8201
#   mdc_pin: GPIO32
#   mdio_pin: GPIO33
#   clk_mode: GPIO0_IN

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_emporia_vue_3

ota:
  platform: esphome
  password: !secret ota_password
  on_error:
    then:
      - button.press: safe_mode_button

# Enable logging
logger:
  logs:
    # by default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - light.turn_on: wifi_led
  on_disconnect:
    - light.turn_off: wifi_led

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Emporia-Vue-3 Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:

preferences:
  # the default of 1min is far too short--flash chip is rated
  # for approx 100k writes.
  # please also make sure `restore: false` is set on all `platform: total_daily_energy`
  # sensors below.
  flash_write_interval: "48h"
    
i2c:
  sda:
    number: 5
    ignore_strapping_warning: true
  scl: 18
  scan: false
  frequency: 400kHz
  timeout: 1ms
  id: i2c_a

button:
  # https://github.com/emporia-vue-local/esphome/discussions/264?sort=old#discussioncomment-11621009
  - platform: restart
    name: Restart
    id: restart_button
    icon: mdi:restart

  - platform: safe_mode
    name: Restart (Safe Mode)
    id: safe_mode_button
    icon: mdi:restart-alert

time:
  # - platform: sntp
  #   id: sntp_time
  # https://esphome.io/components/time/homeassistant
  - platform: homeassistant

# https://github.com/emporia-vue-local/esphome/discussions/264?sort=old#discussioncomment-9788390
# Configure the two status LEDs on the Emporia Vue v3 case.
light:
  - platform: status_led
    id: wifi_led
    name: "WiFi LED"
    pin:
      number: 2
      ignore_strapping_warning: true
    entity_category: diagnostic
    restore_mode: ALWAYS_ON

  - platform: status_led
    id: ethernet_led
    name: "Ethernet LED"
    pin: 4
    entity_category: config
    restore_mode: ALWAYS_OFF

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once

# Using a throttle_average filter let's us specify a time to average over compared to the sliding window average that depends on knowing the update frequency, so it doesn't matter which revision Emporia Vue you have
# The raw power measurements are left as internal sensors with no throttle
# The total daily energy sensors use these internal sensors, and should accurately capture very fast changes in the power measurements
# Apply a time based throttle filter to the energy sensors so as to not publish updates too frequently; this sends the most recent value after the specified time has passed since last publishing
# Copy sensors publish the raw internal sensors and filter them with throttle_average
# The template total power and balance power sensors use the raw internal sensors as their source; this should improve accuracy as we are not averaging averages
# throttle_average filter is applied after combining the internal sensors to reduce publishing rates
# Adam Jaques wrote a great blog post that motivated using these filters with copy sensors to improve accuracy:
# https://www.technowizardry.net/2023/02/local-energy-monitoring-using-the-emporia-vue-2/

# The template total and balance power sensors now have an update_interval of never, and they are instead updated only via this trigger
# This let's us avoid having to specify a time based update_interval that relies on the hardware revision's internal update rate
# Having more accurate power sensors that update every time the Emporia hardware sends new measurements should improve the daily energy sensor's accuracy for total power and balance power
# This behaves much like the built in ESPHome automation trigger on_value. The on_update trigger is guaranteed to execute once after every individual sensor in the component has updated. This allows the template sensors to simultaneously update after all the internal power sensors have finished publishing new values. In contrast, the on_value trigger is executed after a specific individual sensor has updated.

.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 2.88 seconds
      window_size: 24
      # we push a new value every 1.44 seconds
      send_every: 12
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

# https://gist.github.com/bradsjm/c2562df0e891f26e27191a31d617d471
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "MAC Address"

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.0194  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.0194  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
      - id: phase_c  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLUE  # Vue device wire color
        calibration: 0.0194  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase C Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase C Phase Angle"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # Copy sensors will filter and then send power measurements to HA
      # These non-throttled power sensors are used for accurately calculating energy
      # See https://github.com/emporia-vue-local/esphome/pull/200
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_pwr
          filters: [*pos]
        # current:
        #   id: phase_a_curr
        #   filters: [*pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_pwr
          filters: [*pos]
        # current:
        #   id: phase_b_curr
        #   filters: [*pos]
      - phase_id: phase_c
        input: "C"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_c_pwr
          filters: [*pos]
        # current:
        #   id: phase_c_curr
        #   filters: [*pos]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: {id:  c1_pwr, filters: [ *pos ] }, current: {id:  c1_curr, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "2", power: {id:  c2_pwr, filters: [ *pos ] }, current: {id:  c2_curr, filters: [ *pos ] } }
      - { phase_id: phase_c, input:  "3", power: {id:  c3_pwr, filters: [ *pos ] }, current: {id:  c3_curr, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "4", power: {id:  c4_pwr, filters: [ *pos ] }, current: {id:  c4_curr, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "5", power: {id:  c5_pwr, filters: [ *pos ] }, current: {id:  c5_curr, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "6", power: {id:  c6_pwr, filters: [ *pos ] }, current: {id:  c6_curr, filters: [ *pos ] } }
      - { phase_id: phase_c, input:  "7", power: {id:  c7_pwr, filters: [ *pos ] }, current: {id:  c7_curr, filters: [ *pos ] } }
      - { phase_id: phase_b, input:  "8", power: {id:  c8_pwr, filters: [ *pos ] }, current: {id:  c8_curr, filters: [ *pos ] } }
      - { phase_id: phase_a, input:  "9", power: {id:  c9_pwr, filters: [ *pos ] }, current: {id:  c9_curr, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "10", power: {id: c10_pwr, filters: [ *pos ] }, current: {id: c10_curr, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "11", power: {id: c11_pwr, filters: [ *pos ] }, current: {id: c11_curr, filters: [ *pos ] } }
      - { phase_id: phase_c, input: "12", power: {id: c12_pwr, filters: [ *pos ] }, current: {id: c12_curr, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "13", power: {id: c13_pwr, filters: [ *pos ] }, current: {id: c13_curr, filters: [ *pos ] } }
      - { phase_id: phase_a, input: "14", power: {id: c14_pwr, filters: [ *pos ] }, current: {id: c14_curr, filters: [ *pos ] } }
      - { phase_id: phase_b, input: "15", power: {id: c15_pwr, filters: [ *pos ] }, current: {id: c15_curr, filters: [ *pos ] } }
      - { phase_id: phase_c, input: "16", power: {id: c16_pwr, filters: [ *pos ] }, current: {id: c16_curr, filters: [ *pos ] } }
    on_update:
      then:
        - component.update: total_power
        # - component.update: total_curr
        - component.update: balance_pwr
        # - component.update: balance_curr
        - component.update: socket_3phase_garage_pwr
        # - component.update: socket_3phase_garage_curr

  # Combined Entities

  - platform: template
    name: "${socket_3phase_garage} Power"
    id: socket_3phase_garage_pwr
    lambda: return id(c14_pwr).state + id(c15_pwr).state + id(c16_pwr).state;
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  # - platform: template
  #   name: "${socket_3phase_garage} Current"
  #   id: socket_3phase_garage_curr
  #   lambda: return id(c14_curr).state + id(c15_curr).state + id(c16_curr).state;
  #   update_interval: never
  #   device_class: current
  #   state_class: measurement
  #   unit_of_measurement: "A"

  # Entities for Total Power

  - platform: template
    lambda: return id(phase_a_pwr).state + id(phase_b_pwr).state + id(phase_c_pwr).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  # - platform: template
  #   name: "Total Current"
  #   id: total_curr
  #   lambda: return id(phase_a_curr).state + id(phase_b_curr).state + id(phase_c_curr).state;
  #   update_interval: never
  #   device_class: current
  #   state_class: measurement
  #   unit_of_measurement: "A"

  - platform: total_daily_energy
    name: "${socket_3phase_garage} Daily Energy"
    power_id: socket_3phase_garage_pwr
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time

  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time

  - platform: template
    lambda: !lambda |-
      return max(0.0f, id(total_power).state -
        id( c1_pwr).state -
        id( c2_pwr).state -
        id( c3_pwr).state -
        id( c4_pwr).state -
        id( c5_pwr).state -
        id( c6_pwr).state -
        id( c7_pwr).state -
        id( c8_pwr).state -
        id( c9_pwr).state -
        id(c10_pwr).state -
        id(c11_pwr).state -
        id(c12_pwr).state -
        id(c13_pwr).state -
        id(c14_pwr).state -
        id(c15_pwr).state -
        id(c16_pwr).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: balance_pwr
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"

  # - platform: template
  #   lambda: !lambda |-
  #     return max(0.0f, id(total_curr).state -
  #       id( c1_curr).state -
  #       id( c2_curr).state -
  #       id( c3_curr).state -
  #       id( c4_curr).state -
  #       id( c5_curr).state -
  #       id( c6_curr).state -
  #       id( c7_curr).state -
  #       id( c8_curr).state -
  #       id( c9_curr).state -
  #       id(c10_curr).state -
  #       id(c11_curr).state -
  #       id(c12_curr).state -
  #       id(c13_curr).state -
  #       id(c14_curr).state -
  #       id(c15_curr).state -
  #       id(c16_curr).state);
  #   update_interval: never   # will be updated after all power sensors update via on_update trigger
  #   id: balance_curr
  #   device_class: current
  #   state_class: measurement
  #   unit_of_measurement: "A"

  - platform: total_daily_energy
    name: "Balance Daily Energy"
    power_id: balance_pwr
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time

  # Copy sensors filter and send the power state to HA
  - { platform: copy, name:                       "Phase A Power", source_id:                 phase_a_pwr, filters: *throttle_avg, icon:   $icon_power }
  - { platform: copy, name:                       "Phase B Power", source_id:                 phase_b_pwr, filters: *throttle_avg, icon:   $icon_power }
  - { platform: copy, name:                       "Phase C Power", source_id:                 phase_c_pwr, filters: *throttle_avg, icon:   $icon_power }
  - { platform: copy, name:                         "Total Power", source_id:                 total_power, filters: *throttle_avg, icon:   $icon_power }
  - { platform: copy, name:                       "Balance Power", source_id:                 balance_pwr, filters: *throttle_avg, icon:   $icon_power }
  - { platform: copy, name:       "${socket_3phase_garage} Power", source_id:    socket_3phase_garage_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_01} Power", source_id:                      c1_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_02} Power", source_id:                      c2_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_03} Power", source_id:                      c3_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_04} Power", source_id:                      c4_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_05} Power", source_id:                      c5_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_06} Power", source_id:                      c6_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_07} Power", source_id:                      c7_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_08} Power", source_id:                      c8_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_09} Power", source_id:                      c9_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_10} Power", source_id:                     c10_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_11} Power", source_id:                     c11_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_12} Power", source_id:                     c12_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_13} Power", source_id:                     c13_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_14} Power", source_id:                     c14_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_15} Power", source_id:                     c15_pwr, filters: *throttle_avg, icon: $icon_circuit }
  - { platform: copy, name:                 "${circuit_16} Power", source_id:                     c16_pwr, filters: *throttle_avg, icon: $icon_circuit }


  # - { platform: copy, name:                       "Phase A Current", source_id:                 phase_a_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                       "Phase B Current", source_id:                 phase_b_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                       "Phase C Current", source_id:                 phase_c_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                         "Total Current", source_id:                   total_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                       "Balance Current", source_id:                 balance_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:       "${socket_3phase_garage} Current", source_id:    socket_3phase_garage_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_01} Current", source_id:                      c1_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_02} Current", source_id:                      c2_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_03} Current", source_id:                      c3_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_04} Current", source_id:                      c4_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_05} Current", source_id:                      c5_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_06} Current", source_id:                      c6_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_07} Current", source_id:                      c7_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_08} Current", source_id:                      c8_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_09} Current", source_id:                      c9_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_10} Current", source_id:                     c10_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_11} Current", source_id:                     c11_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_12} Current", source_id:                     c12_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_13} Current", source_id:                     c13_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_14} Current", source_id:                     c14_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_15} Current", source_id:                     c15_curr, filters: *throttle_avg, icon: $icon_current }
  # - { platform: copy, name:                 "${circuit_16} Current", source_id:                     c16_curr, filters: *throttle_avg, icon: $icon_current }


  - { power_id:  c1_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_01} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id:  c2_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_02} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id:  c3_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_03} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id:  c4_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_04} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id:  c5_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_05} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id:  c6_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_06} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id:  c7_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_07} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id:  c8_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_08} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id:  c9_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_09} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id: c10_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_10} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id: c11_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_11} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id: c12_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_12} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id: c13_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_13} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id: c14_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_14} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id: c15_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_15} Daily Energy", filters: *throttle_time, icon: $icon_meter }
  - { power_id: c16_pwr, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_16} Daily Energy", filters: *throttle_time, icon: $icon_meter }
```

**Comment by nad22** [comment]
Thank you very much ! This is the first complete config for a 3-Phase Installation i found. Just one Question. It seems, that my vue3 mixes the Phases oltough they are connected correctly (L1 to A, L2, to B, L3 to C, Null to White). Also the Main Clamps are connected right. Overall i do not get any of the Channels right even if i have assigned the phases like installed. I have to assign e.g. Phase 3 to a device which is physically wired to Phase 2 to get Power Values. But it is also not working for every Device,.. some of them get odd readings like 14 Watts where there should be 0,9Watts,.. Do you have any Idea ?Thanks in Advance !

**Reply by maxromanovsky** [reply]
@nad22 make sure you're using `vue3` branch:
```yaml
external_components:
  - source: github://emporia-vue-local/esphome@vue3
    components:
      - emporia_vue
```
