### DISCUSSION TITLE
240V items reading low?

### DISCUSSION THREAD

**Discussion by steckrca** [emporia-vue-local/esphome#343] [General]
I'm beating my head against a wall here.  Sorry if my terminology isn't correct on some things, I'm no electrician.

My air conditioner outside unit (condenser) is reading what I believe to be way low.  When running, based on specs (12.7A @ 240V) it should be somewhere in the neighborhood of 3000W, but it's only showing 1650W (rounded).  I have a multiplier of 2 on the CT definition.  For all of my 240V items, I am running a clamp only on the A phase.  Other items with 2 multipliers, i.e. range, water heater, dryer, etc. seem correct--range pulls roughly 3600W when on, dryer nearly 6000W when on.  

Side question - are current values still not to be trusted?  AC condenser current reported is 13.9A, *120V = 1668W which is strangely close to the 1629.9W reported by the Vue.  It's like the multiplier isn't multiplying.

**Comment by flaviut** [comment]
Can you post your config, [wrapped in a code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)? These sorts of things are often something really simple that some fresh eyes can catch.

For your situation, I wouldn't be surprised if the issue is unbalanced load between the two phases. Most folks use resistive heating for those other things you listed. That's the most basic and easy-to-understand type of load. ACs, especially depending on the specific model, are more complicated and can draw load unevenly between the two poles. There's more details here: https://github.com/emporia-vue-local/esphome/discussions/55 

> are current values still not to be trusted?

Correct, current values can't be trusted. I don't think that'll ever change.

**Comment by steckrca** [comment]
Here you go.  It might be a little messy.

```
esphome:
  name: emporiavue2
  friendly_name: vue2

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components:
      - emporia_vue
substitutions:
  circuit_1: "Air Handler"
  circuit_2:  "Range"
  circuit_3:  "Water Heater"
  circuit_4:  "Master BR"
  circuit_5:  "BR+Office"
  circuit_6:  "Garage"
  circuit_7:  "30A"
  circuit_8:  "AC"
  circuit_9:  "Dryer"
  circuit_10: "Kitchen GFI-1"
  circuit_11: "Bathroom GFI"
  circuit_12: "Washer/Network"
  circuit_13: "Dishwasher"
  circuit_14: "Fridge"
  circuit_15: "Dining Room"
  circuit_16: "Kitchen GFI-2"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable Home Assistant API
api:[REDACTED]

  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

ota:[REDACTED]
  
# Enable logging
logger:
  logs:
    # by default, every reading will be printed to the UART, which is very slow
    # This will disable printing the readings but keep other helpful messages
    sensor: INFO

wifi:[REDACTED]

preferences:
  # please also make sure `restore: false` is set on all `platform: total_daily_energy`
  # sensors below.
  flash_write_interval: "48h"

output:
  - platform: ledc
    pin: GPIO12
    id: buzzer
  - platform: gpio
    pin: GPIO27
    id: buzzer_gnd

rtttl:
  output: buzzer
  on_finished_playback:
    - logger.log: 'Song ended!'

#button:
#  - platform: template
#    name: "Two Beeps"
#    on_press:
#      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

light:
  - platform: status_led
    name: "D3_LED"
    pin: 23
    restore_mode: ALWAYS_ON
    entity_category: config

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 400kHz
  timeout: 1ms
  id: i2c_a

time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &throttle_avg
    # average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time
    # only send the most recent measurement every 60 seconds
    throttle: 60s
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.0229285099052541  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*throttle_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*throttle_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.0217483660130719  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*throttle_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*throttle_avg, *pos]
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # Copy sensors will filter and then send power measurements to HA
      # These non-throttled power sensors are used for accurately calculating energy
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_a_power
          filters: [*pos]
        current:
          id: phase_a_current
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          id: phase_b_power
          filters: [*pos]
        current:
          id: phase_b_current
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { id:  cir1, filters: [ *pos, multiply: 2 ] }, current: { id: cir1_cur, filters: [*pos, *abs, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "2", power: { id:  cir2, filters: [ *pos, multiply: 2 ] }, current: { id: cir2_cur, filters: [*pos, *abs, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "3", power: { id:  cir3, filters: [ *pos, multiply: 2 ] }, current: { id: cir3_cur, filters: [*pos, *abs, multiply: 2 ] } }
      - { phase_id: phase_b, input:  "4", power: { id:  cir4, filters: [ *pos ] }, current: { id: cir4_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_a, input:  "5", power: { id:  cir5, filters: [ *pos ] }, current: { id: cir5_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_a, input:  "6", power: { id:  cir6, filters: [ *pos ] }, current: { id: cir6_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_b, input:  "7", power: { id:  cir7, filters: [ *pos ] }, current: { id: cir7_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_a, input:  "8", power: { id:  cir8, filters: [ *pos, multiply: 2 ] }, current: { id: cir8_cur, filters: [*pos, *abs, multiply: 2 ] } }
      - { phase_id: phase_a, input:  "9", power: { id:  cir9, filters: [ *pos, multiply: 2 ] }, current: { id: cir9_cur, filters: [*pos, *abs, multiply: 2 ] } }
      - { phase_id: phase_a, input: "10", power: { id: cir10, filters: [ *pos ] }, current: { id: cir10_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_b, input: "11", power: { id: cir11, filters: [ *pos ] }, current: { id: cir11_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_a, input: "12", power: { id: cir12, filters: [ *pos ] }, current: { id: cir12_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_b, input: "13", power: { id: cir13, filters: [ *pos ] }, current: { id: cir13_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_a, input: "14", power: { id: cir14, filters: [ *pos ] }, current: { id: cir14_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_b, input: "15", power: { id: cir15, filters: [ *pos ] }, current: { id: cir15_cur, filters: [*pos, *abs ] } }
      - { phase_id: phase_a, input: "16", power: { id: cir16, filters: [ *pos ] }, current: { id: cir16_cur, filters: [*pos, *abs ] } }
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power
  # The copy sensors filter and send the power state to HA
  - { platform: copy, name: "Phase A Pwr", source_id: phase_a_power, filters: *throttle_avg }
  - { platform: copy, name: "Phase B Pwr", source_id: phase_b_power, filters: *throttle_avg }
  - { platform: copy, name: "Total Pwr", source_id: total_power, filters: *throttle_avg }
  - { platform: copy, name: "Balance Pwr", source_id: balance_power, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_1} Pwr", source_id:  cir1, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_2} Pwr", source_id:  cir2, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_3} Pwr", source_id:  cir3, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_4} Pwr", source_id:  cir4, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_5} Pwr", source_id:  cir5, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_6} Pwr", source_id:  cir6, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_7} Pwr", source_id:  cir7, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_8} Pwr", source_id:  cir8, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_9} Pwr", source_id:  cir9, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_10} Pwr", source_id: cir10, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_11} Pwr", source_id: cir11, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_12} Pwr", source_id: cir12, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_13} Pwr", source_id: cir13, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_14} Pwr", source_id: cir14, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_15} Pwr", source_id: cir15, filters: *throttle_avg }
  - { platform: copy, name: "${circuit_16} Pwr", source_id: cir16, filters: *throttle_avg }

  # The copy sensors filter and send the current state to HA
  - { platform: copy, name: "${circuit_1} Current",  source_id: cir1_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_2} Current",  source_id: cir2_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_3} Current",  source_id: cir3_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_4} Current",  source_id: cir4_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_5} Current",  source_id: cir5_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_6} Current",  source_id: cir6_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_7} Current",  source_id: cir7_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_8} Current",  source_id: cir8_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_9} Current",  source_id: cir9_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_10} Current",  source_id: cir10_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_11} Current",  source_id: cir11_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_12} Current",  source_id: cir12_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_13} Current",  source_id: cir13_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_14} Current",  source_id: cir14_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_15} Current",  source_id: cir15_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "${circuit_16} Current",  source_id: cir16_cur,  filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "Phase A Current", source_id: phase_a_current, filters: *throttle_avg, accuracy_decimals: 1 }
  - { platform: copy, name: "Phase B Current", source_id: phase_b_current, filters: *throttle_avg, accuracy_decimals: 1 }


  - platform: template
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: total_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - platform: template
    lambda: !lambda |-
      return max(0.0f, id(total_power).state -
        id( cir1).state -
        id( cir2).state -
        id( cir3).state -
        id( cir4).state -
        id( cir5).state -
        id( cir6).state -
        id( cir7).state -
        id( cir8).state -
        id( cir9).state -
        id(cir10).state -
        id(cir11).state -
        id(cir12).state -
        id(cir13).state -
        id(cir14).state -
        id(cir15).state -
        id(cir16).state);
    update_interval: never   # will be updated after all power sensors update via on_update trigger
    id: balance_power
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Balance Daily Energy"
    power_id: balance_power
    accuracy_decimals: 0
    restore: false
    filters: *throttle_time
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "${circuit_1} Daily", filters: *throttle_time }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "${circuit_2} Daily", filters: *throttle_time }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "${circuit_3} Daily", filters: *throttle_time }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "${circuit_4} Daily", filters: *throttle_time }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "${circuit_5} Daily", filters: *throttle_time }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "${circuit_6} Daily", filters: *throttle_time }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "${circuit_7} Daily", filters: *throttle_time }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "${circuit_8} Daily", filters: *throttle_time }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name:  "${circuit_9} Daily", filters: *throttle_time }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_10} Daily", filters: *throttle_time }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_11} Daily", filters: *throttle_time }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_12} Daily", filters: *throttle_time }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_13} Daily", filters: *throttle_time }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_14} Daily", filters: *throttle_time }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_15} Daily", filters: *throttle_time }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, restore: false, name: "${circuit_16} Daily", filters: *throttle_time }
```
