### DISCUSSION TITLE
Vue2 needs rebooted periodically to avoid inflated readings

### DISCUSSION THREAD

**Discussion by gmrandom** [emporia-vue-local/esphome#346] [Q&A]
If the vue2 is on for multiple weeks, I start seeing ~0.8kWh of "untracked consumption" every hour in HA Energy dashboard. After a few more days, circuits that have consistent 0.3kWh consumption such as my server rack start reporting inflated readings such as 0.4kWh.

This only affects the kWh sensors. The instant power sensors reporting W are not affected and report correctly.

After rebooting the device, the issue disappears and all sensors go back to reporting correctly. I suspect there might be some overflow issue.

Anyone else seeing this behavior?

**Comment by nonnull-ca** [comment]
I suspect floating-point precision, personally.

`total_daily_energy` does a whole lot more calculation in single-precision uncompensated floats than I'm comfortable with. And uses `millis` to boot.

**Comment by flaviut** [comment]
Floating point precision is good intuition, but it isn't the root cause here. The problem is that the energy readings need to be reset every night. @gmrandom maybe you have an older version of the config, and are running the Vue on a IoT VLAN without internet access. This has been a problem for folks in the past, and the solution is to change the config to rely on HASS for time sync:

```
time:
  # needs some time source to reset daily counters and not accumulate
  # floating-point issues. If Home Assistant isn't available, use sntp and
  # set servers and/or DNS as appropriate: https://esphome.io/components/time/sntp.html
  - platform: homeassistant
    id: my_time
```
