### DISCUSSION TITLE
Can one of the 200A CTs be used to measure an individual load?

### DISCUSSION THREAD

**Discussion by flaviut** [emporia-vue-local/esphome#36] [Q&A]
@MeighenHouse asked:

> I have an electric furnace that uses up to 83.3 amps, higher than what the Vue2 can monitor.
>
> Stock Vue2 software doesn’t allow me to use the third 200 amp CT plug to monitor it, so my question is - is that a hardware issue or could this be configured to do that?
>
> I’m a little unsure from what I’ve read so far.

**Comment by flaviut** [comment]
@Jens5395 replied:

> I use the flexible current sensors that Emporia offers. They are good to 200A, they have a 3.5 mm plug so to use them on the branch circuit inputs I use a 3.5 to 2.5 mm adapter. You could also use the regular Emporia 200 amp sensors with an adapter.
>
> My furnace power line is aluminum so it is pretty darn fat and the regular 200 amp clamp probably would not fit but there is also no room to put a regular 200A clamp in my very crowded electrical panel.
>
> You say 'stock vue2 software' .... all bets are off if you do not use the esphome software.
I use a 4.2 multiplication factor for the two flexible current monitors.

**Reply by MeighenHouse** [reply]
Thanks.  I hadn't considered an adapter for the 200 amp ct, that's really interesting.

One thing I want to be clear on, of the three 200 amp connections I'm only using two, can the third be setup to monitor a regular (tho' high amperage) circuit?  Like, did you need to use one of the 16 sensors because those three were full, or is there a technical reason?

Sorry for the specifics, while setting up this project isn't beyond me, it is at the limits of my knowledge and experience.  Trying to know everything I can before I consider an attempt.

**Comment by flaviut** [comment]
Yes, you should be able to use the third connection. You would need to add an additional entry under `ct_clamps:`, using input C.

I've never tried it, but if you run into issues, please come back and ask!

**Comment by airdrummingfool** [comment]
For anyone that comes across this, there appears to be a 75A hardware limitation in the 2.5mm branch circuit inputs according to Emporia. Here's a quote from [their comment on Reddit](https://www.reddit.com/r/EmporiaEnergy/comments/xdhxq8/comment/iqa44yh/):

> You can use the 200A sensor in the (50A) side ports of the device but you will need a 3.5mm to 2.5mm adapter and you'll need to use a 4x multiplier on that circuit in the app to account for the port/sensor calibration difference.
> 
> The 2.5mm (side) ports have a maximum amperage range of 75A (9000W). If you exceed 75A the sensors and ports will reach saturation and will not report anything higher.

**Reply by Jens5395** [reply]
That explains a few things ....
I have two flexible current probes  (200A, 3.5 mm plug) that plug into some sort of active electronic device which in turn uses a 3.5 mm plug.  These probes were used because the neither the regular (50A) clamps nor the fat (200A) clamps properly fit around the extra fat aluminum wires that are running between my main panel and my central electric heating unit. It just so happens that these sensors end up in a side (2.5 mm) port so they use a 3.5 to 2.5mm converter. As it turns out, to make sense of the readings I had to introduce a 4.2 multiplier.
I thought that since these probes use an active device between the probe and the emporia, the sensor needed calibration when in fact the output of sensors with a 3.5 mm is calibrated to provide full scale output at 200A and the 50A sensors provide a full scale output at 50A.
I just don't understand why this was never made clear in the documentation. Emporia sells 3.5 mm to 2.5 mm adapters and (at the time) no mention was ever made that the scaling of the high power sensor was different from the low power sensor and that software scaling needs to be used to correct for high power devices being plugged into a low power side port.

**Comment by ziptbm** [comment]
@Jens5395 Why did you use 4.2 multiplier?  I've read a 200A should be 4x the 50A (or 8x if on a dual pole), but curious why you found the additional 0.2 helpful.

I've got a 100A dual pole circuit on an EVSE, so only need 80A readings and thought the 75A would be close enough.  I've found that it actually only showed me about 62-63A, so I bought the 3.5mm adapters and got some more 200A CTs, but found that it was showing the same readings.  The initial readings were on a 50A CT on one of the lines with a 2x multiplier.  Maybe this should have been higher to get to 75A?

Using port C as @flaviut suggested is an interesting idea.  Has anyone done this yet successfully?

I'm also wondering if I could just repurpose Ports A & B to act like a side port since I have a Tesla Gateway on my system anyway, so I get the whole home monitoring data from that sensor.  My goal here is to get accurate real-time usage in Home Assistant from my "smart" EVSE (Ford Charge Station Pro, which is quite dumb...).

**Reply by Jens5395** [reply]
I chose a 4.2 multiplier before I knew that the magic figure was 4. I chose it based on my furnace heating coil rated power. I calculated the current I should expect based on the rated power and then tweaked the multiplier to have the emporia report the expected current. Not very accurate but accurate enough for my purposes.
In general, I do not trust the accuracy of any current probe. If you want a reading that you can rely on, I would suggest buying a good current meter (calibrated, not a China special $19.95 meter) and then tweaking each individual multiplication factor to give a match between the measured value from the meter and the emporia readings.
Emporia specifies accuracy as +-2%. Note that they are silent on if that is +- 2% of the reading or +-2% of full rated reading. In other words, if you have a 200 amp sensor on a wire that carries 200A, you should see a reading of between 196 and 204A. I would expect that you see the same spread with a 200A sensor that is clamped to a wire carrying 100A. The reading could be between 96 and 104A. Also, any current probe would have an additional error at both the high end and the low end of it's range which emporia is not specifying. On top of all that, is the accuracy specified in terms of what the emporia tells you,  is it based on what the sensor is capable of or is it the accuracy of the results the emporia tells you with the emporia sensor attached. If the sensor has an accuracy of +-2% and the emporia itself has a +-2% accuracy, you could be talking about +-4% accuracy for the full measuring system.
Being somewhat of a doubter, I take the +- 2% figure mentioned by the sales drones with a heaping spoon full of salt unless I can verify the accuracy with another, calibrated, device.
In your case, with the 200A probe reporting the same reading as the 50A probe, I would make the assumption that the reading you are getting is more or less correct.

**Comment by PhotonHebs** [comment]
Just to confirm, this is indeed possible.  We have single phase 240v in the UK and I am actually using A, B & C, all on 'phase_a' to monitor different circuits.  I have also created two extra negative templates to monitor grid feed in and power to my battery (clamp A & B).  Clamp C is positive only.

Amazing work @flaviut, thank you! 

Here is my code, I hope it helps someone:

```
esphome:
  name: emporia1

external_components:
  - source: github://emporia-vue-local/esphome@dev
    components:
      - emporia_vue

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended


# Enable Home Assistant API
api:
  encryption:
    key: "***********"

  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

ota:
  password: "**************"

# Enable logging
logger:

wifi:
  # Wifi credentials are stored securely by new device wizard.
  ssid: ********
  password: "*****"

mqtt:
  broker: 192.168.*****
  username: **********
  password: *******
  id: emporia1
  log_topic: emporia1log      # KH - this is used to send all data to Node-red via MQTT


preferences:
  # the default of 1min is far too short--flash chip is rated
  # for approx 100k writes.
  flash_write_interval: "48h"

output:
  - platform: ledc
    pin: GPIO12
    id: buzzer

rtttl:
  output: buzzer
  on_finished_playback:
    - logger.log: 'Song ended!'

button:
  - platform: template
    name: "Two Beeps"
    on_press:
      - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

light:
  - platform: status_led
    name: "D3_LED"
    pin: 23
    restore_mode: ALWAYS_ON

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a

time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 2.88 seconds
      window_size: 12
      # we push a new value every 1.44 seconds
      send_every: 6
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.02246975  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
        frequency:
          name: "Phase A Frequency"
          filters: [*moving_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
        phase_angle:
          name: "Phase B Phase Angle"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power In"
          id: phase_a_power_in
          device_class: power
          filters: [*moving_avg, *pos, multiply: 1.030259338 ]
      - phase_id: phase_a         # KH - using phase A for everything
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power In"
          id: phase_b_power_in    # KH - power in only (normal behaviour)
          device_class: power
          filters: [*moving_avg, *pos, multiply: 1.021537566 ]



# KH - capture both in and out (same as original sensor but with the *pos filter removed)
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power In and Out"
          id: phase_a_power_in_out 
          device_class: power
          filters: [*moving_avg, multiply: 1.030259338 ]

# KH - capture both in and out (same as original sensor but with the *pos filter removed)
      - phase_id: phase_a
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power In and Out"
          id: phase_b_power_in_out
          device_class: power
          filters: [*moving_avg, multiply: 1.021537566 ]



# KH - Keeoing this one the same - only need one way monitor (on phase_a again)
      - phase_id: phase_a
        input: "C"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase C Power"
          id: phase_c_power
          device_class: power
          filters: [*moving_avg, *pos, multiply: 1.025366139 ]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_a, input:  "1", power: { name:  "Circuit 1 Power", id:  cir1, filters: [ *moving_avg, *pos, multiply: 1.012962225 ] } }
      - { phase_id: phase_a, input:  "2", power: { name:  "Circuit 2 Power", id:  cir2, filters: [ *moving_avg, *pos, multiply: 1.008728318 ] } }
      - { phase_id: phase_a, input:  "3", power: { name:  "Circuit 3 Power", id:  cir3, filters: [ *moving_avg, *pos, multiply: 1.012431044 ] } }
      - { phase_id: phase_a, input:  "4", power: { name:  "Circuit 4 Power", id:  cir4, filters: [ *moving_avg, *pos, multiply: 1.028064963 ] } }
      - { phase_id: phase_a, input:  "5", power: { name:  "Circuit 5 Power", id:  cir5, filters: [ *moving_avg, *pos, multiply: 1.021537566 ] } }
      - { phase_id: phase_a, input:  "6", power: { name:  "Circuit 6 Power", id:  cir6, filters: [ *moving_avg, *pos, multiply: 1.004529657 ] } }
      - { phase_id: phase_a, input:  "7", power: { name:  "Circuit 7 Power", id:  cir7, filters: [ *moving_avg, *pos, multiply: 1.011370351 ] } }
      - { phase_id: phase_a, input:  "8", power: { name:  "Circuit 8 Power", id:  cir8, filters: [ *moving_avg, *pos, multiply: 1.007675365 ] } }
      - { phase_id: phase_a, input:  "9", power: { name:  "Circuit 9 Power", id:  cir9, filters: [ *moving_avg, *pos, multiply: 1.002964156 ] } }
      - { phase_id: phase_a, input: "10", power: { name: "Circuit 10 Power", id: cir10, filters: [ *moving_avg, *pos, multiply: 1.005576042 ] } }
      - { phase_id: phase_a, input: "11", power: { name: "Circuit 11 Power", id: cir11, filters: [ *moving_avg, *pos, multiply: 1.006100052 ] } }
      - { phase_id: phase_a, input: "12", power: { name: "Circuit 12 Power", id: cir12, filters: [ *moving_avg, *pos, multiply: 0.991631228 ] } }
      - { phase_id: phase_a, input: "13", power: { name: "Circuit 13 Power", id: cir13, filters: [ *moving_avg, *pos, multiply: 1.00400728 ] } }
      - { phase_id: phase_a, input: "14", power: { name: "Circuit 14 Power", id: cir14, filters: [ *moving_avg, *pos, multiply: 1.007675365 ] } }
      - { phase_id: phase_a, input: "15", power: { name: "Circuit 15 Power", id: cir15, filters: [ *moving_avg, *pos, multiply: 1.043061048 ] } }
      - { phase_id: phase_a, input: "16", power: { name: "Circuit 16 Power", id: cir16, filters: [ *moving_avg, *pos, multiply: 1.008728318 ] } }
  

# KH - My version of Total Power (I have specific needs - all sensors less A, B C, 1 & 3)
  - platform: template
    name: "Total AC Demand"
    lambda: return id(cir2).state + id(cir4).state + id(cir5).state + id(cir6).state + id(cir7).state + id(cir8).state + id(cir9).state + id(cir10).state + id(cir11).state + id(cir12).state + id(cir13).state + id(cir14).state + id(cir15).state + id(cir16).state;
    update_interval: 1s
    id: total_power
    unit_of_measurement: "W"


 # KH - Clamp A negative (uses phase_a_power_in_out 'A' sensor to read only negative values)
  - platform: template
    name: "Phase A Power Out"
    id: phase_a_power_out
    lambda: |-
      if (id(phase_a_power_in_out).state > 0) {
        return 0;
      } else {
        return abs(id(phase_a_power_in_out).state) ;
      }
    accuracy_decimals: 1
    unit_of_measurement: "W"
    device_class: power
    update_interval: 1s



  # KH - Clamp B negative (uses phase_b_power_in_out 'B' sensor to read only negative values)
  - platform: template
    name: "Phase B Power Out"
    id: phase_b_power_out
    lambda: |-
      if (id(phase_b_power_in_out).state > 0) {
        return 0;
      } else {
        return abs(id(phase_b_power_in_out).state) ;
      }
    accuracy_decimals: 1
    unit_of_measurement: "W"
    device_class: power
    update_interval: 1s


  - platform: total_daily_energy
    name: "Total AC Demand Daily"
    power_id: total_power
    accuracy_decimals: 0
    
  - { power_id:  phase_a_power_in, platform: total_daily_energy, accuracy_decimals: 0, name:  "Clamp A Daily In" }              # KH - daily energy for phase_a_power_in
  - { power_id:  phase_b_power_in, platform: total_daily_energy, accuracy_decimals: 0, name:  "Clamp B Daily In" }              # KH - daily energy for phase_b_power_in
  - { power_id:  phase_a_power_in_out, platform: total_daily_energy, accuracy_decimals: 0, name:  "Clamp A Daily In and Out" }  # KH - daily energy for phase_a_power_in_out
  - { power_id:  phase_b_power_in_out, platform: total_daily_energy, accuracy_decimals: 0, name:  "Clamp B Daily In and Out" }  # KH - daily energy for phase_b_power_in_out
  - { power_id:  phase_a_power_out, platform: total_daily_energy, accuracy_decimals: 0, name:  "Clamp A Daily Out" }            # KH - daily energy for phase_a_power_out
  - { power_id:  phase_b_power_out, platform: total_daily_energy, accuracy_decimals: 0, name:  "Clamp B Daily Out" }            # KH - daily energy for phase_b_power_out
  - { power_id:  phase_c_power, platform: total_daily_energy, accuracy_decimals: 0, name:  "Clamp C Daily Energy" }
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 1 Daily Energy" }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 2 Daily Energy" }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 3 Daily Energy" }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 4 Daily Energy" }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 5 Daily Energy" }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 6 Daily Energy" }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 7 Daily Energy" }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 8 Daily Energy" }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 9 Daily Energy" }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 10 Daily Energy" }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 11 Daily Energy" }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 12 Daily Energy" }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 13 Daily Energy" }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 14 Daily Energy" }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 15 Daily Energy" }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 16 Daily Energy" }
```
