### DISCUSSION TITLE
Power Fator, Reactive Power, Current

### DISCUSSION THREAD

**Discussion by Telk0** [emporia-vue-local/esphome#65] [Q&A]
Hello,

Have any had succes adding these 3 readings to their configuration?

Best regards
Martin.

**Comment by airdrummingfool** [comment]
I set up current sensors doing something like this:

1. Make sure the `voltage` keys in the `phases` config have `id`s:
```yaml
    phases:
      - id: phase_a
        input: RED
        calibration: 0.022
        voltage:
          name: "Phase A Voltage"
          id: phase_a_voltage # <-- make sure this is set to something
          filters: [*pos, *moving_avg]
```

2. Create some filters for the external-facing entities:
```yaml
.defaultfilters:
  - &current_min
    # Throttle to ≈3s but take the max, since I personally care about the highest current measured in a given timeframe
    # if you don't want max, change `max` to `sliding_window_moving_average` to get an average of the last ≈3 seconds
    max:
      window_size: 6
      send_every: 6
  - &current_max
    or:
      - delta: 0.1
      - throttle: 60s
```

3. My CT clamps for reference
```yaml
    ct_clamps:
      - { phase_id: phase_a, input: "A", power: { id: power_phase_a, filters: [*pos, *calibrate], internal: true } } # Total Phase A Power
      - { phase_id: phase_b, input: "B", power: { id: power_phase_b, filters: [*pos, *calibrate], internal: true } } # Total Phase B Power
```

4. Calculate current for phase A, phase B, and add them together to get total home current
```yaml
  # Calculate current for each circuit
  - platform: template
    # name: "Phase A Current"
    id: current_phase_a
    lambda: return id(power_phase_a).state / id(phase_a_voltage).state;
    update_interval: 0.48s
    unit_of_measurement: "A"
    device_class: current
    internal: true
  - platform: template
    # name: "Phase B Current"
    id: current_phase_b
    lambda: return id(power_phase_b).state / id(phase_b_voltage).state;
    update_interval: 0.48s
    unit_of_measurement: "A"
    device_class: current
    internal: true
  - platform: template
    # name: "Total Home Current"
    id: current_home_total
    lambda: return id(current_phase_a).state + id(current_phase_b).state;
    update_interval: 0.48s
    unit_of_measurement: "A"
    device_class: current
    internal: true
```

6. Separate entities that get filtered and pushed to HA:
```yaml
  # External-facing current entities
  - { platform: copy, name: "Phase A Current",    source_id: current_phase_a,    filters: [ *current_min, *current_max ] }
  - { platform: copy, name: "Phase B Current",    source_id: current_phase_b,    filters: [ *current_min, *current_max ] }
  - { platform: copy, name: "Total Home Current", source_id: current_home_total, filters: [ *current_min, *current_max ] }
```
