### DISCUSSION TITLE
Show energy in kWh?

### DISCUSSION THREAD

**Discussion by TommySharpNZ** [emporia-vue-local/esphome#69] [Q&A]
Could someone give some example of how to record the energy in kWh instead of Wh?

**Comment by flaviut** [comment]
You can [use `filters` and `unit_of_measurement`](https://esphome.io/components/sensor/index.html#config-sensor)

```
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      unit_of_measurement: kW
```

Note that the above can also be written like this, and that these two snippets mean exactly the same thing:

```
filters: { multiply: 0.001 }, unit_of_measurement: "kW"
```

**Reply by btarb24** [reply]
```
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 2.88 seconds
      window_size: 12
      # we push a new value every 1.44 seconds
      send_every: 6
```
Assuming that the 1.44s sample rate in the yaml is reliable, you'd be able to use the formula on this stack: https://electronics.stackexchange.com/questions/641818/convert-watts-collected-at-set-interval-over-set-time-period-into-kwh

khw = totalWatts * 1.44 / 3600

or

kwh = totalWatts * .0004

Although, be mindful that the yaml config wont really allow us to derive the true 'billing quality' kwh since it uses a sliding window moving average.  Each sample reported to ha is actually an average of the last 12 samples ... but we send it every 6 samples.  So each ha value is skewed by the prior value we already reported.  You can actually observe this by looking at your series charts - When a circuit turns off there will always be 1 point that's halfway-ish between the last value and 0, this is because it is actually the average of 0 and that last value.
https://i.imgur.com/lYt5Yzo.png


This large sliding window makes for less noise, but also less accuracy since the sample window is larger than the reporting window.  Though, this also causes a falsely-low report when a load turns on, so i suppose it may average out well enough?
