### DISCUSSION TITLE
Value differences with Shelly EM

### DISCUSSION THREAD

**Discussion by PepereLoulou** [emporia-vue-local/esphome#76] [General]
Hello,
I just tested my Emporia Vue under ESPhome, and I find errors with the information given by the clamps.

For air conditioning that does not heat up (on hold):
Shelly EM: ​​208W
**Emporia: 15W (!?!?)**
Measured: 1.05A (x 230V x PF 0.85 = 206W)

Heating air conditioning, max:
Shelly EM: ​​1286W
Emporia: 1764W

Air conditioning 1 day:
Shelly EM: ​​8.26kWh
Emporia: 6.43kWh

With the boiler the difference is less important:

Boiler off heating:
Shelly EM: ​​0W
Emporia: 0.3W

Boiler in heating:
Shelly EM: ​​2707W
Emporia: 2743W

Boiler 1 day:
Shelly EM: ​​15.50 kWh
Emporia: 15.63kWh

Why this difference?

**Comment by flaviut** [comment]
Did you match up the voltage phases and the current clamp phases correctly?

**Comment by PepereLoulou** [comment]
Yes, the 2 are done.

**Reply by flaviut** [reply]
try switching the phase on the misbehaving current clamp anyway.

**Reply by PepereLoulou** [reply]
If I understand : I switch the phase (actually A) into ESPHOME ?

I used second clamp with emporia to verify the values: there are the same. The clamp is not the problem.

**Reply by flaviut** [reply]
No, 100% software. In your config, make sure `phase_id` is correct:

```
      - { phase_id: phase_a, input:  "1", power: { name:  "Circuit 1 Power", id:  cir1, filters: [ *moving_avg, *pos ] } }
```

maybe switch it to `phase_b`, `phase_c`, `phase_a`, or whatever it may be,

**Reply by PepereLoulou** [reply]
phase_a = 15,9 W
phase_b = 0 W
phase_c = 214 W (!!!)

(Shelly = 210 W)

The phase are wrongs ??

**Reply by flaviut** [reply]
Yes, all the phases in the config are wrong. The config is there just as an example, you will need to extensively modify it for your situation. [Part 1 of the guide](https://gist.github.com/flaviut/93a1212c7b165c7674693a45ad52c512#panel-installation-part-1) goes into detail about the information you need to collect to correctly configure the device.

**Reply by PepereLoulou** [reply]
I put the good color for phases and the good letter for each clamp !

I do an error… I good to search where 😅

Thanks a lot !

**Reply by PepereLoulou** [reply]
I checked my entire installation of the Emporia Vue 2...and it's good.

Phase A is on RED cable.
Phase B is on BLACK cable.
Phase C is on BLEU cable.

Air conditioning is on Phase A.

It is possible phase A and phase C are reversed on software ?


Here my ESPhome firmware:


```
esphome:
  name: emporia-vue2

external_components:
  - source: github://flaviut/esphome@emporia-vue-2022.4.0
    components: [ emporia_vue ]

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable Home Assistant API
ota:
  password: !secret password_ota
api:
  password: !secret password_api

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a
time:
  - platform: sntp
    id: my_time

# these are called references in YAML. They allow you to reuse
# this configuration in each sensor, while only defining it once
.defaultfilters:
  - &moving_avg
    # we capture a new sample every 0.24 seconds, so the time can
    # be calculated from the number of samples as n * 0.24.
    sliding_window_moving_average:
      # we average over the past 2.88 seconds
      window_size: 12
      # we push a new value every 1.44 seconds
      send_every: 6
  - &invert
    # invert and filter out any values below 0.
    lambda: 'return max(-x, 0.0f);'
  - &pos
    # filter out any values below 0.
    lambda: 'return max(x, 0.0f);'
  - &abs
    # take the absolute value of the value
    lambda: 'return abs(x);'
 # - &multiply # Current scaling factor
 #   lambda: 'return x * 0.01;'

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: RED  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
      - id: phase_b  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLACK  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase B Voltage"
          filters: [*moving_avg, *pos]
      - id: phase_c  # Verify that this specific phase/leg is connected to correct input wire color on device listed below
        input: BLUE  # Vue device wire color
        calibration: 0.022  # 0.022 is used as the default as starting point but may need adjusted to ensure accuracy
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        voltage:
          name: "Phase C Voltage"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg, *pos ]
        current:
          name: "Phase A - Charge"
          id: main_house_current_a
          device_class: current
          filters: [*moving_avg, *pos]
      - phase_id: phase_b
        input: "B"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg, *pos ]
        current:
          name: "Phase B - Charge"
          id: main_house_current_b
          device_class: current
          filters: [*moving_avg, *pos]
      - phase_id: phase_c
        input: "C"  # Verify the CT going to this device input also matches the phase/leg
        power:
          name: "Phase C Power"
          id: phase_c_power
          device_class: power
          filters: [*moving_avg, *pos ]
        current:
          name: "Phase C - Charge"
          id: main_house_current_c
          device_class: current
          filters: [*moving_avg, *pos]
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      - { phase_id: phase_c, input:  "1", power: { name:  "01 Power", id:  cir1, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "2", power: { name:  "02 Power", id:  cir2, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input:  "3", power: { name:  "03 Power", id:  cir3, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "4", power: { name:  "04 Power", id:  cir4, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "5", power: { name:  "05 Power", id:  cir5, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "6", power: { name:  "06 Power", id:  cir6, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "7", power: { name:  "07 Power", id:  cir7, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "8", power: { name:  "08 Power", id:  cir8, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input:  "9", power: { name:  "09 Power", id:  cir9, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "10", power: { name: "10 Power", id: cir10, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "11", power: { name: "11 Power", id: cir11, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "12", power: { name: "12 Power", id: cir12, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "13", power: { name: "13 Power", id: cir13, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "14", power: { name: "14 Power", id: cir14, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_b, input: "15", power: { name: "15 Power", id: cir15, filters: [ *moving_avg, *pos ] } }
      - { phase_id: phase_a, input: "16", power: { name: "16 Power", id: cir16, filters: [ *moving_avg, *pos ] } }
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state + id(phase_c_power).state;
    update_interval: 1s
    id: total_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, name:  "01 Daily Energy" }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, name:  "02 Daily Energy" }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, name:  "03 Daily Energy" }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, name:  "04 Daily Energy" }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, name:  "05 Daily Energy" }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, name:  "06 Daily Energy" }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, name:  "07 Daily Energy" }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, name:  "08 Daily Energy" }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, name:  "09 Daily Energy" }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, name: "10 Daily Energy" }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, name: "11 Daily Energy" }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, name: "12 Daily Energy" }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, name: "13 Daily Energy" }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, name: "14 Daily Energy" }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, name: "15 Daily Energy" }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, name: "16 Daily Energy" }
  - { power_id: phase_a_power, platform: total_daily_energy, accuracy_decimals: 0, name:  "Phase A Daily Energy" }
  - { power_id: phase_b_power, platform: total_daily_energy, accuracy_decimals: 0, name:  "Phase B Daily Energy" }
  - { power_id: phase_c_power, platform: total_daily_energy, accuracy_decimals: 0, name:  "Phase C Daily Energy" }

  - platform: template       # Sum of all cir wattages
    name: "Main house Calculated total watts"
    id: calculated_total_watts
    lambda: return (id(cir1).state + id(cir2).state + id(cir3).state + id(cir4).state + id(cir5).state + id(cir6).state + (id(cir7).state + id(cir8).state + id(cir9).state + id(cir10).state + id(cir11).state + id(cir12).state + id(cir13).state + id(cir14).state + id(cir15).state));
    update_interval: 60s
    accuracy_decimals: 0
    # Take the total power and subtract all of the individually monitored circuits which will result in the remaining balance of power that is not individually monitored
  - platform: template
    name: "Main house Balance Power"
    lambda: return max((id(total_power).state - id(cir1).state - id(cir3).state - id(cir4).state - id(cir5).state - id(cir6).state - id(cir7).state - id(cir8).state - id(cir9).state - id(cir10).state - id(cir11).state - id(cir12).state - id(cir13).state - id(cir14).state - id(cir15).state), 0.0f);
    update_interval: 3s
    id: balance_power
    unit_of_measurement: "W"
```
