### DISCUSSION TITLE
Can I use phase input A and B both with phase_id: phase_a  (we have mono-phase net)

### DISCUSSION THREAD

**Discussion by ironirc** [emporia-vue-local/esphome#95] [Q&A] [answered]
Initially had the impression that this is working but the readings seem to be off since I configured it this way.
Is there some hard wired electronics in place assuming 120 degrees phase shift?

```
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a
        input: BLACK
        calibration: 0.0232
        voltage:
          name: "Phase A Voltage"
          filters: [*moving_avg, *pos]
    ct_clamps:
      - phase_id: phase_a
        input: "A"
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: [*moving_avg ]
      - phase_id: phase_a
        input: "B"
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: [*moving_avg]
```
